- ODIN_II/SRC/output_blif.c
Fixing a bug that caused mcml to fail on the weekly regression test. There were some else statement missing when a previous commit added some ifs
> Mcml weekly regression fail bug fix

- LICENSE.md
- README.md
This resolves #124. I have added license information according to @kmurray's answer mentioning [this page](http://www.eecg.utoronto.ca/vtr/terms.html).
I have only ommitted the registration statement ("Also, we appreciate it if users of the package register before downloading the tool but this is by no means a requirement.")
> Add license information

- vpr/SRC/route/rr_graph.c
Implementation of issue I describe in " Extra multiplication '* Type->height' #133 "
> Fixed pin placement for tall macros

- ODIN_II/SRC/lib_blif/output_blif.cpp
- ODIN_II/SRC/odin_ii.cpp
- ODIN_II/SRC/types.h
- Add Command Line Option `-black_box_latches` to Treat Latches as BlackBoxes and Output them as such
- Add flag in output_bliff.cpp to track if we have generated a BlackBoxed Latch
- Output Latch BlackBox Model to BLIF File if Command Line Argument is specified and if we have previously generated a BlackBoxed Latch in the BLIF File
- Output Latches as BlackBoxed Latch when Command Line Argument has been specified
`ABC` not handling Latches correctly.
It solves an issue with `ABC` not handling Latches correctly.
Ran `ODIN_II/verify_full.sh`, `run_quick_test.pl`, `vtr_reg_basic` and `vtr_reg_strong` regression tests with no qor test or run failures.
> [Odin] Add Ability to Treat Latches as BlackBoxes and Output them to the BLIF File as Such

- libeasygl/src/graphics.cpp
The old code was drawing the text above the bounding box. Now, the text will actually be centred on the given point.
Quite embarrassingly, I introduced this bug years ago.
> text no longer draws above bounding box

- vpr/src/route/rr_graph_reader.cpp
Previously newType was only ever set to NUM_RR_TYPES which meant that
the side and direction processing was never called.
Fixes #247.
> Fix rr_graph_reader loading of direction and side attributes.

- libs/libarchfpga/src/echo_arch.cpp
Small fix to the `arch.echo` file output.
Before: `fc_value_type: FRACTIONALfc_value: 0.000000segment: globalpins: 0 1 2 3`
After: `fc_value_type: FRACTIONAL fc_value: 0.000000 segment: global pins: 0 1 2 3`
> Add spaces to echo_arch file for fc_value_type output.

- vpr/src/route/rr_graph_reader.cpp
It's useful to get an echo file after an rr_graph is loaded from an external file.
> Echo the file after loading.

- libs/libarchfpga/src/read_xml_arch_file.cpp
Throw an error about the which blif_model is missing and on what pb_type that blif_model is referenced from. Previously it would just die with an assert which made it hard to figure out what was missing.
> libarchfpga: Throw an error on missing blif.

- vpr/src/route/rr_graph.cpp
Previously it would either fail the assert or segfault. Now it outputs
errors like the following;
```
Error 1:
Type: Architecture file
File: artix7/arch/xc7a50t-roi-virt/merged.xml
Line: 22106
Message: Unable to find block BLK_MB-INT_R-CLBLL_R-INT_R.
```
> Improve errors on direct CLB to CLB interconnects.

- doc/src/arch/reference.rst
- libs/libarchfpga/src/physical_types.h
`s/Inpterpretted/Interpreted/`
[See the result here](http://vtr-verilog-to-routing.readthedocs.io/en/inpterpretted/arch/reference.html#tag-<fcdefault_in_type=).
> docs: Small spelling fixes.

- vpr/CMakeLists.txt
- vpr/src/pack/output_clustering.cpp
Replaces hand-written XML generation of cluster packing output (.net file) with equivalent pugixml calls.
#291 
Reduce likelihood of errors and overall complexity of output generation code by leveraging a well-tested library.
Output from the original and pugixml implementations were passed through 'xmllint --c14n' and then diffed. Inputs, outputs, and clocks tags have differences in leading/trailing white space but no other meaningful changes were noticed.
> Rewrite output_clustering using pugixml

- .github/autolabeler.yml
Probot AutoLabeler bot will add labels to pull requests automatically
based on this config.
Having these labels makes it easier to see at a quick glance what a pull
request is about.
More info here;
* https://github.com/probot/autolabeler
* https://github.com/apps/probot-autolabeler
After merging this pull request. Add the [Probot AutoLabeler GitHub app](https://github.com/apps/probot-autolabeler) to either all verilog-to-routing repos or just the vtr-verilog-to-routing repo. Then on the next pull request the bot will add labels as shown in the screenshot below;
> infra: Adding a probot autolabeler configuration.

- doc/src/vpr/file_formats.rst
- libs/libarchfpga/src/read_xml_arch_file.cpp
- vpr/src/base/netlist.h
- vpr/src/base/netlist.tpp
- vpr/src/base/read_blif.cpp
- vpr/src/base/read_netlist.cpp
- vpr/src/pack/cluster_router.cpp
- vpr/src/pack/output_clustering.cpp
This extends the work on EBLIF support by tracking the parameters and attributes of netlist block objects, and outputs them in the XML using the following syntax:
```
<attribute name="test_attr">1</attribute>
<parameter name="test_param">x</parameter>
```
This fixes #281
This will help in the efforts to support real FPGA architectures in VPR
Standard tests and specific tests with attributes and parameters in eblif types were done
> Propagate attributes and parameters from eblif to post-clustering .net file

- doc/src/vpr/file_formats.rst
- vpr/src/route/rr_graph_reader.cpp
- vpr/src/route/rr_graph_writer.cpp
Add additional metadata to rr_graph <pin_class> entries to make manipulating rr_graphs easier outside VPR.
I've taken @mithro's changes towards this and made some minor cleanup for this PR (commit description, minor formatting, drop unrelated changes)
rr_graph_writer.cpp was modified to output this new format with corresponding changes in rr_graph_reader.cpp
This supports work in the symbiflow-arch-defs repo towards importing ice40 routing, which cannot be represented by the arch.xml format
Currently rr_graph exports pin classes like this:
<pin_class type="INPUT">0</pin_class>
Where the 0 index comes from a std::map internal to vpr. It is very difficult for external applications to predict how these indices are assigned to determine the original pin names.
@mithro proposed this should be …
> rr_graph: write pin name in addition to index

- vpr/src/place/place.cpp
Small fix to the place type mismatch error. Found when using `--fix_pins` and being unable to understand why the error was happening.
Previous: 
```
Error 1857: Block 10 type does not match grid location (1,10) type.
```
Current: 
```
Error 1857: Block 10 type (BLK_TL-PIO_R) does not match grid location (1,10) type (BLK_TL-PIO_L).
```
> vpr: Better error message for type mismatch.

- vpr/src/pack/output_clustering.cpp
This define is not referenced anywhere in the code base.
> Remove obsolete define.

- vpr/src/route/rr_graph_area.cpp
Output the human name for the node type.
> vpr: Slightly better error message.

- vpr/src/pack/lb_type_rr_graph.cpp
This makes the output *much* easier to read.
Before;
```
Node 127
BEL_FF-SB_FF[0].E[0]
Type: LB_INTERMEDIATE
Capacity: 1
Intrinsic Cost: 0
Mode: 0   # Outedges: 0
Mode: 1   # Outedges: 0
Mode: 2   # Outedges: 5
(140, 1) (141, 1) (142, 1) (143, 1) (144, 1)
(145, 1)
Mode: 3   # Outedges: 1
(144, 1)
```
After;
```
Node 127
BEL_FF-SB_FF[0].E[0]
Type: LB_INTERMEDIATE
Capacity: 1
Intrinsic Cost: 0
Mode: 0   # Outedges: 0
Mode: 1   # Outedges: 0
Mode: 2   # Outedges: 5
(140, 1) (141, 1) (142, 1) (143, 1) (144, 1)
(145, 1)
Mode: 3   # Outedges: 1
(144, 1)
```
> vpr: Fixing the output of edges in the lb_type_rr_graph.echo file.

- Makefile
Means you don't have to modify the Makefile to set BUILD_TYPE. You can just go `export BUILD_TYPE=debug` and you get a debug build.
> Allow BUILD_TYPE to be overridden in environment.

- vpr/src/route/check_rr_graph.cpp
When loading the rr graph, bounds check ptr_num (e.g. track_num) for type == CHANY.
CHANX ptr_num's have to abide this restriction.
Ran "./run_reg_test.pl vtr_reg_basic"
> Check ptr_num on y channels too.

- vpr/src/pack/cluster_router.cpp
Before;
```
net temp0 num targets 2
NULL
net outc num targets 2
NULL
```
After;
```
net temp0 num targets 2
(1207-->0) (0-->45) (45-->90) (90-->103) (103-->108) (108-->112) (112-->107) (107-->130) (130-->180) (180-->1253)
net outc num targets 2
(181-->131) (131-->223) (223-->224) (224-->99) (99-->80) (80-->35) (35-->1209) (1209-->1208)
```
> vpr: Print route before doing cleanup.

- vpr/src/pack/output_clustering.cpp
Minor style cleanup in `output_clustering.cpp` file.
> vpr/pack: Fix weird wrapping in output_clustering.cpp

- doc/src/_static/css/vtr.css
- doc/src/conf.py
Adding a one-liner CSS stylesheet (can be used for other custom additions in the future) to fix the problem where XML definitions extend beyond the line width and generally look bad.
A simple `white-space: pre-wrap` fixes the issue.
See e.g. here: https://docs.verilogtorouting.org/en/latest/arch/reference/#tag-recognized-blif-models-models-port
The reason I am fixing it in a custom CSS and not in the theme is that you are using a custom domain for XML and it's a very niche use case. In practice, no one in RTD is expecting the class name to have spaces - your extension is putting the entire XML tag (which is long and includes spaces, so can be wrapped) into the code.classname element.
#421
Makes docs look like they're not broken!
Tested the changes on a local build and also live in browser …
> Add custom CSS to fix broken (too long) descnames styling

- ODIN_II/SRC/partial_map.cpp
> ODIN_MEMLEAK: freed muxes in partial_map.cpp

- ODIN_II/SRC/netlist_create_from_ast.cpp
> ODIN_MEMLEAK: freed ref_string in netlist_create_from_ast.cpp

- ODIN_II/SRC/netlist_create_from_ast.cpp
WIP ODIN_DEBUG: Fix for [0:0] data width crash using SPR
SRC: netlist_create_from_ast.cpp
A function call to create a node's full name was fixed so that it would properly insert the end of the name in the case of a data width (port size) of 1.
The bug would cause a segmentation fault when specifying a data width of 1 in memory_controller.v and running it on odin_II.cpp. The issue seemed to arise because when using single-port-ram, certain input drivers could not be detected mid-synthesis.
Having a data width of 1 is a valid special case.
memory_controller.v was tested primarily, using data/address widths of 1/1, 2/1, 2/2 as well as other larger values.
> ODIN_DEBUG: Fix for [0:0] data width segmentation fault

- CMakeLists.txt
- ODIN_II/CMakeLists.txt
- ODIN_II/SRC/odin_ii.cpp
- libs/CMakeLists.txt
- libs/librtlnumber/.gitignore
- libs/librtlnumber/CMakeLists.txt
- libs/librtlnumber/Makefile
- libs/librtlnumber/README.md
- libs/librtlnumber/main.cpp
- libs/librtlnumber/regression_tests/basic_regression_tests.csv
- libs/librtlnumber/regression_tests/compound_regression_test.csv
- libs/librtlnumber/src/include/internal_bits.hpp
- libs/librtlnumber/src/include/rtl_int.hpp
- libs/librtlnumber/src/include/rtl_utils.hpp
- libs/librtlnumber/src/rtl_int.cpp
- libs/librtlnumber/src/rtl_utils.cpp
- libs/librtlnumber/unit_test/Makefile
- libs/librtlnumber/unit_test/verilog_bits.cpp
- libs/librtlnumber/verify_librtlnumber.sh
librtlnumber - Register Transfer Level (RTL) Verilog Number Library
- Arbitrary Length Verilog Number Library that can Handle 'X' and 'Z' inputs.
- Authors: Aaron Graham (aaron.graham@unb.ca, aarongraham9@gmail.com),
Jean-Philippe Legault (jlegault@unb.ca, jeanphilippe.legault@gmail.com)
and Dr. Kenneth B. Kent (ken@unb.ca)
for the Reconfigurable Computing Research Lab at the
Univerity of New Brunswick in Fredericton, New Brunswick, Canada
> librtlnumber - Register Transfer Level (RTL) Verilog Number Library

- vpr/src/place/timing_place_lookup.cpp
The placer code assumes all tiles have at least one source and sink.  IPAD and OPAD tiles generally speaking don't look like that, having only 1 sink or source.
Allow for tiles with only an IPAD or OPAD.
> Allow placement of tiles with only sources or sinks.

- vpr/src/route/rr_graph_reader.cpp
Encountered a segfault due to memory corruption on a custom rr graph.  Valgrind was required to find the issue, rather than a straight forward error message.
> Add some missing bounds check on rr_graph reading.

- ODIN_II/SRC/include/verilog_preprocessor.h
Signed-off-by: Prayas Arora <arora.prayas@gmail.com>
Fixed [-Wmissing-declarations] warning in VTR/master
- wrote function prototype in ODIN_II/SRC/include/verilog_preprocessor.h file.
Run the following commands from VTR root directory:
```
$ make clean
$ make
```
Issue Link: https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/540
VTR should compile cleanly without warnings in favor of the user.
Command: ./run_quick_test.pl
All tests of vtr_reg_basic passed
- [`x`] Bug fix (change which fixes an issue)
- [`x`] All new and existing tests passed
> Fixed [-Wmissing-declarations] warning in VTR/master

- vpr/src/route/rr_graph_reader.cpp
Previous error would only indicate out of bounds, but not which array or index.
> Add useful error message on CHAN PTC check.

- ODIN_II/.gitignore
- ODIN_II/SRC/implicit_memory.cpp
- ODIN_II/SRC/memories.cpp
- ODIN_II/SRC/netlist_create_from_ast.cpp
- ODIN_II/regression_test/benchmark/syntax/inferred_DPram.v
- ODIN_II/regression_test/benchmark/syntax/inferred_SPram.v
Leave the zero paddings of the implicit ram for later to be able to collapse it.
No issue raised, but SP ram was always initialized, now this fixes it to also use SP_ram when only a single call to the ram is used.
added a test to assure that single port rams are initialized
- [ x ] Bug fix (change which fixes an issue)
- [x ] I have added tests to cover my changes
> Odin: single port implicit ram wrongly initialized as dual port

- libs/libvtrutil/src/vtr_flat_map.h
* flat_map assertion could generate invalid iterator on small maps.
> Correct flat_map assertion.

- ODIN_II/SRC/netlist_create_from_ast.cpp
The AST needs to be simplified before submodules are instantiated to be able to support new instantiations in generate blocks
> ODIN II: moved simplify_ast_module()

- ODIN_II/SRC/include/multipliers.h
- ODIN_II/SRC/multipliers.cpp
- ODIN_II/SRC/partial_map.cpp
Before this PR odin will never implement a multiplier using soft logic if the architecture has a hard multiplier. Which is fixed in 01659c2a68a5951bb7d9a11a1845d968dfaf3195. This PR also fixes the logic of splitting a multiplier into multiple smaller multipliers (2edfbb9a7d9fbf2c60b7c730696ffaf15ef3082f). Finally, it adds a way of implementing soft multipliers using AND gates and a balanced adder tree if the architecture has hard adders instead of implementing soft multipliers using AND gates and soft multipliers only previously (9f591fb287e57189688112bb5de897cca297149c).
> Fixing the logic of splitting multipliers and adding the capability of implementing soft multipliers as AND gates and a balanced adder tree

- libs/EXTERNAL/libpugixml/CMakeLists.txt
This enables PugiXML's [compact mode](https://pugixml.org/docs/manual.html#dom.memory.compact), which optimizes document structures for memory usage instead of efficiency of access.
This is originally discussed in [SymbiFlow/vtr-verilog-to-routing/#34](https://github.com/SymbiFlow/vtr-verilog-to-routing/pull/34). A benchmark using Artix 7's RR graph(1.9M nodes, 4M annotated edges) gives these results:
>Create Device times:
>
>| Reader | Time to create device(5 runs) | max_rss to create device |
>|------------|-----------------------------------------|---------------------------|
>|PugiXML|`21.78 21.68 21.9 21.71 21.99`|5902.4 MiB|
>|PugiXML compact|`25.17 24.63 24.43 24.59 24.16`|3200.3 MiB|
>|LibXML2 SAX|`31.31 30.96 30.83 30.99 30.85`|1895.5 MiB|
This is a one-line PR which adds …
> Enable PugiXML compact mode

- ODIN_II/SRC/netlist_create_from_ast.cpp
- ODIN_II/SRC/parse_making_ast.cpp
- ODIN_II/SRC/verilog_bison.y
- ODIN_II/regression_test/benchmark/syntax/multi_module_io_data_types.v
Fixed a bug that prevented input/output declarations to include a data type (i.e. output reg, input wire, output wire).
https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/603
new syntax test
local tests
> ODIN II: fixed output reg/output wire/input wire bug

- ODIN_II/SRC/verilog_flex.l
Allows tri, tri0, tri1 to be parsed as wires.
https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/605
> ODIN II: initial implementation for tri, tri0, tri1

- vpr/src/base/read_route.cpp
- vpr/src/base/vpr_api.cpp
These are two cases where work is being done twice.  The first case is
that the routing graph is being generated (or read from a file) twice.
The second is that when a routing graph load is done, the check_route
routine is called twice, once in the load function and another in the
root level flow function.
> Avoid duplicate work during flow.

- vpr/src/route/rr_graph.cpp
- vpr/src/route/rr_graph2.cpp
- vpr/src/route/rr_graph_reader.cpp
This PR adds the possibility to allow channel segments to have non-consecutive ptc.
More information about the issue can be found here: https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/606
SymbiFlow architectures do have channels which have non-consecutive ptc, generating an error while reading the RR graph. More specifically, the lines that produce the issue are the following:
https://github.com/verilog-to-routing/vtr-verilog-to-routing/blob/411331f32b286273ed06eb4e4171c62c700e6f76/vpr/src/route/rr_graph_reader.cpp#L748-L777
Track all the places where `PTC` is used for getting the node information.
> rr_graph_reader: allow non-consecutive ptc

- vpr/src/analysis/timing_reports.cpp
- vpr/src/analysis/timing_reports.h
- vpr/src/base/vpr_api.cpp
This will be used to add timing report outputs other than the final
post-route report.
https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/653
This allows the report generation functions generate_setup_timing_stats and generate_hold_timing_stats to be invoked by multiple callsites without colliding on the file names.
Compiles and CI should pass once https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/655 is resolved
> Add argument to add prefix to timing report.

- vpr/src/route/rr_node.cpp
Previous code would allow for integer overflow, resulting in negative indices or alias other cost indicies.
> Check that cost_index fits within storage.

- doc/src/vpr/command_line_usage.rst
This PR adds an additional comment on how to enable the parallel workers.
If `libtbb-dev` is not installed in the system, parallel workers are not enabled. Therefore, a more explicit comment on the docs helps in getting the end-user to set-up the system for parallel workers builds.
> docs: add note to usage of parallel workers

- libs/libarchfpga/src/physical_types.h
- libs/libarchfpga/src/read_xml_arch_file.cpp
This PR is a little enhancement to have the different pb_type classes enum easy accessible in an array structure. There is also an index addressable array to get the name of the class as a `const char *`. 
Better access capability to the `e_pb_type_class` enum.
> vpr: Adding pb_type to match other enum values.

- doc/src/utils/fasm.rst
- utils/fasm/src/fasm.cpp
- utils/fasm/test/test_fasm.cpp
- utils/fasm/test/test_fasm_arch.xml
Previously only one FASM feature could be specified per mux selection.  In some cases, it is convenient to specify multiple features.  This PR enables multiple features to be specified, while being backwards compatible with the previous syntax.
The case that motives this change is using features in "passthrough".  There are couple examples of this in the 7-series arch.  The first is the "BUFHCE" pass-through.    This requires two features:
```
BUFHCE_X0Y0.IN_USE
BUFHCE_X0Y0.ZINV_CE
```
So if the BUFHCE is in passthrough, both features must be set.  No additional routing is required in this case because by default the pin CE == 1, and by default the inverted on the CE IPIN is enabled, e.g. held in reset.  These two features enable the use of a particular BUFHCE (e.g. connecting the input …
> Add support for multiple FASM features for a single mux selection.

- vpr/src/place/place.cpp
It is unclear why the assertion exists, it seems that not all ``cx_to`` will have items that conform to the ``min_cy``/``max_cy`` for spare architectures.
> Skip x locations that have no targets.

- vpr/src/place/timing_place_lookup.cpp
Currently delta matrix may have IMPOSSIBLE_DELTA elements after sampling.  If the placer requires a delay using these elements, it will corrupt the slack computation, resulting in an exception or assertion failure.
https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/563
This PR generalizes the nearest neighbor algorithm to have a flexible distance parameter, and then adds a pass to the placer delay matrix computation where IMPOSSIBLE_DELTA are filled using a nearest neighbor average (up to 5 Manhattan distance).
Some integration testing with Symbiflow has been done, but nothing substantial.
> Fill in IMPOSSIBLE_DELTA elements of delay matrix.

- ODIN_II/SRC/netlist_create_from_ast.cpp
Fixed memory leak in create_hard_block funtion in netlist_create_from_ast.cpp where the children of in_list were being freed, but in_list itself was not.
> ODIN_II Fixed memory leak in create_hard_block function in netlist_create_from_ast.cpp

- ODIN_II/SRC/include/config_t.h
- ODIN_II/SRC/include/odin_buffer.hpp
- ODIN_II/SRC/include/verilog_preprocessor.h
- ODIN_II/SRC/odin_ii.cpp
- ODIN_II/SRC/parse_making_ast.cpp
- ODIN_II/SRC/read_xml_config_file.cpp
- ODIN_II/SRC/simulate_blif.cpp
- ODIN_II/SRC/verilog_bison.y
- ODIN_II/SRC/verilog_flex.l
- ODIN_II/SRC/verilog_preprocessor.cpp
This fixes issue #64 via the removal of the freopen on tempfiles and also use a single pass preprocessor.
getline, trim and whitespace removal in one function to be used by the preprocessor
closes issue #64 
fix issue of freopen on tmpfile
full regression suite, basic and strong
> Single pass verilog preprocessor and Remove freopen

- libs/librtlnumber/src/include/internal_bits.hpp
Fix compile warning about unused globals in the RTL int library
rtl regression test
> remove warnings about unused variable in rtl_number library

- libs/libvtrutil/src/vtr_log.cpp
- libs/libvtrutil/src/vtr_log.h
- vpr/src/base/read_options.cpp
- vpr/src/base/read_options.h
- vpr/src/base/vpr_api.cpp
- vpr/src/place/place.cpp
- vpr/src/route/check_route.cpp
- vpr/src/route/check_rr_graph.cpp
- vpr/src/util/vpr_error.cpp
- vpr/src/util/vpr_error.h
- vpr/src/util/vpr_utils.cpp
- vpr/src/util/vpr_utils.h
This PR adds the functionality to do the following:
- Disable errors by demoting them to warnings;
- Suppress noisy warnings and redirect them to a custom file.
To enable this feature there are two new command line options:
- Warning suppression:
```
--suppress_warnings <output_filename>,<func1>:<func2>:<func3>
```
If the `<output_filename>` is not provided the warnings will be output on stdout as usual.
- Error disabling:
```
--disable_errors <func1>:<func2>:<func3>
```
`<funcN>` is the name of the function for which the warning/error will be suppressed/disabled, therefore, if a function name is specified in the list, all its warnings/errors are going to be disabled.
There are two different reasons why this PR is needed:
1. There …
> vpr: added optional disable errors and suppress warnings

- ODIN_II/SRC/ast_util.cpp
Fixed memory leak in get_name_of_pins function in ast_util.cpp where sym_node was not being freed
> Fixed memory leak in get_name_of_pins function in ast_util.cpp

- ODIN_II/SRC/verilog_preprocessor.cpp
Fixed problem with the file path not being properly copied with recursive includes.
>  Fixed preprocessor filepath

- ODIN_II/SRC/netlist_create_from_ast.cpp
- ODIN_II/SRC/parse_making_ast.cpp
Fixed a bug that caused the AST tree to be built incorrectly when declaring inputs and outputs outside of the port list.
> ODIN II: I/O port bug fix

- libs/libvtrutil/src/vtr_log.cpp
- libs/libvtrutil/src/vtr_log.h
- vpr/src/base/read_options.cpp
- vpr/src/base/vpr_api.cpp
This PR is to make optional the noisy warning output file optional (given that it could slow down run-time if VPR is launched on a HDD-provided machine). This is a PR related to the already merged https://github.com/verilog-to-routing/vtr-verilog-to-routing/pull/672 
Outputting the suppressed warning on dedicated file could slow down run-time for machine mounting HDDs instead of SSDs.
> vpr: optional noisy log warning file

- ODIN_II/SRC/ast_util.cpp
- ODIN_II/SRC/netlist_create_from_ast.cpp
Cleaned up memory leaks in ast_util.cpp and netlist_create_from_ast.cpp caused by calls to resolve_node.
> Cleaned up leaks caused by resolve_node

- vtr_flow/scripts/qor_compare.py
This PR solves an issue in the `qor_compare.py` script, for which, if there is a `parse_result` file which name starts with '0', the references in the `ratios` stylesheet are not computed correctly (as the starting 0 gets chopped-off, at least using LibreOffice when opening the `xlsx`).
Another thing is that now, if the input `parse_result` files are located in a different folder, the style sheet names will not contain the whole path, but only the filenames. 
It also solves an issue related to the TYPE_NUMERIC macro which is not found, hence ending in a fatal error.
https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/652
There is a need of manually changing the script (for the TYPE_NUMERIC issue) or be aware of the …
> vtr_flow: fixed qor_compare issue

- ODIN_II/SRC/netlist_create_from_ast.cpp
Fixed leak caused by alias_name being unnecessarily duplicated using vtr::strdup and then not being freed.
> Fixed leak from alias_name

- vpr/src/place/place.cpp
- vpr/src/route/check_route.cpp
- vpr/src/route/check_rr_graph.cpp
- vpr/src/util/vpr_error.cpp
- vpr/src/util/vpr_error.h
This PR follows changes in https://github.com/verilog-to-routing/vtr-verilog-to-routing/commit/93640d35613d989faea6c015c548be12bf76ce93.
It changes some VPR_THROWs to VPR_ERRORs to make them non-fatal and allow their disabling from command line.
An additional change of this PR is related to the usage of `__PRETTY_FUNCTION__`.
It is utilized only when displaying the error (demoted to warning), not for discerning what ERRORs need to be treated as WARNs, as the pretty function adds additional information to the string which, once compared with the function names of the command line option, cannot produce a match (making it impossible to demote errors to warnings from cmd line).
With this change, if g++ version is previous 99, __func__ …
> vpr: changed some VPR_THROW to VPR_ERROR

- ODIN_II/SRC/parse_making_ast.cpp
Fixed a bug that didn't allow 2D arrays to get through parsing.
> ODIN II: fix 2D array bug

- ODIN_II/SRC/netlist_create_from_ast.cpp
Fix odin leak from create_param_table_for_module function where the temp_localparam_list was being allocated but not freed.
> Odin leak temp localparam list

- ODIN_II/SRC/netlist_create_from_ast.cpp
Fixed leak in create_param_table_for module function where temp_string was not being assigned to anything before having the pointer reassigned, so it should be freed.
> ODIN_II leak fix

- ODIN_II/SRC/adders.cpp
Fixed leak in adders.cpp caused by new_name not being freed before being reassigned
Issue #622
Fixes leak when ODIN is run with the following file:
vtr_flow/arch/timing/k6_frac_N10_frac_chain_mem32K_40nm.xml
sha.v
> Fixed leak caused by new_name

- ODIN_II/SRC/adders.cpp
- ODIN_II/SRC/subtractions.cpp
Fixed leak in subtractions.cpp caused by new_name not being freed before being reassigned
Issue #622
Fixes leak when ODIN is run with the following file:
vtr_flow/arch/timing/k6_frac_N10_frac_chain_mem32K_40nm.xml
sha.v
> Odin leak sub new name

- ODIN_II/SRC/memories.cpp
- ODIN_II/SRC/netlist_create_from_ast.cpp
Fixed memory leak from pin->mapping being set to NULL before being freed.
> Odin leak pin->mapping

- ODIN_II/SRC/adders.cpp
- ODIN_II/SRC/subtractions.cpp
Fixed memory leak in subtractions.cpp where not_node[i] was allocated and then reassigned without being freed.
Issue #622
Fixes leak when ODIN is run with the following file:
vtr_flow/arch/timing/k6_frac_N10_frac_chain_mem32K_40nm.xml
#####Verilog
sha.v
> Odin leak in subtractions.cpp not_node[i]

- ODIN_II/SRC/netlist_create_from_ast.cpp
Fixes leak from temp_string being allocated and not being freed before either being reassigned or going out of scope.
> ODIN_II leak fix temp_string

- ODIN_II/SRC/netlist_create_from_ast.cpp
Fixes leak from temp_string being allocated and going out of scope before being freed.
> ODIN_II leak Fix get_chunk_size_node

- ODIN_II/SRC/odin_error.cpp
Fixes Coverity issue CID200634. Ensures that a possible NULL pointer will not be de-referenced.
> ODIN_II: Fix coverity issue CID 200634

- ODIN_II/SRC/ast_util.cpp
Should resolve coverity issue CID 200780. 
node->types.concat.bit_strings was being freed inside a for loop rather than freeing it's contents.
Would also probably fix some memory leaks
> ODIN_II: Fix coverity issue CID 200780 - Double free

- ODIN_II/SRC/netlist_create_from_ast.cpp
Should resolve coverity issue CID 200678. Because data is either assigned right_outputs or in_1, and both of those are initialized to NULL, we should check that data is not NULL before de-referencing.
> ODIN_II: Fix coverity issue CID 200678

- ODIN_II/SRC/output_blif.cpp
Should resolve coverity issue CID 200815; de-referencing a possible NULL pointer
> ODIN_II: Fix coverity issue CID 200815

- ODIN_II/SRC/adders.cpp
Should resolve coverity issue CID 200827. Typo; string comparison done on component_s[1] against itself, should've been compared against component_o[1]
> ODIN_II: Fix coverity issue CID 200827

- ODIN_II/SRC/ast_util.cpp
Should resolve coverity issue CID 200833, CID 20053, & CID 201095. Should check that bit is not negative before using it to index into array
> ODIN_II: Fix coverity issue CID 200833, CID 201053, & CID 201095

- ODIN_II/SRC/parse_making_ast.cpp
Should resolve coverity issue CID 200914; NULL pointer de-reference. Moved NULL check to be its own if statement and put both other branches inside. If symbol_list is NULL, the fucntion will return NULL.
> ODIN_II: Fix coverity issue CID 200914

- ODIN_II/SRC/netlist_create_from_ast.cpp
Should resolve coverity issue CID 200944. De-reference before NULL check.
> ODIN_II: Fix coverity issue CID 200944

- ODIN_II/SRC/netlist_create_from_ast.cpp
Should resolve coverity issue CID 200970. de-reference bfore NULL check
> ODIN_II: Fix coverity issue CID 200970

- ODIN_II/SRC/ast_util.cpp
Should resolve coverity issue 200973. Type mis-match. Cannot pass enum to print statement. Added a function to convert enum to string to be able to print. This is the only place in the code where this is an issue, so we could also just remove the print statement if it's not completely necessary to include it. 
> ODIN_II: Fix coverity issue CID 200973

- ODIN_II/SRC/netlist_create_from_ast.cpp
Should resolve coverity issue CID 201059. NULL de-reference
> ODIN_II: Fix coverity issue CID 201059

- ODIN_II/SRC/memories.cpp
Should resolve coverity issue CID 201233. Need to print the name of the pin; cannot print type nnpin_t
> ODIN_II: Fix coverity issue CID 201233

- ODIN_II/SRC/netlist_create_from_ast.cpp
Should resolve coverity issue 201170. Check that right_inputs is not NULL before de-referencing
> ODIN_II: Fix coverity issue 201170

- ODIN_II/SRC/adders.cpp
Fixes leak caused by new_name not being freed before the pointer being reassigned
> ODIN_II: Fix leak caused by new_name

- ODIN_II/SRC/adders.cpp
Fixes seg faults occurring in adders.cpp when using the chain
nightly regression run was failing because of this seg faults
> ODIN II: fix segfault from hard adders

- ODIN_II/SRC/output_blif.cpp
Should resolve Coverity issue 200741 & 200719. Flag is initialized to 0 and never set to 1, but there is an if statement to check for flag ==1. Removed dead code.
> ODIN_II: Fix coverity issues CID 200741, 200719

- ODIN_II/SRC/simulate_blif.cpp
Should resolve coverity issue CID 200858. covered can never be false, therefore the code would never take the false branch
> ODIN_II: Fix coverity issue CID 200858

- ODIN_II/SRC/read_blif.cpp
Should resolve coverity issue CID 201850. Check for ptr should be done before strcmp otherwise, NULL pointer could be de-referenced
> ODIN_II: Fix coverity issue CID 201850

- ODIN_II/SRC/simulate_blif.cpp
Should resolve coverity issue CID 201694. Check the length of node->name before appending to buffer
> ODIN_II: Fix coverity issue CID 201694

- ODIN_II/SRC/read_blif.cpp
Should resolve coverity issue CID 201341. NULL de-reference
> ODIN_II: Fix coverity issue CID 201341

- ODIN_II/SRC/simulate_blif.cpp
Should resolve coverity issue CID 201703. Ensures that the return value of get_clock_ratio is not zero before doing the modulo.
Odin pre-commit.
> ODIN_II: Fix coverity issue CID 201703

- ODIN_II/SRC/ast_elaborate.cpp
- ODIN_II/SRC/ast_loop_unroll.cpp
- ODIN_II/SRC/ast_util.cpp
- ODIN_II/SRC/include/ast_elaborate.h
- ODIN_II/SRC/include/ast_loop_unroll.h
- ODIN_II/SRC/include/ast_util.h
- ODIN_II/SRC/netlist_create_from_ast.cpp
- ODIN_II/SRC/parse_making_ast.cpp
Moved all resolutions from the resolve_node() function to a new elaboration phase during the AST simplification phase. This reduces convolution during netlist creation and will allow new features to be implemented more easily.
> ODIN II: initial AST elaboration refactoring

- vpr/src/draw/draw.cpp
- vpr/src/route/route_timing.cpp
- vpr/src/route/route_tree_timing.cpp
- vpr/src/timing/net_delay.cpp
The modules route_tree_timing.cpp performs a task similar to net_delay.cpp. The former conducts incremental timing analysis while the latter completes timing analysis in a single step. It is unsurprising, then, that the two files both heavily rely on a similar tree data structure. In fact, the information included in the node of the net_delay's resistance-capacitance tree is a subset of a node in the route_tree_timing's route tree. Therefore, in this pull request, we have net_delay utilize the route tree data structure and make calls with the appropriate functions.
This change is required to remove redundancies, in alliance with the principles of clean coding.
1. Passed titan on commit id: 68317ee0637f4535e92328eb51e673e5ef20b8a3 (Planning to rerun on more recent commit id)
2. See …
> Refactored net_delay and route_tree_timing code

- libs/EXTERNAL/libpugixml/CMakeLists.txt
pugixml throws errors in compact mode when sanitize flags are on, 
this PR disables compact mode when sanitize flag are set
fixes #813 
Clean sanitize errors
built using PR  #815 to verify build is successful
no errors are thrown
> VTR_BUILD: disable pugixml compact mode with sanitize flags on

- vpr/src/base/read_options.cpp
- vpr/src/base/read_options.h
- vpr/src/base/vpr_api.cpp
- vpr/src/timing/timing_graph_builder.cpp
- vpr/src/timing/timing_graph_builder.h
In the [SymbiFlow](https://github.com/SymbiFlow/symbiflow-arch-defs) architectures, some of the tiles do not have combination sinks. This fix is needed to allow the architecture to have no combination sinks for specific tiles. Without this addition, the Timing graph builder would produce a `tatum` error and the failure of the VPR flow.
It may be better to have this fix under a command line option (e.g. --allow_non_combination_sinks). 
Avoid Tatum error while building the Timing Graph within VPR.
> timing_builder: allow dangling combinational nodes

- libs/libvtrutil/src/vtr_ndmatrix.h
Flat accessors are useful for serialization (see #707).
> Add flat accessors to NdMatrix.

- vtr_flow/scripts/run_vtr_flow.pl
disable valgrind when running perl scripts to catch valgrind leaks only on internal components
https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/622#issuecomment-513857413_
This should now give a clean valgrind error list, vtr_reg_valgrind_small should now report 0 errors
Allows to catch only important valgrind leaks
vtr_reg_valgrind_small
> VTR_FLOW: do not run valgrind on perl scripts for run_vtr_flow.pl

- libs/libvtrutil/src/vtr_flat_map.h
Also convert forwarding version of constructors to require r-value
reference (and avoid potential copy).
> Add  convenience constructors for flat_map2

- ODIN_II/SRC/simulate_blif.cpp
Related to PR #788. Coverity issue CID 201323. Type mis-match fix that was missed on the previous PR
> ODIN_II: Fix coverity issue CID 201323 -Update

- ODIN_II/SRC/soft_logic_def_parser.cpp
Should resolve coverity issue CID 201117. Need to store the pointer to the string that was duplicated so that it can later be freed.
> ODIN_II: Fix coverity issue CID 201117

- ODIN_II/SRC/read_blif.cpp
Should resolve coverity issue CID 134668; resource leak. Need to free input_names and it's contents before returning.
>  Odin_ii: Fix coverity issue CID 134668: Resource leak 

- ODIN_II/SRC/netlist_create_from_ast.cpp
- ODIN_II/regression_test/benchmark/large/spree.v
Fixed a bug that placed an unexpected node in the string cache when an implicit declaration was encountered.
nightly regression failed
> ODIN II: fix implicit declarations

- CMakeLists.txt
with the previous flags, vtr would not build with libasan.
the changes remove linking asan as a static library
this fixes #814
Ability to run with sanitize flags.
built with gcc 9
> VTR_BUILD: -lasan not found

- ODIN_II/SRC/memories.cpp
Should resolve coverity issue CID 201741. Type mis-match
(commit message has different CID, that was a typo)
> ODIN_II: Fix coverity issue CID 201741

- ODIN_II/SRC/parse_making_ast.cpp
Should resolve coverity issue CID 202041. NULL pointer de-reference
> ODIN_II: Fix coverity issue CID 202041

- ODIN_II/SRC/read_blif.cpp
Should resolve coverity issue CID 201815. Resource leak due to names not being freed. In the first if block, we can free the contents held by names because they are not assigned to anything, but if the program goes into the else block, the contents are assigned, so we should not free them, just the pointer. 
> ODIN_II: Fix coverity issue CID 201815

- ODIN_II/SRC/read_blif.cpp
Should resolve coverity issue CID 201611. Resource leak due to clock_name not being freed. Since the function search_clock_name will malloc a new string anyway, just assign to names[3] and don't use another variable or do strdup. No need to duplicate strings everywhere if they're not being used again
> ODIN_II: Fix coverity issue CID 201611

- ODIN_II/SRC/read_blif.cpp
Should resolve coverity issue CID 201751 & 200856. Resource leaks from output_bit_map and bit_map going out of scope before being freed. Had to rewrite function so that there was only one return point and the storage could be freed before the function returns.
> ODIN_II: Fix coverity issue CID 201751

- ODIN_II/SRC/ast_elaborate.cpp
- ODIN_II/SRC/ast_loop_unroll.cpp
- ODIN_II/SRC/ast_util.cpp
- ODIN_II/SRC/include/ast_util.h
- ODIN_II/SRC/include/odin_types.h
- ODIN_II/SRC/include/string_cache.h
- ODIN_II/SRC/netlist_create_from_ast.cpp
- ODIN_II/SRC/verilog_bison.y
- Expanded reduce_expressions to unpack 2D arrays and fold constant ternary operations
- Fixed replications of zero so that they are permitted in concatenations that contain other valid bitstrings, but not permitted anywhere else, per the Verilog 2005 standard
- Implicit fallthrough warning was solved via the reorganization of replication
- Bug from unrolled module instances in module_names_to_idx was resolved
closes 828
> ODIN II: handle 2D arrays, replication of zero, ternary op in AST elaboration

- ODIN_II/SRC/netlist_create_from_ast.cpp
Should resolve coverity issue CID 202042 & CID 200970. NULL pointer de-reference
> ODIN_II: Fix coverity issue CID 202042

- ODIN_II/SRC/soft_logic_def_parser.cpp
Should resolve coverity issue CID 202093. line_dup going out of scope before being freed.
> ODIN_II: Fix coverity issue CID 202093

- ODIN_II/SRC/netlist_check.cpp
Should resolve coverity issue CID 201853. Dereference after a NULL check
> ODIN_II: Fix coverity issue CID 201853

- utils/CMakeLists.txt
- utils/route_diag/CMakeLists.txt
- utils/route_diag/src/main.cpp
- vpr/src/base/SetupVPR.cpp
- vpr/src/base/SetupVPR.h
- vpr/src/base/read_options.cpp
- vpr/src/base/read_options.h
- vpr/src/base/vpr_api.cpp
- vpr/src/base/vpr_api.h
- vpr/src/place/timing_place_lookup.cpp
- vpr/src/place/timing_place_lookup.h
- vpr/src/route/route_timing.cpp
- vpr/src/route/route_timing.h
- vpr/src/route/route_tree_timing.cpp
- vpr/src/route/route_tree_timing.h
- vpr/src/route/router_delay_profiling.cpp
route_diag is intended to be used to probe router behavior and explore
interconnection delay behavior.
Used for exploring #592
The quality and behavior of the router lookahead and placer delay matrix are important to QoR, but current diagnostic flows are tied within an existing flow (e.g. place or route a circuit).  This tool allows running relevant flows without tying it to a circuit.
This can be used to diagnose router and placer inputs independent of flows.  The delay profile can be used to compare A* factors on a given graph, and compare delay grids for different rrgraphs on the same architecture grid.
An additional desired feature is to provide diagnostics on the A* heurstic, e.g. compare predicted forward cost vs true forward cost.
Changes to main VPR should be limited to moving …
> Initial router diagnostic tool

- ODIN_II/SRC/ast_util.cpp
This commit removes a compile warning related to
ast_util.cpp's fold_conditional() in ODIN_II.
Changed code to fix compile warnings coming from the fold_conditional() function. The warnings happen because the wrong type of enum is being used in a certain spot.
This change removes one ODIN_II compile warning.
The pre-commit test was run.
> Fix fold_conditional() ODIN_II compile warning

- ODIN_II/SRC/netlist_create_from_ast.cpp
Fixes leak from creating copies of pins unnecessarily. Rather than copying, just assign the pin. 
> ODIN_II: Leak fix: Do not copy pin, just assign

- ODIN_II/SRC/ast_util.cpp
This commit removes several compile warnings related to
ast_util.cpp's get_name_of_pin_at_bit() in ODIN_II.
Changed code to fix compile warnings coming from the get_name_of_pin_at_bit() function. The warnings are about an uninitialized variable being used.
This change simply removes some ODIN_II compile warnings.
The pre-commit test was run.
> Fix get_name_of_pin_at_bit() ODIN_II compile warnings

- ODIN_II/SRC/netlist_create_from_ast.cpp
Fixes memory leaks caused by never freeing the ast nodes held by the local_param_table_sc
> ODIN_II: Leak fix: free contents of local_param_table_sc

- ODIN_II/SRC/adders.cpp
Fixes leaks when running raygentop.v with k6_frac_N10_frac_chain_mem32k_40nm.xml, caused by not freeing the net name, or any unused pins before deleting the pointers
#622 
> ODIN_II: Fixes leak caused by free_op_node

- ODIN_II/regression_test/.library/conf_generate.sh
- ODIN_II/regression_test/.library/helper.sh
- ODIN_II/verify_odin.sh
travis will not run reg test due to missing realpath command.
rolled my own realpath -from_directory in the odin script library
N/A
fix regression test on travis
pre_commit
> Odin_II: remove dependency to GNU coreutils realpath

- ODIN_II/SRC/include/netlist_utils.h
- ODIN_II/SRC/netlist_utils.cpp
- ODIN_II/SRC/output_blif.cpp
- ODIN_II/SRC/partial_map.cpp
Fixes valgrind leak caused by not being able to free the nodes and pins in the function instantiate_arithmetic_shift_right. There should not be any leaks found when running the asr benchmarks in the operators suite with the k6_frac_N10_frac_chain_mem32k_40nm.xml architecture file. 
> ODIN_II: Fixes leak in instantiate_arithmetic_shift_right

- ODIN_II/SRC/ast_util.cpp
- ODIN_II/regression_test/benchmark/task/valgrind_operators/task.conf
Fix leak caused by expand_power and re-enable all verilog test files in valgrind_operators, as they should not be causing any leaks after this PR, PR #872, and PR #865 are all merged. The valgrind_operators will fail without all of these being merged, so the other two should be merged first.
> ODIN_II: Leak fix caused by expand_power

- ODIN_II/SRC/adders.cpp
- ODIN_II/SRC/multipliers.cpp
the leak is introduced from IPO flag by making some global variable appear as unreachable by the program exit.
valgrind operator failing on master
fix regression test
pre_commit
> Odin_II: fix leak appearing when IPO is enabled

- ODIN_II/SRC/netlist_visualizer.cpp
Should resolve coverity issue CID 200771. Resource leak. Very similiar to PR #811. Need to free stack_of_nodes and it's contents before returning.
> ODIN_II: Fix coverity issue CID 200771: Resource leak

- ODIN_II/SRC/netlist_visualizer.cpp
Should resolve coverity issue CID 200770. Resource leak. Need to free stack_of_nodes and it's contents. This was also labeled in the code as a TODO. Ran regression suite with no failures.
> ODIN_II: Fix coverity issue CID 200770: Resource leak

- vpr/src/draw/draw.cpp
In the function trace_routed_connection_rr_nodes, I added the route tree to the free list, where it could be correctly freed by the subsequent function call free_route_tree_timing_structs().
#845 
For this issue, I was unable to replicate the memory leak mentioned above with the latest build of libezgl or the suggested commit of a990b18. 
I built VTR with sanitizers on, and from the vpr folder ran the command:
valgrind --leak-check=full --show-leak-kinds=all --errors-for-leak-kinds=none --error-exitcode=1 --track-origins=yes ./cmd.sh
where ./cmd.sh was: 
./vpr ~/vtr_baseline/vtr_flow/arch/timing/k6_frac_N10_frac_chain_mem32K_htree0_40nm.xml ~/vtr_baseline/vtr_flow/benchmarks/blif/alu4.blif.
I ran the following command with graphics, and tried different permutations of clicking …
> vpr: fix memory leak caused by route tree that was not freed.

- vpr/src/route/route_tree_timing.cpp
added an assertion to avoid potential null pointer dereference warning.
#871 
"To keep VTR warning clean during builds (at least with gcc), so that any new warning actually gets looked into."
Passed basic and strong regression tests.
> vpr: added check for null pointer dereference in route_tree_timing.cpp

- ODIN_II/SRC/netlist_utils.cpp
This commit removes a compile warning related to
netlist_utils.cpp's depth_traverse_count() in ODIN_II.
This commit changes the parameters to the depth_traverse_count() function to accept a `short` instead of an `int`. This was done because the parameter was later being assigned to a value in `node`, which is of type short int.
This removes a warning that comes up during ODIN_II compilation.
The pre-commit test was run.
> Fix depth_traverse_count() ODIN_II compile warning

- ODIN_II/SRC/netlist_visualizer.cpp
This commit removes a compile warning related to
netlist_visualizer.cpp's depth_first_traverse_visualize()
in ODIN_II.
This commit changes the parameters to the depth_first_traverse_visualize() function to accept a `short` instead of an `int`. This was done because the parameter was later being assigned to a value in `node`, which is of type short int. The value passed in when this function is called is also a short int.
This change removes an ODIN_II compile error.
The pre-commit test was run.
> Fix depth_first_traverse_visualize() ODIN_II compile warning

- vpr/src/route/route_timing.cpp
Added a condition checking both the total_cost and backwards_cost in reaching the node must be less than any previously recorded value of total_cost and backwards_cost, before adding the node to the heap. This action is also referred to as "prepruning".
This change is required as an improvement to VPR's runtime.
Here are the results of Titan23 benchmarks being run on the StratixIV Titan architecture.
These results are a comparison of the code with the check added vs. master branch.
Both codebases ran only the routing stage, and used the same net and place files to isolate only the effect of the router.
https://docs.google.com/spreadsheets/d/1f8zz_17xW7yyd9VYHUvNfsq8xoqpjj1B1918oFWb83Q/edit?usp=sharing
> vpr: check the costs of node to be expanded before adding to the heap

- vpr/src/route/rr_graph_indexed_data.cpp
Freed the pointer switch_Cinternal_total in load_rr_indexed_data_T_values.
#889 
"Memory leaks should be avoided."
Running vtr_reg_valgrind_small after my change no longer reported the memory leak from load_rr_indexed_data_T_values function.
> vpr: fixed memory leak in load_rr_indexed_data_T_values

- ODIN_II/SRC/adders.cpp
- ODIN_II/SRC/ast_elaborate.cpp
- ODIN_II/SRC/include/adders.h
- ODIN_II/SRC/include/memories.h
- ODIN_II/SRC/include/multipliers.h
- ODIN_II/SRC/include/parse_making_ast.h
- ODIN_II/SRC/memories.cpp
- ODIN_II/SRC/multipliers.cpp
- ODIN_II/SRC/netlist_create_from_ast.cpp
- ODIN_II/SRC/parse_making_ast.cpp
- ODIN_II/regression_test/benchmark/task/rs_decoder/task.conf
Fixed a bug with module/hard block name collisions. Odin will now convert module instantiations to hard blocks or soft logic where appropriate (i.e., when port connections match), regardless of whether a custom module was written. 
Odin pre-commit regression suite
> ODIN II: fix hard block instantiation bug

- ODIN_II/Makefile
This PR fixes the Makefile for Odin to allow parallel builds (e.g. `make -j$(nproc)`)
There were two issues with the way the targets are defined.
1. The `.%.build` target cannot depend on both `clean` and `_init`. It works
fine with a single-core build, but when executing it in parallel, the
`clean` target breaks the `_init` target. To make it work in parallel the
`_init` target now directly depends on the `clean` target.
2. The `_set_<xxx>` targets have to be executed before the `_build_it`
target - they cannot be executed at the same time. This has been
reworked to use a dynamically defined targets to avoid creating an extra
wrapper target for each of them.
To be able to build Odin using multiple cores.
Both mutli and single job builds work for Odin.
> odin: makefile: fix parallel build

- vpr/src/pack/pack.cpp
Pretty straight-forward, just adding missing header.
> Fix include: pack.cc uses std::stringstream; include <sstream>

- ODIN_II/SRC/enum_str.cpp
- ODIN_II/SRC/include/odin_types.h
- ODIN_II/SRC/include/odin_util.h
- ODIN_II/SRC/odin_util.cpp
- ODIN_II/SRC/parse_making_ast.cpp
- ODIN_II/SRC/verilog_preprocessor.cpp
Added support for .vh files, which can be included in .v files.
Need .vh file support for MOR1K
> ODIN II: add support for .vh files

- ODIN_II/SRC/include/odin_error.h
- ODIN_II/SRC/include/odin_types.h
- ODIN_II/SRC/odin_ii.cpp
- ODIN_II/SRC/odin_util.cpp
add soft errors to Odin via a flag
#903 
Allow users to pass unsupported files
pre_commit
> Odin: add soft errors

- ODIN_II/SRC/ast_elaborate.cpp
- ODIN_II/SRC/ast_util.cpp
- ODIN_II/SRC/include/odin_types.h
- ODIN_II/SRC/netlist_create_from_ast.cpp
- ODIN_II/SRC/parse_making_ast.cpp
When building the symbol table, the nodes are no longer copied over, but put directly in the symbol table and then removed completely from the AST, so that these nodes will no longer exist in multiple places. This prevents having to do multiple passes in the code to update the copies, and prevents nodes from being lost when updating both copies to be put in string caches.
This PR should take care of any remaining valgrind leaks from the full benchmarks.
> ODIN_II: Remove any var_declare nodes in the symbol table from the ast

- vpr/src/pack/cluster.cpp
The `unclustered_list_head` is an array holding heads of lists of unclustered molecules. The array is sorted by number of molecules inputs. Since the `unclustered_list_head_size` was calculated incorrectly, the molecules with the highest input count were not considered while searching for unrelated candidates for a cluster.
This is one of the issues causing #621
> cluster: fix unclustered_list_head_size

- vpr/src/route/route_tree_timing.cpp
Previous code could not handle searching along multiple linked nodes.
If sink rr node is on second linked edge, previous code would assert.
Invocation that failed before passes now.
> Do not assert mid-search for sink node.

- CMakeLists.txt
- Makefile
- ODIN_II/CMakeLists.txt
- vpr/CMakeLists.txt
This PR adds the optional `-Werror` flag during ODIN_II compilation to have a warning-free build in Travis CI.
This PR also contains two formatting fixes (trailing space and tab-to-spaces conversion).
Having a consistent warning-free build is necessary to prevent from having possible regressions in the future.
Locally, by inserting useless code producing warnings which have been correctly caught at compile time.
> ODIN_II: added -Werror when BUILD_TYPE is release_strict

- vpr/src/base/vpr_context.h
- vpr/src/route/rr_graph.cpp
- vpr/src/route/rr_graph_reader.cpp
- vpr/src/route/rr_graph_reader.h
When ``--read_rr_graph`` is used, every time ``create_rr_graph``is called it will reload the rrgraph.  The intention of ``create_rr_graph`` is to only reload the rrgraph if needed (e.g. [channel width check](https://github.com/verilog-to-routing/vtr-verilog-to-routing/blob/master/vpr/src/route/rr_graph.cpp#L330)), however this check doesn't work if the channel width is fixed by the rr graph being read.
This PR changes how ``create_rr_graph`` checks if ``load_rr_graph`` needs to be called.
#707 
Avoids reloading rrgraph when loading the rrgraph from a file.
> Fix rrgraph reload check when loading rrgraphs from disk.

- vpr/src/util/vpr_utils.cpp
Recent logical/physical tiles split introduced the regression. If there is no max_type found we should not call the logical_block_type function, but rather return the nullptr immediately  (like we did before the split).
> Fix segfault in find_most_common_block_type

- vpr/src/route/rr_graph_reader.cpp
Previous code assumed that rr nodes appeared in id order, rather than rely on the id field of the XML.
Some experimentation with rr graph reordering based on geometry re-assigns rr node ids based on various criteria.  This requires that the rr graph reader not assume that node ids are in order when being read.
CI is green and some manual functional testing.
> Remove assumption about rr node order when reading XML.

- vpr/src/place/place.cpp
Appears that pointer type in logging macro was missed during recent logical <-> physical cluster split.
> Correct pointer type in logging macro.

- vpr/src/route/rr_graph.cpp
Removed existing dead code in rr_graph.cpp.
Code originally checked for whether if is_global_graph was false, when this boolean was already known to be false, so I removed that condition.
#945 
Keeps coverity clean.
Investigated the blame for that particular section of code, and concluded that the condition had never been evaluated before.
> vpr: shortened check of max nodes per channel vs. max channel width

- vpr/src/route/rr_graph_indexed_data.cpp
The current cost indexing code will leave segment costs as "OPEN" (e.g. -1.f) if none of that segment is present.  This data may get used in the classic cost function here (https://github.com/verilog-to-routing/vtr-verilog-to-routing/blob/master/vpr/src/route/router_lookahead.cpp#L50), and as a result a negative lookahead cost may be generated.
The specific circumstances that can result in this is if a segment is only used in the X or Y direction, resulting in none of the opposite type being present.  In this case, it is probably better to use the ortho cost values rather than leave them as "OPEN" (e.g. -1.f).
Green CI, and some symbiflow integration tests.
> Always initialize cost indexed data on orthagonal segments (if possible).

- libs/librtlnumber/src/include/internal_bits.hpp
change get_value function to solve runtime error of long 64bits for Sanitizer
compile on make build odin
> get_value: solve the runtime 64bits_long error

- doc/src/vpr/basic_flow.rst
@kmurray added few tweaks to PR #983 (thanks for that!). 
There is one typo that caught my eye though, namely ``Placment`` instead of ``Placement``.
This small PR fixes it.
> doc: vpr: Fix typo

- utils/fasm/src/fasm.cpp
- utils/fasm/src/fasm.h
- utils/fasm/test/test_fasm.cpp
- utils/fasm/test/test_fasm_arch.xml
The previous code used the clb prefix of the current block, but the
`interconnect`/`fasm_mux` logic operates on the parent pb_type of the
current block, not the current block itself.  As a result, if the output
of a `fasm_mux` has a prefix, it was getting lumped into the FASM mux
declaration.
The intention of `fasm_prefix` was to apply to metadata at the current level and deeper.  This bug caused a `fasm_prefix` to leak one level higher than intended.
1. Integration tests on Symbiflow
2. New unit test
> Use FASM prefix of parent pb_type, not prefix of output pb_type.

- libs/libvtrutil/src/vtr_ndmatrix.h
Previous implementation recomputed dimension strides every usage.  When
using the map lookahead, this has a very significant affect, as the core
of the map lookahead is an NdMatrix.
Provides significant speedup when using lookaheads that leverage NdMatrix lookaheads (e.g. map).
Profiled before and after.
> Optimize NdMatrix.

- libs/libarchfpga/src/physical_types.h
- libs/libvtrutil/src/vtr_cache.h
- utils/route_diag/src/main.cpp
- vpr/src/base/SetupVPR.cpp
- vpr/src/base/place_and_route.cpp
- vpr/src/base/read_options.cpp
- vpr/src/base/read_options.h
- vpr/src/base/vpr_api.cpp
- vpr/src/base/vpr_context.h
- vpr/src/base/vpr_types.h
- vpr/src/place/place_delay_model.h
- vpr/src/place/timing_place_lookup.cpp
- vpr/src/route/route_common.cpp
- vpr/src/route/route_common.h
- vpr/src/route/route_timing.cpp
- vpr/src/route/route_timing.h
- vpr/src/route/router_delay_profiling.cpp
- vpr/src/route/router_delay_profiling.h
- vpr/src/route/router_lookahead.cpp
- vpr/src/route/router_lookahead.h
- vpr/src/route/rr_graph.cpp
- vpr/src/route/rr_graph.h
This PR restructures the router lookahead and placement delay objects to enable several goals:
- Properly encapsulate existing functionality behind virtual interfaces
- Provide command line arguments and virtual methods to read and write the router lookahead and placement delay objects
- Avoid reconstruction of the router lookahead object during placement delay lookup
Once this PR is merged, a followup PR will be submitted to implement the read/write methods with a proposed serialization format.
The router lookahead computation and placement delay matrix computations can take a fairly significant amount of time.  For example (take from one of the titan bench marks, ``stratixiv_arch.timing.xml/gsm_switch_stratixiv_arch_timing.blif``):
```
RR graph channel widths unchanged, skipping RR …
```
> Provide structure for Router lookahead and placement delay lookup SerDes

- vpr/src/route/route_timing.cpp
When debugging lookaheads, a common problem early on is simply the lookahead failing to find valid values (e.g. finite).  This adds a small debug log message if a non-finite lookahead is detected and router debugging is enabled.
This is simply a debugging aid.
Compiled and checked the output on a failure.
> Add debug logging if there is a non-finite value from the lookahead.

- vpr/src/base/SetupVPR.cpp
- vpr/src/base/read_options.cpp
- vpr/src/base/read_options.h
- vpr/src/base/vpr_types.h
- vpr/src/place/timing_place_lookup.cpp
This is useful if the placer delay sampling method tries to sample clock
network tiles (e.g. PLLs, global/local clock buffers) which will result
in a poor delay matrix which is unsuitable for LUTs/FFs/RAMs.
If the delay matrix sampling algorithm chooses a specialized tile (e.g. PLL, global/local clock buffers) it effectively builds the delay matrix for the specialized network, instead of the general routing fabric.  This option prevents this from being possible.
Need to finish testing with variant, but a simpler version of this PR was tested with Symbiflow.
Testing remaining to be done:
> Add tile filtering option for placer delay matrix sampling.

- ODIN_II/SRC/read_blif.cpp
> simulation mem leak - latch names array in create latch

- utils/fasm/src/fasm.cpp
Added a null-pointer test in the main loop of the `FasmWriterVisitor::walk_routing()` method, so an empty trace won't cause segment fault during FASM generation.
When calling the `genfasm` util with routing results containing global routes (for example a clock), an empty trace will appear in the `g_vpr_ctx.mutable_routing().trace` vector. The head of such trace is a null pointer, and the `FasmWriterVisitor::walk_routing()` method does not check this before walking the route tree converted from it, eventually causing a segment fault.
> Avoid global routing messing up FASM generation

- vpr/src/route/check_route.cpp
- vpr/src/route/route_common.cpp
- vpr/src/route/route_timing.cpp
- vpr/src/route/route_tree_timing.cpp
- vpr/src/route/route_tree_timing.h
- vpr/src/route/rr_graph.cpp
The previous pruning code left non-configurable sets unpruned.  The new code tracks outbound configurable edges from non-configurable sets, and prunes them when the count reaches zero.
Fixes #526
- #526
> Track non-configurable edge usage to enable pruning.

- CMakeLists.txt
- libs/CMakeLists.txt
- libs/EXTERNAL/CMakeLists.txt
- libs/libvtrcapnproto/CMakeLists.txt
- libs/libvtrcapnproto/README.md
- libs/libvtrcapnproto/matrix.capnp
- libs/libvtrcapnproto/mmap_file.cpp
- libs/libvtrcapnproto/mmap_file.h
- libs/libvtrcapnproto/ndmatrix_serdes.h
- libs/libvtrcapnproto/place_delay_model.capnp
- libs/libvtrcapnproto/serdes_utils.cpp
- libs/libvtrcapnproto/serdes_utils.h
- vpr/CMakeLists.txt
- vpr/src/place/place_delay_model.cpp
- vpr/src/place/place_delay_model.h
- vpr/src/place/timing_place_lookup.cpp
- vpr/test/test_place_delay_model_serdes.cpp
Bind ``--read_placement_delay_lookup`` and ``--write_placement_delay_lookup`` to SerDes (implemented using Cap’n Proto).
See justification in https://github.com/verilog-to-routing/vtr-verilog-to-routing/pull/707
This PR has predecessor PRs:
- #707 
- #708 
- #709 
Unit testing on SerDes, and some integration testing with Symbiflow.
> Initial place matrix serialization/deserialization support.

- vpr/src/base/place_and_route.cpp
- vpr/src/base/place_and_route.h
Coverity has reported a defect in the build.
** CID 202040:  Performance inefficiencies  (PASS_BY_VALUE)
/home/travis/build/verilog-to-routing/vtr-verilog-to-routing/vpr/src/base/place_and_route.cpp: 46 in binary_search_place_and_route(t_placer_opts, const t_annealing_sched &, const t_router_opts &, const t_analysis_opts &, const t_file_name_opts &, const t_arch *, bool, int, t_det_routing_arch *, std::vector<t_segment_inf, std::allocator<t_segment_inf>> &, vtr::vector<vtr::StrongId<cluster_net_id_tag, int, (int)-1>, float *> &, std::shared_ptr<SetupHoldTimingInfo>, std::shared_ptr<PostClusterDelayCalculator>)()
We do not need to pass the entire t_placer_opts into the function, its reference shall suffice.
> vpr: pass t_placer_opts in binary_search_place_and_route by reference

- vtr_flow/README.md
- vtr_flow/Readme.txt
* Convert the file to markdown.
* Actually link to the "running the vtr flow" docs.
See what this looks like at https://github.com/mithro/vtr-verilog-to-routing/tree/vtr-flow-readme-fix/vtr_flow or click the "Display Rich Diff" button (the paper looking one near the `<>` button).
> docs: Rework the readme file in the vtr_flow directory.

- vpr/src/timing/concrete_timing_info.h
Previous code was only clearing caching in one of 3 relevant places.
#1036 
Caching code introduced in https://github.com/verilog-to-routing/vtr-verilog-to-routing/commit/485697eacfdea46ebf4efdb727866e0b522e186f did not clear the cache in all paths, resulting in the router iteration display showing stale data.
> Clear cache of critical path and sTNS/sWNS.

- vpr/src/route/route_tree_timing.cpp
I believe when C_internal support was added, VPR was not tested at `-DVTR_ASSERT_LEVEL=3`, and as a result it was not noticed that `is_valid_route_tree` was failing.
Assertion violation on 7-series tests when running at `-DVTR_ASSERT_LEVEL=3`.
> Add missing C_internal to is_valid_route_tree.

- vpr/src/base/setup_clocks.cpp
Fixes an unchecked dynamic cast
Minor change: uses an if statement to check that a dynamic cast is returned
Unchecked dynamic cast #732
Fixes coverity warnings
N/A
Creates safer code
> Coverity Fix for unchecked dynamic cast in setup_clocks

- vtr_flow/parse/parse_config/common/vpr.common.txt
- vtr_flow/scripts/run_vtr_flow.pl
This provides metadata about where golden/parse results came from which can help
debugging/tracing/reproducibility issues.
> VTR flow: Add hostname and run directory to parse results

- vpr/src/base/netlist.tpp
- vpr/src/route/check_rr_graph.cpp
o The semicolon in the empty fallthrough statement in netlist.tpp
triggers fallthrough warnings, so removing the semicolon better
reflects the intentions.
o check_rr_graph: there is a missing break in the switch/case which
happens to not introduce a bug as the following cases also break.
Add 'break' to reflect intention of code.
> Remove empty statement in switch/case. Add missing break in another.

- vpr/src/route/route_common.cpp
- vpr/src/route/route_common.h
- vpr/src/route/route_timing.cpp
Removes redundant calls to re-sift the heap. add_route_tree_node_to_heap() inserts them in the correct position, so there should be no need to re-sift.
> vpr: Remove redundant calls to heap_::sift()

- libs/libvtrutil/src/vtr_geometry.h
- libs/libvtrutil/src/vtr_geometry.tpp
- libs/libvtrutil/test/test_geometry.cpp
- vpr/src/route/route_timing.cpp
Add some bounding box methods to vtr::Rect with unit tests.
Adds a couple of useful constructors, `empty()` and `bounding_box` and `expand_bounding_box` to compute bounding rectangles.
I added a bounding box class while working on the connection box based lookahead, and vtr::Rect had most of what I implemented in the new class, so this allows me to use vtr::Rect instead.
I've added unit tests.
> Add some bounding box methods to vtr::Rect with unit tests

- vpr/src/route/route_timing.cpp
- vpr/src/util/vpr_utils.cpp
This was causing 100 billion allocations to be generated.
Avoids 100 billion allocations during PnR.
> Remove copy of vtr::bimap in get_physical_pin

- libs/libvtrutil/src/vtr_flat_map.h
Previous implementation of the flat_map `operator []` did a `find` followed by an `insert`.  This effectively did a binary search twice (`find` calls `std::lower_bound`, and so does `insert`).  The correct optimal solution is to use `std::lower_bound`, and avoid the second lookup.
This makes using `operator []` faster by avoiding a second call to `std::lower_bound`.
> Refactor vtr::flat_map operator []

- CMakeLists.txt
- libs/CMakeLists.txt
Previously additional compilation flags (e.g. to enable sanitizers) were
also applied to external libraries causing for instance the capnproto
compiler to be build with sanitizers which could then cause the build to
fail.
We now only apply additional flags to internal libraries to avoid this.
> build: Don't apply additional flags to external libraries/tools

- libs/libvtrutil/src/vtr_ndmatrix.h
- vpr/src/base/vpr_types.h
- vpr/src/route/rr_graph.cpp
- vpr/src/route/rr_graph2.cpp
- vpr/src/route/rr_graph_reader.cpp
By converting the first 4 layers into array+NdMatrix, the memory
locality is improved and the number of pointer chases changes from 5 to
2ish.
There is almost never a time where 5 nested std::vector's are the right data structure.  Changing the middle 3 std::vector's to an `NdMatrix` isn't ideal, but it is better.  Given that root vector is fixed size, using std::array instead of std::vector saves one layer of indirection.
- CI is green
- Profiled change before and after
> Convert 5-level nested vectors to 3-level array/NdMatrix/vector.

- libs/libarchfpga/src/physical_types.h
- libs/libarchfpga/src/read_xml_arch_file.cpp
- libs/libvtrutil/src/vtr_flat_map.h
- libs/libvtrutil/src/vtr_string_interning.h
- libs/libvtrutil/src/vtr_string_view.h
- libs/libvtrutil/test/test_strings.cpp
- utils/fasm/src/fasm.cpp
- utils/fasm/src/fasm.h
- utils/fasm/src/main.cpp
- utils/fasm/test/test_fasm.cpp
- vpr/src/base/metadata_storage.h
- vpr/src/base/vpr_context.h
- vpr/src/route/rr_graph_reader.cpp
- vpr/src/route/rr_graph_writer.cpp
- vpr/src/route/rr_metadata.cpp
- vpr/src/route/rr_metadata.h
- vpr/test/test_vpr.cpp
String internment is basically the idea that if you know you have a small pool of strings relative to the number of total strings, you can save memory and maybe save CPU time by interning the strings.  Then the leafs of the code have intern ids rather than the full strings.
This PR adds a simple string internment using `std::unordered_map` for use when interning strings, and a `std::vector` for intern id to string lookup. This simple string internment does use 2x the memory for string storage, but is straight forward to implement and verify.
This PR also converts the metadata structures to use interned string ids instead of `std::string`.  This is not critical for metadata on objects in physical types, but is critical when there is metadata that is on a per edge or per node basis.  The …
> Support for string internment and use interned strings for metadata

- libs/libvtrcapnproto/CMakeLists.txt
- libs/libvtrcapnproto/map_lookahead.capnp
- libs/libvtrcapnproto/serdes_utils.h
- vpr/src/place/place_delay_model.cpp
- vpr/src/route/router_lookahead.cpp
- vpr/src/route/router_lookahead.h
- vpr/src/route/router_lookahead_map.cpp
- vpr/src/route/router_lookahead_map.h
- vpr/test/test_map_lookahead_serdes.cpp
Now that capnp and the place delay lookahead are merged, this PR adds serialization for the map lookahead.
#989
As part of working on memory and CPU optimization for Titan benchmarks, iteration speed is important.  As an example, running routing only on the `gsm_switch_stratixiv_arch_timing.blif` takes ~1000 seconds.   Around 400 seconds of that time is computing the lookahead map.  The ability to save lookahead map saves those 400 seconds, and means that any resulting profile will be focused samples from the router.
> Implement serialization of map lookahead.

- vtr_flow/scripts/qor_compare.py
It will now detect:
* '.txt' -> '\t' separator
* '.csv' -> ',' separator
> flow: Improve separator detection in qor_compare.py

- vpr/src/util/vpr_utils.cpp
When the logical and physical block types were seperated the storage
convention for ports was changed to be more explicit. This updates the
reverse look-up to be consistent with that format (for most
architectures the previous code was correct, but that was because most
architectures obey the same pin ordering conventions as before) which
should be more robust.
Also add some additional sanity checking to RR node debug print
routines.
> vpr: Update block pin index to name to match new storage convention

- vpr/src/base/SetupVPR.cpp
- vpr/src/base/netlist.h
- vpr/src/base/netlist.tpp
- vpr/src/base/read_options.cpp
- vpr/src/base/read_options.h
- vpr/src/base/vpr_types.h
- vpr/src/pack/cluster.cpp
- vpr/src/place/place.cpp
- vpr/src/timing/VprTimingGraphResolver.cpp
- vpr/src/timing/concrete_timing_info.h
- vpr/src/timing/timing_info.h
- vpr/src/timing/timing_util.cpp
- vpr/src/timing/timing_util.h
Adds support for dumping the timing graph in GraphViz's DOT format to aid debugging.
Also adds support for 'debug' timing reports which include additional debug-level information (like timing graph node ids) which is helpful for interpreting the DOT format.
> vpr: Add support for dumping timing graph in GraphViz dot format

- vpr/src/route/check_route.cpp
- vpr/src/route/route_common.cpp
- vpr/src/route/route_timing.cpp
- vpr/src/route/route_tree_timing.cpp
- vpr/src/route/rr_graph.cpp
- vpr/src/route/rr_graph2.cpp
- vpr/src/route/rr_graph2.h
`malloc()` and `free()` can be error-prone, so I'm working on replacing them with safer alternatives, but without adding overhead.
https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/506
See issue above.
I've run `vtr_reg_strong` tests.
> Replace some uses of malloc/free with std::unique_ptr

- vpr/src/draw/draw.cpp
- vpr/src/draw/draw_types.h
This ensures that non-interactive graphics work correctly with auto set to a high value (i.e. not pausing for user interaction). Previously this would cause VPR to crash.
This also refactors the graphics setup code in update_screen() to be simpler and clearer.
> vpr: Fix graphics with --auto 2

- vpr/src/base/read_route.cpp
- vpr/src/route/check_route.cpp
- vpr/src/route/route_common.cpp
Previous code would (and did) happily write to inode = -1 (OPEN).
Memory corruption is bad!
- CI is green
> Avoid memory overrun/underrun in reserve_locally_used_opins.

- libs/libarchfpga/src/read_xml_arch_file.cpp
Previously this would cause a std::logic_error to be thrown from
std::string.
This is a good example of something that would be caught using the uxsdcxx parser generator, rather than hand writing parsing.
Previous logic just reported:
```
terminate called after throwing an instance of 'std::logic_error'
what():  basic_string::_M_construct null not valid
```
> Detect missing name attribute on model port declaration.

- ODIN_II/regression_test/benchmark/third_party/.gitignore
- ODIN_II/regression_test/benchmark/third_party/SymbiFlow/build.sh
- ODIN_II/regression_test/benchmark/third_party/SymbiFlow/task.mk
- ODIN_II/verify_odin.sh
This add symbiflow as a third-party BM and add build step to odin regression if the third party bm are not found yet
Have the ability to run external BM without having to store them in the repository 
make -f ODIN_II/Makefile pre_merge
> Odin: add third party benchmark build step

- .github/travis/build.sh
- .github/travis/common.sh
- .travis.yml
- ace2/ace.c
- ace2/bdd.c
- libs/CMakeLists.txt
- run_reg_test.pl
- utils/fasm/src/fasm.cpp
- utils/fasm/src/fasm.h
- vpr/src/base/atom_netlist_utils.cpp
- vpr/src/base/check_netlist.cpp
- vpr/src/base/vpr_api.cpp
- vpr/src/main.cpp
- vpr/src/pack/output_clustering.cpp
- vpr/src/route/route_timing.cpp
- vpr/src/util/histogram.cpp
- vpr/src/util/vpr_utils.cpp
- vpr/src/util/vpr_utils.h
- vtr_flow/scripts/run_vtr_flow.pl
- vtr_flow/scripts/run_vtr_task.pl
These build set VTR_ENABLE_SANTIZE=on which compiles VTR with sanitizers
to check for invalid memory accesses, undefined behaviour etc.
For motivation see #1130
> infra: Add sanitized versions of basic and strong regression tests

- ODIN_II/SRC/netlist_create_from_ast.cpp
invalid indexing for dynamic array
N/A (implicit ports)
bug during implicit port initilaization
make -f ODIN_II/Makefile pre_merge
> odin: fix assignment to index 0 in array

- vpr/src/base/vpr_api.cpp
- vpr/src/place/place.cpp
- vpr/src/place/place.h
This should ensure lookahead construction time is not attributed to the
placer (since it is also re-used by the router).
> vpr: Prime router lookahead for placement

- vpr/src/route/rr_graph_uxsdcxx_serializer.h
https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/1161
https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/1079
This bug prevents testing different graph ordering algorithms, which could benefit VPR runtime.
It has been tested with random and specific orderings using https://github.com/HackerFoo/Gorder in symbiflow-arch-defs.
> Fix Serialization of ptcs

- libs/libvtrcapnproto/serdes_utils.h
- vpr/src/route/gen/rr_graph_uxsdcxx_capnp.h
Capnp's traversal limits are not helpful, so disable them.
The traversal limit is easy to violate once graphs get big!
> Remove traversal limits from capnp reading.

- vpr/src/timing/timing_util.cpp
in id_or_pin_name_to_tn()
Signed-off-by: Henner Zeller <h.zeller@acm.org>
> Fix missing <sstream> include for use of std::istringstream

- utils/route_diag/src/main.cpp
This enables the route_diag tool to route with criticality other than `1.0`.
> Have route_diag use criticality from --max_criticality argument.

- libs/libvtrutil/src/vtr_flat_map.h
- vpr/src/base/metadata_storage.h
- vpr/src/route/rr_graph_uxsdcxx_serializer.h
- vpr/src/route/rr_metadata.cpp
- vpr/src/route/rr_metadata.h
- Intern metadata strings earlier to avoid allocations.
- Avoid second sort when building metadata map.
> Some improvements to metadata storage.

- libs/libarchfpga/src/arch_util.cpp
- libs/libarchfpga/src/arch_util.h
- libs/libarchfpga/src/physical_types.h
- libs/libarchfpga/src/read_xml_arch_file.cpp
- vpr/src/base/SetupVPR.cpp
- vpr/src/base/vpr_context.h
- vpr/src/util/vpr_utils.cpp
- vpr/src/util/vpr_utils.h
`std::set` is a fairly heavy-weight data structure, and consumes more
memory and is slower than a boolean.
Using a `std::set` is both slower and more memory intensive than simply using two booleans.  The new code no longer accommodates iterating over input or output tiles, but that was never done in the old code.
- CI is green
- Profiled before and after
> Use 2 boolean's per physical types instead of std::set to mark IO types.

- utils/fasm/src/main.cpp
- utils/fasm/test/test_fasm.cpp
- vpr/src/base/SetupVPR.cpp
- vpr/src/base/place_and_route.cpp
- vpr/src/base/read_options.cpp
- vpr/src/base/read_options.h
- vpr/src/base/vpr_api.cpp
- vpr/src/base/vpr_types.h
- vpr/src/route/route_common.cpp
- vpr/src/route/router_delay_profiling.cpp
- vpr/src/route/rr_graph.cpp
- vpr/src/route/rr_graph.h
- vpr/test/test_vpr.cpp
This PR adds two options that enable faster reading of RR graphs from disk.
Option 1 enables the ability to disable calling `check_rr_graph`.  This is takes ~12 seconds on the A50T graph, and if the entire flow is otherwise taking ~60 seconds, this is a significant fraction of runtime.  The idea here is that when the RR graph was first created, `check_rr_graph` can be called, and then once the graph is written to disk, future instance of VPR do not need to call it again.
Option 2 is a two part change.  By default VPR doesn't use edge metadata, so by default the RR graph reader will no longer read edge metadata.  However there are reasons to read the edge metadata (e.g. format conversion, profiling, etc), so an option is being added to re-enable reading of edge metadata from disk.  The …
> Options to enable faster rr graph reading

- .travis.yml
Travis CI has been failing for mysterious reasons, and it is unclear why.  This PR removes the caching statement from `.travis.yml` to see if it helps with the failures.
> Remove caching arg.

- libs/libvtrutil/src/vtr_string_view.h
- strncpy cannot handle nullptr (e.g. empty strings), so special case comparisons with empty strings to avoid calling into strncpy
- Fixed incorrect `empty` method
This was discovered by running with sanitizers.
> Fix couple small bugs in vtr_string_view.h

- vpr/src/route/connection_router.cpp
This is a small cleanup removing a use of `g_vpr_ctx` from `ConnectionRouter`.
**All** use of global data should be mediated through the `ConnectionRouter` construct, or arguments to it's methods.
> Use grid_ reference in ConnectionRouter.

- libs/libvtrutil/src/vtr_dynamic_bitset.h
- vpr/src/base/vpr_context.h
- vpr/src/base/vpr_types.h
- vpr/src/route/route_breadth_first.cpp
- vpr/src/route/route_timing.cpp
I'm converting the `vtr:vector<ClusterNetId, t_net_routing_status>` to just an `t_net_routing_status` object.  The backing store is now a bitset instead of vector to lower the memory requirement for `t_net_routing_status` and put clearer boundries on when `t_net_routing_status` is updated.
Follow up PR will more `t_net_routing_status` and other mutable state out of raw RoutingContext into a set of dedicated objects for tracking router state per #1018 
#1018
> Add dynamic_bitset and convert net status to use dynamic bitset.

- libs/libvtrutil/src/vtr_strong_id_range.h
- libs/libvtrutil/test/test_strong_id.cpp
- vpr/src/route/connection_router.cpp
- vpr/src/route/rr_graph_storage.h
vtr::StrongIdRange and vtr::StrongIdIterator are useful utility classes
for ranges of vtr::StrongId's (e.g. edges belonging to a node).
> Add vtr::StrongIdRange and use it within ConnectionRouter.

- vpr/src/base/vpr_types.h
- vpr/src/device/rr_graph_fwd.h
- vpr/src/route/binary_heap.cpp
- vpr/src/route/connection_router.cpp
- vpr/src/route/connection_router.h
- vpr/src/route/heap_type.cpp
- vpr/src/route/heap_type.h
- vpr/src/route/route_breadth_first.cpp
- vpr/src/route/route_common.cpp
- vpr/src/route/route_common.h
- vpr/src/route/route_tree_timing.cpp
- vpr/src/route/rr_graph_storage.h
- vpr/src/route/rr_node_fwd.h
When reviewing https://github.com/verilog-to-routing/vtr-verilog-to-routing/pull/1197#discussion_r389216334 @kmurray suggested removing `iconn` from the `ConnectionRouter` completely here: https://github.com/verilog-to-routing/vtr-verilog-to-routing/pull/1197
I've made that change, but done it here, because removing `iconn` is more involved because of its usage in `t_heap`.
> Use RREdgeId in t_heap

- vpr/src/device/rr_graph_fwd.h
- vpr/src/route/clock_connection_builders.cpp
- vpr/src/route/clock_network_builders.cpp
- vpr/src/route/clock_network_builders.h
- vpr/src/route/rr_graph.cpp
- vpr/src/route/rr_graph2.cpp
- vpr/src/route/rr_graph2.h
- vpr/src/route/rr_graph_clock.cpp
- vpr/src/route/rr_graph_clock.h
While debugging other issues I found inconsistencies with the rr_node_indices reverse RR graph look-up.
This PR adds:
* A verification routine which sanity checks RR node indices against the current RR graph (this also has the added benefit of codifying exactly what is stored in rr_node_indicies which hasn't always been clear).
* Fixes several bugs (mostly in the clock RR graph construction code) which were causing the inconsistencies
> Verify RR Node Indicies are Consistent with RR Graph

- vpr/src/route/rr_graph_storage.cpp
The stable sort requires additional memory, so this avoids using the stable sort.
> Remove stable sort by defining full element order.

- vpr/src/base/vpr_context.h
- vpr/src/route/route_common.cpp
- vpr/src/util/vpr_utils.h
Use the two bytes free space in t_rr_node_route_inf to implement a bitmap so that configurable nodes do not have to go through hash map look ups.
For configurable nodes (majority of nodes), looking through hash map to determine if the node is a non_configurable node is slow due to possible collision. A bitmap can be implemented to mitigate the issue.
Tests from symbiflow: picosoc, murax, top_bram_n1-3, dram_test_64x1d and buttons have been run with the change. Execution time of Routing section is reduced by around 15% without affecting quality of results.
Run through Benchmarks QoR Measurements. All tests passed. Since the tests do not have non_configurable nodes, there's no obvious improvement to execution time. Used to prove no increase in memory utilization.
Still waiting for results …
> Add a bitmap to speed up non_configurable look up

- .github/kokoro/continuous/nightly.cfg
- .github/kokoro/continuous/strong.cfg
- .github/kokoro/continuous/weekly.cfg
- .github/kokoro/presubmit/nightly.cfg
- .github/kokoro/presubmit/strong.cfg
- README.developers.md
Include '*.out' files (e.g. vpr.out, vpr.crit_path.out) in kokoro artifacts. These are the file which are useful for debugging flow issues and so should be included.
This PR will also update the kokoro documentation based on my experience debugging issues in kokoro runs.
> Updates to Kokoro artifacts and docs

- vpr/src/base/vpr_api.cpp
- vpr/src/pack/cluster.cpp
- vpr/src/pack/cluster.h
Refactors log messages for printing pb_type usage after packing too:
* Be in a consistent order (was using std::unordered_map, so variable depending on compiler)
* Show the heirarchical relation between pb_types
For example previously:
```
Pb types usage...
DSP                      : 31
LAB                      : 332
M9K                      : 105
PLL                      : 2
alm                      : 3066
dff                      : 5275
dffeas                   : 5275
half_DSP                 : 61
inpad                    : 3
io                       : 5
lcell_comb               : 3542
lut                      : 3546
lut6                     : 2
mac_mult                 : 61
mac_mult_reg             : 61
mac_out                  : 61
mac_out_output_only      : 61
memory_slice …
```
> Update pb_type usage log messages

- ODIN_II/regression_test/parse_result/parse_result.py
This PR change parser dict to ordered dict to preserve ordering of keys, older versions of python dict did not. python 3.5 (standard in ubuntu 16.04) dict does not preserve ordering
> Odin: use ordered dict to preserve ordering in parse script

- README.md
> README.md: "How to Cite" was duplicated

- vpr/src/draw/draw.cpp
We now ensure the canvas is only added the first time graphics is
initialized.
> vpr: Fix GTK warning about duplicate add_canvas

- doc/src/vpr/command_line_usage.rst
- vpr/src/base/read_options.cpp
- vpr/src/route/route_timing.cpp
- vpr/src/route/router_lookahead_map.cpp
- vpr/src/timing/slack_evaluation.cpp
- vpr/src/timing/timing_util.cpp
- vtr_flow/tasks/regression_tests/vtr_reg_strong/strong_router_update_lb_delays/config/config.txt
Builds on #1216 and #1109 to use lookahead based initial timing estimates during the first routing iteration. This PR enables this feature (and updating of lower bound delays) by default. 
This PR requires #1216 so the map lookahead is used by default.
> Change default router initial timing to lookahead

- libs/libvtrutil/src/vtr_array_view.h
- vpr/src/route/connection_router.cpp
- vpr/src/route/connection_router.h
- vpr/src/route/rr_graph_storage.cpp
- vpr/src/route/rr_graph_storage.h
t_rr_graph_view is a purely read-only view into the RR graph object.  The justification for the view class is two fold:
- Remove indirection overhead present in using a reference to `t_rr_graph_storage`
- Pave the way for a fully const copy of the RR graph to be read from disk via mmap.  This would enable 0 overhead for loading rr graphs.
> Add t_rr_graph_view and have ConnectionRouter use it

- .travis.yml
It appears Travis no longer includes various cmake/gcc/llvm PPA sources
in its whitelist, so we must change how they are specified.
Example build issues: https://travis-ci.com/github/verilog-to-routing/vtr-verilog-to-routing/jobs/313260700
> WIP: Update Travis PPA sources

- vpr/src/base/vpr_api.cpp
- vpr/src/pack/lb_type_rr_graph.cpp
Crashes occurred when an early error means some data structures are uninitialized when things are cleaned up.
> vpr: Fix crashes when freeing un-initialized data structures

- .gitattributes
GitHub uses https://github.com/github/linguist to do language stats. linguist however mis-detects a bunch of things in this repo. It also needs to be told about the "vendored" files in the repo.
This can be fixed by setting values via `.gitattributes` file which is done here.
```
53.46%  C         	 # This mostly comes from ABC
24.03%  C++
18.32%  Verilog  	 # This is the various imported regression tests / benchmarks
1.24%   HTML
0.85%   Perl
0.63%   Python
0.28%   Shell
0.28%   Cap'n Proto
0.27%   CMake
0.15%   Makefile
0.13%   Yacc
0.10%   JavaScript
0.07%   Lex
0.06%   Raku   		 # Misdetection
0.04%   M4
0.03%   CSS
0.03%   Objective-C
0.01%   Coq              # Misdetection
0.01%   Dockerfile
0.01%   SourcePawn    	 # Misdetection
0.00%   Lua
0.00%   Emacs Lisp
0.00%   Batchfile …
```
> Adding .gitattributes to fix GitHub language detection.

- vpr/src/route/rr_graph_storage.cpp
Some system implementations of sort are not really good in
only using the equality and less-than operators on iterators; add
operators observed to be needed.
Signed-off-by: Henner Zeller <h.zeller@acm.org>
CC: @litghost
> edge_sort_iterator: also add operator> and >=.

- vpr/src/place/place_delay_model.h
The change forces operator< to be inlined properly.
https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/1225
Original operator< is not inlined by compiler. Since the function is timing critical, force the function to be inlined can reduce place time by ~10% with xc7 tests and ~5% with QoR and Titan benchmark tests
Run through xc7 tests like picosoc and murax and passed QoR and Titan Benchmarks.
Comparison shows a place time reduction.
Comparison also proves there is no impact on quality of results.
> Force operator< to be inlined to reduce place time

- doc/src/vpr/command_line_usage.rst
Updating the documentation to add the two_stage_clock_routing cmd line option
Addresses part of https://github.com/verilog-to-routing/vtr-verilog-to-routing/pull/928#issuecomment-555432218
Adds documentation to an existing command line option
N/A
Documentation
> Adding documentation for two stage clock routing cmd line option

- .travis.yml
- ODIN_II/SRC/include/Hashtable.hpp
- libs/libvtrutil/src/vtr_ndmatrix.h
* Fixes for building with gcc-10
* Fixes for Travis infrastructure (should close #1263)
* ~~Add Travis gcc-10 and clang-9/10 build tests~~
* Turns out gcc-10 and clang-9/clang-10  aren't available with the OS version we're using in Travis
> Travis & gcc10 fixes

- libs/libvtrutil/src/vtr_math.h
Addresses coverity issues 201519, 200831, 165914
> vtrutil: Avoid potential divide by zero in geomean/arithmean

- libs/libvtrutil/src/vtr_vector.h
The using storage::data method forwarding only works if there is such
a method defined in the base class, which might not be true for all
specializations (I ran into this with a `vector<bool>` specialization).
This can be fixed by forwarding the method in a traditional way with
an inline implementation; then, the compiler will defer compiling it
to when actually needed.
Signed-off-by: Henner Zeller <h.zeller@acm.org>
> Fix compilation of vtr_vector for specializations without data().

- .github/kokoro/continuous/nightly.cfg
- .github/kokoro/continuous/strong.cfg
- .github/kokoro/continuous/strong_sanitized.cfg
- .github/kokoro/continuous/weekly.cfg
- .github/kokoro/presubmit/nightly.cfg
- .github/kokoro/presubmit/strong.cfg
- .github/kokoro/presubmit/strong_sanitized.cfg
- .github/kokoro/steps/vtr-test.sh
Building on PR #1276, this adds an additional Kokoro test, which runs vtr_reg_strong with a [sanitizer enabled](https://docs.verilogtorouting.org/en/latest/dev/developing/#sanitizers) build of VTR.
Since vtr_reg_strong is out main 'feature check' test it would be good to have it checked with sanitizers for memory issues/leaks etc.
We already have a sanitized version of the vtr_reg_basic test running in TravisCI, but the combination of longer compilation times with sanitizers enabled, and longer test time make it impossible to run vtr_reg_strong with sanitizers on TravisCI.
> Add vtr_reg_strong with sanitizers to Kokoro

- libs/libarchfpga/src/physical_types.h
- vpr/lsan.supp
- vtr_flow/scripts/run_vtr_flow.pl
On some systems there are memory leaks caused by system libraries (e.g. related to VPR graphics) which get picked up by LSAN.
This change adds an LSAN suppression file to avoid such leaks causing test failures (since they are outside of VTR's control).
Also fixes an uninitialized member variable in t_physical_tile_type also detected by sanitizers.
> Fix sanitizer failures in vtr_reg_strong

- .github/kokoro/continuous/nightly.cfg
- .github/kokoro/continuous/strong.cfg
- .github/kokoro/continuous/weekly.cfg
- .github/kokoro/presubmit/nightly.cfg
- .github/kokoro/presubmit/strong.cfg
- .github/kokoro/steps/hostinfo.sh
- .github/kokoro/steps/vtr-build.sh
- .github/kokoro/steps/vtr-test.sh
I've observed a number of run-time failures on the Kokoro nightly regression test, despite having fully updated the nightly regression test results, and the same tests passing when run locally.
For example see: https://source.cloud.google.com/results/invocations/354130ae-411d-454b-bdb0-6d66751a702e/targets/foss-fpga-tools%2Fverilog-to-routing%2Fupstream%2Fpresubmit%2Fnightly/log
where we see everything passes run-time and quality except for route time on some tests:
```
regression_tests/vtr_reg_nightly/complex_switch...[Fail]
k4_N8_topology-0.85sL2-0.15gL4-on-cb-off-sb_22nm_22nm.xml/mcml.v/common crit_path_route_time: golden = 81.87 result = 2124.87
```
Diffing the offending [VPR on Kokoro log file](https://storage.cloud.google.com/vtr-verilog-to-routing/artifacts/prod/foss-fpga-tools/veri …
> infra: Fix Kokoro nightly run-time failures

- vpr/src/place/place.cpp
If it happens that a routing graph contains zero-capacity channels then the computation of bounding-box placement cost yields in +infs. This may happen when VPR operates on a rr graph provided by a user. This makes the placement optimizer not optimize anything.
The cost is computed as inverse of a channel capacity. This PR adds a condition which catches zeros, logs a warnings and substitutes them with ones. This way channels of capacity 0 and 1 will have the same placement cost.
Solves poor timing-driven placement results in SymbiFlow on the Artix 200T architecture.
The placement algorithm was run twice: first in its unmodified version, second with the proposed modification. Each time using the same packed netlist. The results were assessed through the worst critical path delay estimated …
> Placement bb cost computation fix

- .github/kokoro/continuous/strong_sanitized.cfg
- .github/kokoro/presubmit/strong_sanitized.cfg
- .travis.yml
- libs/libarchfpga/src/arch_util.cpp
- libs/libarchfpga/src/arch_util.h
- libs/libarchfpga/src/read_xml_arch_file.cpp
- vpr/src/base/vpr_api.cpp
- vpr/src/pack/pack.cpp
- vpr/src/pack/prepack.cpp
- vpr/src/pack/prepack.h
- vtr_flow/scripts/run_vtr_flow.pl
Fixes various memory leaks which could occur when errors cause VPR to abort.
Also ensures LSAN uses a consistent exit code in case of leaks across different machines (for instance, ensuring consistent behavior on local developer and Kokoro machines).
This should fix the 'strong sanitized' Kokoro test, which was failing due to these leaks. We have some tests which check that VPR exits with an error in the case of invalid input. However some memory was leaked in these cases causing LSAN to exit with a different exit code (causing the test to fail).
> Sanitizer leak fixes

- libs/libarchfpga/src/physical_types.h
- libs/libarchfpga/src/read_xml_arch_file.cpp
- vpr/src/base/SetupVPR.cpp
This pull request aims to solve the following problem: 
- Keep the VPR delayless switch name in a constant string and can be used easily in later functions
- Avoid users to define a switch in the reserved names, which may crash the software.
Modify the readarch library to add a constant string for delayless switches.
Check codes are added to error out `read_arch`  when users try to define a switch in the same name as the delayless switch.
VPR setup code has been adapted to use the delayless switch constant.
This issue has been discussed during the VTR developer's meeting at FPGA'2020
Delayless switch is a special switch created by VPR internally.
It is the switch that is used by edges between SOURCE and OPIN, IPIN and SINK, or direct connection between CLBs in VPR's routing resource …
> Reserve VPR delayless switch name

- vpr/src/base/netlist_writer.cpp
VPR crashes when run with `--analysis` and `--gen_post_synthesis_netlist`. It turned out that the crash was caused by unconnected pins not having assigned nets in the `t_pb->pb_route` map.
I fixed that by checking whether a key is present in the map instead of retrieving its value and checking if it corresponds to a valid net. 
https://github.com/SymbiFlow/symbiflow-arch-defs/issues/1467
This is a bugfix that allows to get a post-synthesis netlist from VPR.
Locally by enabling the `--gen_post_synthesis_netlist` and seeing it not crash.
> Fixed post-synthesis netlist writing

- ODIN_II/SRC/ast_elaborate.cpp
- ODIN_II/SRC/ast_util.cpp
```
/home/travis/build/verilog-to-routing/vtr-verilog-to-routing/ODIN_II/SRC/ast_util.cpp: 1329 in assert_constant_positionnal_args(ast_node_t *, long)()
>>>     CID 210518:  API usage errors  (PRINTF_ARGS)
>>>     Argument "i" to format specifier "%d" was expected to have type "int" but has type "long".
1329                     error_message(AST, node->line_number, node->file_number,
1330                                   "%s node expects a constant at positional arguments [%d]\n", ast_node_name_based_on_ids(node), i);
```
```
/home/travis/build/verilog-to-routing/vtr-verilog-to-routing/ODIN_II/SRC/ast_elaborate.cpp: 1115 in build_hierarchy(ast_node_t *, ast_node_t *, int, sc_hierarchy *, bool, bool, e_data *)()
1110             if (child_skip_list) {
1111                 child_skip_list …
```
> Odin: resolve coverity errors

- README.md
Adding Antmicro to the contributing companies list in the README to reflect the commitment.
N/A
Antmicro have been contributing to VTR for quite a while, and expect to continue to do so for the foreseeable future related to our dedication to open source FPGA as well as customer projects. We want to raise prominence of the tool among the organizations we participate in - RISC-V and CHIPS, so showing commitment / contributions from more companies helps in this endeavor.
N/A
N/A
N/A
> doc: add Antmicro to contributing companies in README

- doc/src/vpr/graphics.rst
- vpr/src/draw/buttons.cpp
- vpr/src/draw/draw.cpp
- vpr/src/draw/draw.h
- vpr/src/draw/draw_types.h
Adds support for drawing SOURCE and SINK RR nodes in VPR graphics.
Also cleans-up RR drawing combobox options, and avoid expensive copying of RR nodes in pin drawing.
> Add support for drawing RR SOURCE and SINK nodes

- .readthedocs.yaml
- doc/README
- doc/_doxygen/ODIN_II.dox
- doc/_doxygen/abc.dox
- doc/_doxygen/ace2.dox
- doc/_doxygen/blifexplorer.dox
- doc/_doxygen/vpr.dox
- doc/requirements.txt
- doc/src/conf.py
This commit adds support for Doxygen and Breathe, allowing for generating Sphinx API documentation for C++ code
- Add Doxygen configuration files for:
- vpr
- abc
- ace2
- ODIN_II
-  blifexplorer
- Add Breathe plugin with the configuration for the mentioned projects
- Convert documentation to Python3 in order to satisfy all the dependencies
I've added functionality to skip API generation if Doxygen is not installed. It is also possible to skip regenerating the documentation after setting `SKIP_DOXYGEN` environment variable to `True`.
Resolves https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/568
The changes related to this PR were proposed in https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/1328
The changes were proposed in …
> Initial support for API documentation

- vtr_flow/scripts/run_vtr_flow.pl
Improves valgrind integration in run_vtr_flow.pl, specifically:
- Uses a unique exit code for valgrind failures (22) which is distinct from normal exit codes
- Includes the valgrind log in the regular tool log files, which ensures they show up when a failure log is printed (e.g. on TravisCI). Previously the vaglrind output was placed in a separate valgrind.log file which was rather mysterious.
- Treats detected memory leaks as errors, since most VTR tools are now leak-free in regular usage. This should detect new leak regressions.
> Improve valgrind vtr flow

- vpr/src/route/route_profiling.cpp
- vpr/src/route/route_profiling.h
- vpr/src/route/route_timing.cpp
Signed-off-by: Keith Rothman <537074+litghost@users.noreply.github.com>
This PR adds debug prints during the router profiling (when the `#define PROFILE` is active).
This PR is part of https://github.com/verilog-to-routing/vtr-verilog-to-routing/pull/1351 and has been split as it does not strictly belong to the lookahead context.
No issues
This helps in the debug process of the router behaviour
> route: profiling: add debugging prints.

- vpr/src/place/place.cpp
Changed get_net_wirelength_estimate() in vpr/src/place/place.cpp to
use linear equation, as in get_net_cost(). Original quadratic formula
offers no advantage over the linear one: similar runtime and QoR.
VTR_benchmarks & titan_benchmarks
- [x ] All new and existing tests passed
> Change VPR place WL estimate fun to linear

- doc/src/quickstart/index.rst
Visualization was misspelt (trivial fix)
> Fixed a typo in vtr quick start

- vpr/src/route/route_timing.cpp
Trying to speed up the VPR router by detecting its various performance bottlenecks and remove them by optimizations. This PR should not change any of the VPR router's functionalities.
This PR is still undergoing changes. I will update more commits if I manage to optimize other areas of the code.
1. Optimized overused info calculation. Noticeable speed up when running very large titan benchmarks, where the number of nets is large and many router iterations are performed.
- Tested on the LU8+Flagship and Stereovision+Tian benchmarks. No significant speedup.
- Tested on the Bitcoin+Titan benchmark. Appreciable speedup.
> Speed up Router's calculation of OveruseInfo

- vpr/src/draw/draw.cpp
made critical path lines thicker for better visualization in the GUI.
added line 3183 which sets the line widths for critical paths to 4 which is thicker than the current lines and thus will be clearer in the GUI.
[https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/1391#issue-650217985](url)
In some circuits, the critical paths are too faint and hard to locate, the new setting uses thicker lines that are easier to visualize.
> made critical path lines thicker

- ODIN_II/exec_wrapper.sh
- ODIN_II/verify_odin.sh
- doc/src/odin/dev_guide/verify_script.md
+ Outputs MISMATCH instead of SIGABRT on simulation failure
+ Allows passing regex for tests to run
Adds support for using regular expressions to specify a subset of tests to run.
e.g. `./verify_odin.sh -t regression_test/benchmark/task/syntax syntax/bm_*`
> Improved the verify odin script

- ODIN_II/SRC/verilog_bison.y
Get verbosity back from bison, since the macro YYERROR_VERBOSE seems to not provide detailed output as of bison v:3.6.4
The parser errors where uninsightful with the newer bison
odin full regression test
> [WIP] Odin: get verbose output out of bison

- vpr/src/route/rr_graph_storage.h
The maximux value of cost_index limits the number of segments to max
~(count / 2), because CHANX and CHANY segments each get a cost index.
At int8, the maximum number of segments is ~64, which can easily be
exceeded.  The 7-series arch has ~100 segment types.
The 7-series arch uses ~100 segment types, which cannot be stored in an `int8_t`.
> Increase width of cost_index to support more segment types.

- ODIN_II/regression_test/benchmark/task/arch_sweep/task.conf
Stop using glob for regression tests architecttures in odin
PR #1436 added a new architecture and the regresssion test added it due to globbing
> Odin: don't glob for memory architectures in arch_sweep

- dev/subtree_config.xml
Some of the external subtrees originally under 'kmurray' have been moved
to the verilog-to-routing origanization. Next time they are updated in
VTR (i.e. via dev/external_subtrees.py --update) they will pull from the
new repo locations.
> infra: Update subtree references from 'kmurray' to 'verilog-to-routing'

- doc/src/vpr/command_line_usage.rst
- doc/src/vpr/dusty_sa.rst
- vpr/src/base/SetupVPR.cpp
- vpr/src/base/ShowSetup.cpp
- vpr/src/base/read_options.cpp
- vpr/src/base/read_options.h
- vpr/src/base/vpr_types.h
- vpr/src/place/place.cpp
- vtr_flow/parse/pass_requirements/common/pass_requirements.vpr_route_min_chan_width.txt
- vtr_flow/parse/pass_requirements/timing/pass_requirements.vpr_pack_place.txt
- vtr_flow/parse/pass_requirements/timing/pass_requirements.vpr_route_fixed_chan_width.txt
- vtr_flow/parse/pass_requirements/timing/pass_requirements.vpr_route_relaxed_chan_width.txt
- vtr_flow/tasks/regression_tests/vtr_reg_nightly/titan_quick_qor/config/config.txt
- vtr_flow/tasks/regression_tests/vtr_reg_nightly/vtr_bidir/config/config.txt
This change adds a new schedule designed to simultaneously optimize for variables of varying sensitivity by continually sweeping a narrow temperature band at increasing rates.
https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/1203
This change is to increase the performance (quality/runtime) of the placer.
I've run a QoR comparison using `vtr_reg_nightly/vtr_reg_qor_chain`:
Metric | Relative to Baseline
--|--
vtr_flow_elapsed_time | 108.40%
placed_wirelength_est | 107.57%
place_time | **49.71%**
placed_CPD_est | 100.64%
min_chan_width | 105.69%
routed_wirelength | 106.89%
min_chan_width_route_time | 147.13%
crit_path_routed_wirelength | 105.72%
critical_path_delay | 101.79%
crit_path_route_time | 109.44%
> A New Simulated Annealing Schedule

- vpr/src/route/binary_heap.cpp
- vpr/src/route/binary_heap.h
- vpr/src/route/bucket.cpp
- vpr/src/route/bucket.h
- vpr/src/route/connection_router.h
- vpr/src/route/heap_type.h
VPR currently has unbounded memory usage as a result of #1032.  This PR caps the heap memory usage at 4x the number of nodes in the entire graph.  This is likely overkill for non-RCV routers.  For RCV based routers, this pruning will be problematic, but there likely needs to be a bounded memory limit for RCV based routers too.
#1032
The current heap implementations (both BinaryHeap and Bucket) can consume an unbounded amount of memory if the router is exploring bad paths that have incrementally better costs.  This has been observed to allow memory usage to grow to consume the entire RAM of ~128 GB machines in pathological cases.  Based on analysis, this memory usage around ~1000 heap entries for each node in the graph.
In #1032 other optimizations were identified, such as updating the …
> Prune the heap

- doc/src/vpr/command_line_usage.rst
- vpr/src/base/SetupVPR.cpp
- vpr/src/base/read_options.cpp
- vpr/src/base/read_options.h
- vpr/src/base/vpr_api.cpp
- vpr/src/base/vpr_types.h
- vpr/src/route/overuse_report.cpp
- vpr/src/route/overuse_report.h
- vpr/src/route/route_timing.cpp
- vpr/src/route/rr_graph_storage.cpp
- vpr/src/route/rr_graph_storage.h
Add the option **--max_logged_overused_rr_nodes N**, which is set to N=20 by default.
When each routing attempt fails, if the # of overused nodes is less than or equal to N, then print out the diagnostics of the overused nodes.
Add the option **--generate_rr_node_overuse_report on/off**, which generates a detailed report on overused RR nodes if the final routing attempt fails (i.e. the routing process has failed).
https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/1453
> Print out info/report on overused rr-nodes at the end of a failed routing iteration

- vtr_flow/scripts/run_vtr_flow.py
The max_router_iteration value being passed into run_vtr_flow was not passed onto vpr.
The default value for the parameter crit_path_router_iterations was overriding the inserted value of max_router_iteration, if max_router_iteration  was directly input. This has been fixed
[This issue is fixed here.](https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/1458)
It is important to be able to pass parameters directly to vpr as well as pass them through the vtr flow. 
Ran the titan tests as described in the issue, and ensured that the max_router_iteration value passed in was the one VPR was given
- [x ] Bug fix (change which fixes an issue)
> Vtr flow max router iteration fix

- ODIN_II/SRC/netlist_create_from_ast.cpp
In resolve_top_parameters_defined_by_parameters an error is thrown if it surpasses the recursive limit. The limit is an integer but was being printed with a %s not %d.
> Odin II: Fixed error found in Coverty Scan

- ODIN_II/SRC/ast_elaborate.cpp
- ODIN_II/SRC/ast_util.cpp
- ODIN_II/SRC/enum_str.cpp
- ODIN_II/SRC/include/odin_types.h
- ODIN_II/SRC/include/parse_making_ast.h
- ODIN_II/SRC/netlist_create_from_ast.cpp
- ODIN_II/SRC/parse_making_ast.cpp
- ODIN_II/SRC/verilog_bison.y
- ODIN_II/SRC/verilog_flex.l
- ODIN_II/regression_test/benchmark/task/keywords/automatic/synthesis_result.json
- ODIN_II/regression_test/benchmark/task/keywords/for/synthesis_result.json
- ODIN_II/regression_test/benchmark/task/keywords/input/simulation_result.json
- ODIN_II/regression_test/benchmark/task/keywords/input/synthesis_result.json
- ODIN_II/regression_test/benchmark/task/keywords/integer/simulation_result.json
- ODIN_II/regression_test/benchmark/task/keywords/integer/synthesis_result.json
- ODIN_II/regression_test/benchmark/task/keywords/output/simulation_result.json
- ODIN_II/regression_test/benchmark/task/keywords/output/synthesis_result.json
- ODIN_II/regression_test/benchmark/task/keywords/parameter/synthesis_result.json
- ODIN_II/regression_test/benchmark/task/keywords/signed_unsigned/simulation_result.json
- ODIN_II/regression_test/benchmark/task/keywords/signed_unsigned/synthesis_result.json
- ODIN_II/regression_test/benchmark/task/keywords/specify_endspecify/synthesis_result.json
- ODIN_II/regression_test/benchmark/task/keywords/while/synthesis_result.json
- ODIN_II/regression_test/benchmark/task/micro/synthesis_result.json
- ODIN_II/regression_test/benchmark/task/syntax/synthesis_result.json
This PR:
- add the ieee_std verification before passing over tokens in flex
- completes the reserved keyword support,
TODO:
- add c functions support
verilog 2005 support
no new test was added since this does not ast support.
> Odin: add reserved keyword support in Flex and verify standard

- doc/src/api/vpr/contexts.rst
- doc/src/api/vpr/index.rst
- doc/src/api/vpr/netlist.rst
- doc/src/dev/c_api_doc.rst
- doc/src/dev/index.rst
- doc/src/index.rst
This PR provides the Sphinx API documentation for VPR Contexts and Netlists, taken from the source code by Doxygen. 
https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/1328
This PR provides basic information about key VPR structures. The provided API documentation might be a convenient reference for new people in the project. 
The main motivation behind the mentioned changes is to create comprehensive API documentation for the project.
I tested the changes by running the documentation building locally. The same build is available in the CI
> API documentation of VPR key structures 

- vtr_flow/scripts/python_libs/vtr/util.py
Expected failures now work when show failure is off.
From the below issue, expected failure tests were failing if the show failures tag was not included. This has been fixed. In addition a regressed issue with error reporting has been fixed in conjunction with the show failures tag. 
[This is the issue ](https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/1459)that has been fixed
The vtr_flow should be able to expect failure when show failure is off. 
Regression tests run with show_failure and without.
> Vtr flow failure fix

- vpr/src/draw/draw.cpp
Change the colour of the flyline delay text to black. I also gave it a very small offset so that it does get seperated from the line it's printed over if zoomed in, but is still clearly related to said path. Ideally one would also draw a white box behind the text so it's clear, but ezgl doesn't make this very ez. 
A visual example of the issue below.
https://imgur.com/Zu5VrQd
I tested it on a random circuit and architecture and verified that it only effects flyline text, in the intended manner.
> Adding contrast to flyline delay text so it's readable now

- vpr/src/route/bucket.cpp
- vpr/src/route/bucket.h
Make some improvements to the bucket heap.  This PR adds some dynamic rescaling to the bucket heap and adds fully randomized popping.
The fully randomized popping from the front bucket was always the intention, but it was initially believed that the cost of implementing that would be prohibitive.  It isn't that expensive to do, and improves the worst case handling a bit.
The other bit change is dynamic bucket rescaling, which was an issue identified originally, but didn't manifest in the initial test cases.  However, with some placement seeds, the non-rescaling version of the bucket heap can become cost insensitive, and as a result have poor convergence qualities.
In some cases of tougher congestion resolution, the semi-randomized pop and lack of bucket scaling resulted in the bucket heap …
> Iterate bucket heap

- vpr/src/route/edge_groups.cpp
- vpr/src/route/edge_groups.h
- vpr/src/route/rr_graph.cpp
- vpr/src/route/rr_graph.h
- vpr/src/route/rr_graph_storage.h
- vpr/test/test_edge_groups.cpp
Depending on the node and edge order, the previous algorithm could result in an inconsistent group assignment, failing the following assertion:
https://github.com/verilog-to-routing/vtr-verilog-to-routing/blob/d4ea40548ee30aa13e27df5268760a86e38ad289/vpr/src/route/rr_graph.cpp#L3051
#1288 
These bugs were found while implementing #1271
A unit test has been added that fails with the previous algorithm, and also been tested with `random_shuffle` in #1271
> Fix some bugs in generating non-configurable edge sets.

- vtr_flow/scripts/python_libs/vtr/vpr/vpr.py
The suppression file has now been added to the new run_vtr_flow.py 
The old perl script included a suppression file to suppress various memory leak errors when sanitizing was enabled.  This functionality was missed in the initial conversion of run_vtr_flow to python but it is being implemented here. 
Should fix [this issue](https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/1470)
This could possibly fix [this issue](https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/1478)
Memory leaks in the vtr_reg_strong tests come up when sanitizing is enabled. This occurs mainly on the tests mentioned in the above issues. This causes some CI tests to fail on master.
I unfortunately have been unable to reproduce the errors locally and am unable to test this fully.
> Adding suppression file to the new vtr-flow.py

- vpr/src/base/atom_netlist.cpp
- vpr/src/base/atom_netlist.h
- vpr/src/base/read_blif.cpp
Saves around 20 out of 30 seconds in circuit cleaning on baselitex 7-series flow per VPR invocation.
We've noticed that the circuit cleaning time was large relative to the overall runtime (30 seconds into 120 second total run).  A profile run showed about 20 seconds being spent in a simple string copy to determine if a model is either inpad/outpad.
> Avoid strcpy inside of atom netlist.

- ODIN_II/SRC/verilog_bison.y
- ODIN_II/SRC/verilog_flex.l
```
New defect(s) Reported-by: Coverity Scan
Showing 1 of 1 defect(s)
** CID 212134:    (PRINTF_ARGS)
________________________________________________________________________________________________________
*** CID 212134:    (PRINTF_ARGS)
/home/travis/build/verilog-to-routing/vtr-verilog-to-routing/ODIN_II/SRC/verilog_bison.y: 1105 in ieee_filter(int, int)()
1099                            if(ieee_version < ieee_2001)
1100                                    delayed_error_message(PARSER, my_location, "error in parsing: (%s) only exists in ieee 2001 or newer\n",return_type)
1101                            break;
1102                    }
1103                    case vUWIRE: {
1104                            if(ieee_version < ieee_2005)
>>>     CID 212134:    (PRINTF_ARGS)
>>>     Argument …
```
> Odin: fix coverity error in bison and flex

- vpr/src/base/vpr_types.h
- vpr/src/route/overuse_report.cpp
- vpr/src/route/overuse_report.h
#1467 
[ipin_report.txt](https://github.com/verilog-to-routing/vtr-verilog-to-routing/files/5099061/ipin_report.txt)
1. cd to the VTR root directory
2. ./vtr_flow/scripts/run_vtr_flow.pl ./vtr_flow/benchmarks/verilog/diffeq2.v ./vtr_flow/arch/timing/k6_frac_N10_frac_chain_mem32K_40nm.xml -crit_path_router_iterations 100 --max_logged_overused_rr_nodes 50 --route_chan_width 32 --generate_rr_node_overuse_report on -temp_dir report_test
3. ls report_test/report_overused_nodes.rpt
I added block information for OPINs as well. If this is not desired, I'll discard this feature.
> Added block information for the IPIN/OPIN grid location in the overuse report

- ODIN_II/SRC/ast_elaborate.cpp
- ODIN_II/SRC/ast_util.cpp
- libs/librtlnumber/main.cpp
- libs/librtlnumber/regression_tests/basic_regression_tests.csv
- libs/librtlnumber/src/include/internal_bits.hpp
- libs/librtlnumber/src/include/rtl_int.hpp
- libs/librtlnumber/src/include/rtl_utils.hpp
- libs/librtlnumber/src/rtl_int.cpp
- libs/librtlnumber/src/rtl_utils.cpp
This PR adds support for tristate gates to the rtl arithmetic library
Also fixes string display to convert unbounded binaries to decimal strings without converting to integers.
> librtl: add bufifs and fix strings

- CMakeLists.txt
Turn off optimization and add debug flags for the "debug" build type.
This avoids the dreaded `<value optimized out>` in GDB.
> Make it easier to use GDB

- .travis.yml
This moves Travis to use `bionic` which is Ubuntu 18.04.5 LTS and has support until April 2023.
The "End of Standard Support" for Ubuntu 14.04.6 LTS was April 2019 which has meant things like the llvm upstream packages have started to remove support. For example from https://apt.llvm.org/;
> Aug 20th 2019 - Ubuntu Trusty removed (EOL)
Fixes #1505
> travis: Upgrade OS to Bionic

- vpr/src/draw/draw_debug.cpp
Fixes #1513.
https://developer.gnome.org/gtk3/stable/GtkWidget.html#gtk-widget-set-margin-left
> gtk_widget_set_margin_left has been deprecated since version 3.12 and
> should not be used in newly-written code.
>
> Use gtk_widget_set_margin_start() instead.
https://developer.gnome.org/gtk3/stable/GtkWidget.html#gtk-widget-set-margin-right
> gtk_widget_set_margin_right has been deprecated since version 3.12 and
> should not be used in newly-written code.
>
> Use gtk_widget_set_margin_end() instead.
> vpr: Fixing the usage of deprecated GTK methods in drawing code.

- vpr/src/base/SetupVPR.cpp
- vpr/src/base/read_options.cpp
- vpr/src/base/read_options.h
- vpr/src/base/vpr_types.h
- vpr/src/route/route_timing.cpp
- vpr/src/route/route_timing.h
- vpr/src/route/routing_predictor.cpp
- vpr/src/route/routing_predictor.h
This change uses the routing predictor to detect when congestion resolution slows down, and disables the high fanout routing logic.
https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/479
High fanout routing logic has been disabled in Symbiflow due to non-termination in some tests. This fixes that.
This change has been tested in Symbiflow, and also strong and nightly tests have been run locally.
> Prevent non-termination with high fanout routing logic

- vpr/src/base/metadata_storage.h
- vpr/src/route/rr_graph_util.cpp
- vpr/test/test_vpr.cpp
Update RR graph node IDs in node and edge metadata when using RR graph node reordering.
Bitstreams produced with node reordering (a `--reorder_rr_graph_nodes_algorithm` other than `none`) were not building with `fasm2bels` due to scrambled metadata.
#1270 
This fixes metadata when using RR node reordering.
`fasm2bels` tests now pass on [`fpga-tool-perf`](https://hydra.vtr.tools/jobset/dusty/fpga-tool-perf#tabs-jobs).
> Apply reordering to node and edge metadata

- doc/src/vpr/graphics.rst
fixed the image link for toggle block internal documentation.
The link for the gif showing how block internals work was incorrect and the gif wouldn't display on the website. I corrected the link in this PR.
> Fixed Toggle block internal image link

- vpr/src/base/read_place.cpp
When reading the place constraints file (`.place`) to fix some clusters, there was a bug in the token count. More precisely, the if statement that checked the token count did not take into account that there can bee more tokens than the ones specified due to the possibility to add comments to each line that generate several tokens when parsing a line.
> place_constraints: fixed number of tokens when reading place file

- ODIN_II/SRC/simulate_blif.cpp
```
/home/travis/build/verilog-to-routing/vtr-verilog-to-routing/ODIN_II/SRC/simulate_blif.cpp: 564 in is_node_ready(nnode_t *, int)()
558 npin_t* pin = node->input_pins[i];
559
560 bool has_missing_driver = false;
561 for (int j = 0; j < pin->net->num_driver_pins && !has_missing_driver; j++)
562 has_missing_driver = pin->net->driver_pins[j]->node == NULL;
563
>>> CID 214202: Null pointer dereferences (REVERSE_INULL)
>>> Null-checking "pin->net" suggests that it may be null, but it has already been dereferenced on all paths leading to the check.
564 if (!pin->net || has_missing_driver) {
565 bool already_flagged = false;
566 int j;
567 for (j = 0; j < node->num_undriven_pins; j++) {
568 if (node->undriven_pins[j] == pin)
569 already_flagged = true;
```
> Odin: Fixes coverity error in simulation

- .travis.yml
- vpr/src/draw/breakpoint.cpp
- vpr/src/draw/draw.cpp
- vpr/src/draw/draw.h
- vpr/src/draw/draw_debug.cpp
- vpr/src/draw/draw_debug.h
- vpr/src/draw/draw_types.h
- vpr/src/place/move_utils.cpp
- vpr/src/place/move_utils.h
- vpr/src/place/place.cpp
- vpr/src/place/placer_breakpoint.cpp
- vpr/src/place/placer_breakpoint.h
- vpr/src/route/route_timing.cpp
This PR follows #1287 . In this PR, some code refactoring was done while preserving the same functionality.
Taking into consideration some code review comments on #1287 
test that the UI is working for multiple VPR benchmarks
test that the feature is disabled if the compilation or the code flag is disabled
> Refactor the placer debug code

- vpr/src/base/read_place.cpp
This fixes an issue when reading placement files.
Placement files can be read for two different reasons:
1. Prior to the routing stage if the flow is divided in three diffrent calls to VPR P&R stages
2. To read placement constraints files. 
In SymbiFlow, there are a set of tests which are automated and the verilog design alongside with the PCF constraints is automatically generated. The PCF constraints will translate into a placement constraints file.
The issue is that, during the various test design generation, some parameters may allow for some IO signals to be unconnected after synthesis, conflicting with the fact that VPR throws an error if a block specified in the placement constraints file is not present in the packed netlist. …
> read_place: do not throw error if block name is invalid

- vpr/src/place/place.cpp
- vpr/src/place/place_util.cpp
- vpr/src/place/place_util.h
#1529 
#1534 (Discussion) #1542 (Merge)
**(This PR)**：
**(1. pass by arguments)**
**(2. move it into the placer global context)**
Future PR ideas:
Refactor place.cpp to modularize it and reduce its length and complexity.
> Refactor place.cpp Part III

- vpr/src/route/connection_router.cpp
- vpr/src/route/route_timing.cpp
- vpr/src/route/router_lookahead.cpp
- vpr/src/route/router_lookahead.h
- vpr/src/route/router_lookahead_cost_map.h
- vpr/src/route/router_lookahead_extended_map.cpp
- vpr/src/route/router_lookahead_extended_map.h
- vpr/src/route/router_lookahead_map.cpp
- vpr/src/route/router_lookahead_map.h
- vpr/src/route/router_lookahead_map_utils.cpp
Followup of https://github.com/verilog-to-routing/vtr-verilog-to-routing/pull/1449.
This PR is a followup to solve some outstanding comments on the lookahead extended map that require some more work.
To not have to wait a full CI build once again, these changes are applied to this followup PR
> Add extended lookahead map followup

- README.developers.md
Added a section to talk about generating new golden results when a reg test is failing.
> Updated documentation for generating new golden results

- vpr/src/place/place_util.cpp
- vpr/src/place/place_util.h
Fix Coverity Scan for t_placer_costs in place_util.h.
**Original report:**
Please find the latest report on new defect(s) introduced to Verilog to Routing found with Coverity Scan.
1 new defect(s) introduced to Verilog to Routing found with Coverity Scan.
1 defect(s), reported by Coverity Scan earlier, were marked fixed in the recent build analyzed by Coverity Scan.
New defect(s) Reported-by: Coverity Scan
Showing 1 of 1 defect(s)
** CID 214341:  Uninitialized members  (UNINIT_CTOR)
/home/travis/build/verilog-to-routing/vtr-verilog-to-routing/vpr/src/place/place_util.h: 51 in t_placer_costs::t_placer_costs(t_place_algorithm)()
________________________________________________________________________________________________________
*** CID 214341:  Uninitialized members  (UNINIT_CTOR) …
> Add in-class initializers for t_placer_costs to fix coverity scan defect

- .travis.yml
Although we moved to the Python flow scripts, there are a couple references to the Perl scripts in `.travis.yml`.  This fixes those.
> Replace lingering references to pl scripts in travis

- vpr/src/place/initial_placement.cpp
Signed-off-by: Andrew Butt <butta@seas.upenn.edu>
In the case where a design contains more SLICEMs than there are CLBLM_Ls in the architecture, the initial placement would still accept the CLBLM_L as a valid placement tile, resulting in a lack of sub_tiles to make the placement. This happens because there was no distinction of valid sub_tiles for a SLICEM, so the CLBLM_L still has free SLICELs allowing CLBLM_L to be chosen as a placement tile for a SLICEM while not having any free SLICEM sub_tiles. This fix only checks the free locations of valid sub_tiles, causing CLBLM_L to be rejected for placement of a SLICEM and allowing the CLBLM_R to be used instead.
I made this fix when using the symbiflow-arch-defs defined architectures, but the issue is relevant for all architectures with …
> Fix initial placement for heterogeneous tiles

- vpr/test/test_connection_router.cpp
Adds a unit test for the ConnectionRouter.
This unit test is both to verify functionality, and as a starting point to experiment with the router.
Unit tests allow quicker iteration because they run quickly and make it easier to locate bugs. Furthermore, they serve as documentation on to do something, and a starting point for changes.
Specifically, I'm working on parallel routing algorithms, so this is a starting point for that.
The unit test passes in `make test`.
> Add a unit test for the ConnectionRouter

- libs/libvtrutil/src/vtr_vector_map.h
This check seems to be causing an issue on the latest version of g++, where it's complaining about checking the sign on an unsigned type. See the issue linked for more information.
Closes https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/1539
Cleans up the build output, otherwise you get a warning everytime vector_map is referenced.
I built it successfully, and tested it on a super small circuit, everything seems in order.
> Remove index >= 0 check from vtr_vector_map.h

- ODIN_II/SRC/MixingOptimization.cpp
- ODIN_II/SRC/include/MixingOptimization.hpp
- ODIN_II/SRC/netlist_statistic.cpp
The commit addresses several errors
CID 212805:  API usage errors  (PRINTF_ARGS)
Related to #1496
The printf function used as part of the odin_error, was not even treated with a warning, while was caught as coverity scan.
Makes the code cleaner
Executed make test in ODIN_II directory
> ODIN_II: Changes to fix coverity scan errors

- vpr/src/base/netlist_writer.cpp
Summary of changes:
1. Traverse through input and output pins of blackbox primitives and populate timing_arcs, Tsu, Thld, Tco in local netist_writer data structure.
2. Store and output the correct reference clock ports in SDF writing.
https://github.com/SymbiFlow/vtr-verilog-to-routing/issues/537
There are multiple issues related to SDF writer for Blackbox primitive
1. The primitives being modelled as Blackbox have combinational and sequential timings. In present --analysis code, BlackBox combinational and sequential timings are not getting populated
2. Blackbox could have more than 1 reference clocks (e.g. Dual Port RAM). Current SDF generation does not handle timing checks w.r.t. specific clock. It uses a generic name "clk" to write out timing checks
- Turned on analysis option and …
> Blackbox SDF timing fixes

- vpr/src/place/analytic_placer.cpp
- vpr/src/route/rr_graph_indexed_data.cpp
This PR fixes an issue related to buffered nodes.
During the rr_graph_indexed_data calculation, the state of the switches of different segment type nodes are being checked and, currently, if two different computation of the buffering state of two nodes belonging to the same cost_index (e.g. same segment type), VTR throws an error.
The changes in this PR prevent VTR to throw the error, but instead, as the buffered switches "win" against the non-buffered ones, if a conflict is found when checking the buffering state of the switches of two nodes of the same segment type.
In case of conflict then, the buffered state of a node is set to one as there is no other possibility (e.g. the conflict can only be between zero and one).
https://github.com/verilog-to-routing/vtr-verilog-to-routing/pull/156 …
> Fix inconsistent buffering

- vpr/src/draw/draw_debug.cpp
This PR fixes an error that happens with old GTK version due to a bug in checking the available GTK version
> fix an issue with old GTK versions

- vpr/src/route/check_rr_graph.cpp
There seems to be a bug in check_rr_graph related to the check on the multiple connections between RR nodes.
While dealing with https://github.com/SymbiFlow/symbiflow-arch-defs/pull/1711 to fix the RR graph due to the presence of only one node for all the possible sides of a pin, I encountered the VPR error below:
```
Message: in check_rr_graph: node 279 (CHANX) connects to node 149 (IPIN) 2 times - multi-connections only expected for CHAN->CHAN.
```
Given that the comment prior to the check say that this pair of nodes can have multiple connections, I spotted a possible bug in the if statement.
> check_rr_graph: fix bug when checking multi-connections between nodes

- vpr/CMakeLists.txt
This adds a missing library (gcov) used by the profile guided optimization configuration, and adds a new variable to specify where to store the profile data (VPR_PGO_DATA_DIR.)
This is to enable PGO and make it more convenient to collect profile data.
I have tested `VPR_PGO_CONFIG=prof_gen` and `VPR_PGO_CONFIG=prof_use` on my machine.
> Add missing gcov library for PGO and configurable data directory

- vpr/src/pack/prepack.cpp
This PR moves an assertion related to chain pack-patterns elsewhere to allow for pb_type modes that break a chain.
Whenever there is a chain pack-pattern that passes through a pb_type with a mode in which chain-related pins are unconnected VPR raises an assertion. This happens at the pre-packing stage (the circuit doesn't matter). I've attached an example arch.xml file to allow reproduction of the issue.
In the attached example `arch.xml` there is a top-level pb_type `PB-CLB` that has two modes: `LUT4` and `LUT4_CARRY`. The former hosts the `LUT4` BLIF model (a classic LUT4) while the latter hosts a LUT that also has carry input and output pins for adder implementation `LUT4_CARRY`.
The assertion is throws specifically when the interconnect of the `LUT4` mode includes the carry-chain pin …
> Chain pack pattern assertion fix

- vpr/src/place/place_macro.cpp
This PR fixes a bug with direct connection lookup during identification of placement macro heads.
The function `net_is_driven_by_direct` looks up the `f_idirect_from_blk_pin` array using logical block index and its pin index. However, the array stores information for physical blocks and their pin indices.
In this PR I've added translation from logical to physical indices and used them for lookup.
While defining architecture for a QuickLogic FPGA that utilizes carry chains I've encountered a VPR segfault during placement. During debugging I've noticed that the lookup index used in the function in question is greater than the array size which shouldn't be happening. Looking of how the `f_idirect_from_blk_pin` array is allocated and what it stores allowed me to identify the issue.
For now …
> Direct connection lookup fix

- vpr/src/route/rr_graph_util.cpp
- vpr/src/route/rr_graph_util.h
It might be useful to get only the fan-in edges of a certain destination node, and currently the RR graph APIs do not provide such a possibility.
This PR adds a fan-in list constructor and its destroyer so that the extra memory is freed once the purpose of the fan-in lists has been fulfilled.
> rr_nodes: add fan-in list generator

- vpr/src/route/rr_graph_indexed_data.cpp
This PR solves a coverty issue on the delay normalization factor calculation function for which, in corner cases, there might be a division by zero.
> rr_graph: avoide div-by-zero issues while getting the delay norm fac

- vpr/src/route/rr_graph_indexed_data.cpp
Follow-up PR to add comments requested in https://github.com/verilog-to-routing/vtr-verilog-to-routing/pull/1576
> rr_graph: added comments on the new rr_graph_indexed data calculation

- vpr/src/pack/prepack.cpp
This is a code comment as requested in #1591
> Code comment for #1591

- vpr/src/base/ShowSetup.cpp
- vpr/src/base/constraints_load.cpp
- vpr/src/base/gen/vpr_constraints_uxsdcxx.h
- vpr/src/base/gen/vpr_constraints_uxsdcxx_interface.h
- vpr/src/base/read_options.cpp
- vpr/src/base/vpr_constraints.xsd
- vpr/src/base/vpr_constraints_reader.cpp
- vpr/src/base/vpr_constraints_reader.h
- vpr/src/base/vpr_constraints_serializer.h
Added a change to the XML Schema so that atoms and regions can be added in any order. Also added ability to provide regular expressions in place of atoms.
> Vpr constraints fixes

- .editorconfig
https://editorconfig.org/ is a common file that is understood
by virtually all editors and IDES that deal with code. With this
file, contributors to the code-base already have a good head-start
complying with the expected formatting rules.
Note, this also includes a trim_trailing_whitespace setting, that
will remove random whitespace at end of lines, which will reduce
merge conflicts on such lines. Some existing files have spurious
whitespace at the end of lines, so whenever they are edited first
under .editorconfig configuration they will be cleaned up.
In recent pull requests I noticed that I had to manually configure my editor to match the local customs. With a `.editorconfig` file, this wouldn've happened automatically. This is an issue all contributors face. Let's make it simple to …
> Add .editorconfig to tell editors/IDEs basic whitespace rules.

- vtr_flow/parse/parse_config/vpr_standard.txt
Remove unnecessary parsed info that was used for placement debugging
> remove unnecessary placement parsing info

- .github/kokoro/steps/vtr-test.sh
There is logic to cleanup the VTR working space after `run_reg_test.py`, but if the `e` flag (terminate on error) is set, then the cleanup logic never runs.  This change un-sets the `e` flag around `run_reg_test.py` and forwards the result.
Might help with #1666
> Fix cleanup if `run_vtr_test.py` generates an error.

- README.developers.md
- dev/pylint_check.py
In the past pylint_check.py could only run on the entire repository.  Now you can provide arguments to individual files to check.  While you could always manually call pylint on your individual files, our script has certain rules that are ignored, so it's better to provide this functionality through the script.
Closes #1683
> Update pylint_check.py to check individual files

- vpr/src/place/critical_uniform_move_generator.cpp
- vpr/src/place/feasible_region_move_generator.cpp
- vpr/src/place/move_utils.cpp
- vpr/test/test_vpr_constraints.cpp
- vpr/test/wire.constraints
This PR fixes an issue for which a fixed block could get swapped during placement
https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/1681
Critical blocks and IOs cannot get swapped and must preserve the initial constraints.
> place: fix illegal swap of fixed blocks

- vpr/src/route/check_rr_graph.cpp
- vpr/src/route/router_lookahead_map.cpp
- vpr/src/route/rr_graph2.cpp
- vpr/src/route/rr_graph_uxsdcxx_serializer.h
This PR aims to deploy the new node_side() API to rr_graph builder and router.
This PR:
To address issue #1580
In Titan architecture, a ``rr_node`` may appear in multiple sides of a logic block. However, VPR's rr_graph builder and router only assumes that a ``rr_node`` locates on only 1 side. There has been patches (#1621 and #1661) to extend the side support for ``rr_node`` and deploy to GUIs. This PR is a follow-up PR as planned to deploy the new API node.is_node_on_specific_side() in place of the to-be-deprecated API node_side() in the rr_graph builder and router.
After this PR, the old API can be safely removed.
> Deploy new node.side() API to rr_graph builder and router

- ODIN_II/SRC/netlist_create_from_ast.cpp
Odin_II buffers each signal in block statements like ASSIGN. Moreover, Odin_II eliminates BUF_NODE while doing the partial mapping. Since Odin looks up for clock signals before the partial mapping phase if the actual clock is assigned to a new signal Odin_II considers it as a new separate clock while it is the same as the actual one. This PR resolves the issue by considering the source of each buffered clock signal as the clock signal.
ML-benchmarks: tiny_darknet_hls.v
Bug fix
1. make test (ODIN-II)
2. Basic Regression Tests
3. Strong Regression Test
4. Basic Valgrind Memory Tests (also, Valgrind memory tests for all other regression suits)
5. Sanitized Basic Regression Tests
6. Odin-II Micro Tests
> Buffered clocks recognized as a different clock than the actual clock 

- doc/src/tutorials/flow/basic_flow.rst
Updating the Basic Design Flow tutorial. 
The tests pointed to in the tutorial are outdated and golden_results don't include every parameter. Updating the tutorial to point to the basic regression tests at regression_tests/vtr_reg_basic would ensure that the design flow tutorial stays up to date.
Avoids the task of generating golden_results for the basic_flow tasks every time they get out-of-date.
> Updating the documentation design tutorial 

- libs/EXTERNAL/libargparse/src/argparse.cpp
- utils/fasm/src/main.cpp
- utils/fasm/test/test_fasm.cpp
- utils/fasm/test/test_fasm_arch.xml
Added execution of post routing cluster pin fixup to genfasm via the `sync_netlists_to_routing()` function.
#1730
Correct FASM generation for annotated blocks that have ports with equivalent input pins.
Using the testcase attached to the issue #1730. Also this PR contains update to the `genfasm` test which verifies that FASM features from clb muxes correspond to those from rr graph edges.
> Add missing post routing cluster pin fixup to genfasm

- ODIN_II/SRC/ast_elaborate.cpp
According to Verilog Standard 2005, concatenate results are unsigned, regardless of the operands. 
IEEE.1364-2005 pp.65
#1634 
Bug fix
1. make test (ODIN-II)
2. Basic Regression Tests
3. Strong Regression Test
4. Basic Valgrind Memory Tests (also, Valgrind memory tests for all other regression suits)
5. Sanitized Basic Regression Tests
6. Odin-II Micro Tests
> Neglecting concatenation case for signedness

- vtr_flow/primitives.v
Fixed a syntax error in Verilog LUT cell model in `vtr_flow/primitives.v`. The parameter `K` of the `LUT_K` cell was missing a default value.
None
To be able to do post-pnr simulation of a design.
With Yosys that can now successfully parse the file.
> Fix for syntax error in vtr_flow/primitives.v

- libs/libvtrcapnproto/CMakeLists.txt
Use CMAKE_INSTALL_DATADIR in order to install capnp files to a File Hierarchy Standard compliant directory.
N/A
On Linux, with `CMAKE_INSTALL_PREFIX=/usr`, the current configuration places the capnp files in `/usr/capnp/`, which is a nonstandard directory. Using `CMAKE_INSTALL_DATADIR` results in `/usr/share/vtr/` instead, which makes more sense.
`make install` places the capnp files under `CMAKE_INSTALL_PREFIX/CMAKE_INSTALL_DATADIR/vtr/`.
> libvtrcapnproto: install capnp files to DATADIR

- ODIN_II/CMakeLists.txt
- blifexplorer/CMakeLists.txt
- libs/EXTERNAL/libblifparse/CMakeLists.txt
- libs/EXTERNAL/libsdcparse/CMakeLists.txt
- libs/libarchfpga/CMakeLists.txt
- utils/fasm/CMakeLists.txt
- utils/route_diag/CMakeLists.txt
- vpr/CMakeLists.txt
With `INTERPROCEDURAL_OPTIMIZATION`/LTO enabled, LDFLAGS from the environment are ignored.
N/A
CMake takes the default linker flags from the LDFLAGS environment variable and initializes the targets' `LINK_FLAGS` with it. If `set_target_property()` is used to overwrite a target's `LINK_FLAGS`, these initial linker flags from the environment are lost.
```
$ env LDFLAGS=-Wl,-z,relro cmake -B build -S . -DVTR_IPO_BUILD=on
$ grep relro build/vpr/CMakeFiles/vpr.dir/link.txt
```
> CMake: append to LINK_FLAGS instead of replacing them

- libs/librtlnumber/src/include/internal_bits.hpp
In VNumber copy constructor with new length, the defined_size variable was not initialized. As a result, Odin_II would throw an error in case of facing new VNumbers without defined_size equal to true while they have already a size specified.  
#1738
Bug fix!
> Initializing defined_size in VNumber Copy constructor

- .github/kokoro/presubmit/nightly.cfg
Updated nightly presubmit configuration to include artifact collection for files ending in .gz. This is needed because all output files from nightly runs are zipped to save disk space, and so to collect those files the artifact collection had to be updated. The presubmit runs are the ones launced on every pull request.
> Add artifact collection of files ending in .gz to nightly presubmit runs

- libs/EXTERNAL/libblifparse/CMakeLists.txt
- libs/EXTERNAL/libsdcparse/CMakeLists.txt
- libs/liblog/CMakeLists.txt
The test binaries used for `make test`/ctest are also installed to the destination system using `install()` directives. This makes little sense, as the tests do not need to be run outside a development environment.
N/A
I am packaging vtr in the [vtr-git AUR package](https://aur.archlinux.org/packages/vtr-git/). The installed package should not contain unit test binaries.
`make install` no longer installs test binaries, `make test` still works as expected.
> CMake: do not install test binaries

- dev/pylint_check.py
- run_reg_test.py
- vtr_flow/scripts/flow_script_template.txt
- vtr_flow/scripts/python_libs/vtr/log_parse.py
- vtr_flow/scripts/python_libs/vtr/parse_vtr_task.py
- vtr_flow/scripts/python_libs/vtr/task.py
- vtr_flow/scripts/python_libs/vtr/util.py
- vtr_flow/scripts/run_vtr_task.py
The run_vtr_task.py script can generate vtr_flow.sh scripts by adding -system scripts option. Each script runs one (design, arch) pair of the specified task
In this PR, some bugs of this generation process is fixed:
- the script now generates a correct vpr command
- the script now generates the full cartesian product runs of the designs, architectures, and script parameters.
- the script adds executable permission to the generated shell scripts
The generated shell scripts can be used to run multiple VPR runs in parallel on a large cluster.
> Fixing the generated vtr_flow.sh scripts

- libs/libvtrutil/src/vtr_memory.h
Fixes #1745, see the commit message or the issue for details.
The test suite still passes, and compilation is now successful with GCC 11.
> aligned_allocator: add operator==

- vpr/src/device/rr_spatial_lookup.cpp
- vpr/src/device/rr_spatial_lookup.h
- vpr/src/route/rr_edge.h
- vpr/src/route/rr_graph.cpp
- vpr/src/route/rr_graph2.cpp
- vpr/src/route/rr_graph2.h
- vpr/src/route/rr_graph_storage.h
This pull request is a follow-up PR on the #1693 
This is part of the PR request plan on routing resource graph, being a follow-up PR on the #1693 
Motivated by @vaughnbetz 's suggestion, the top priority is to deploy the new data structure ``RRGraphBuilder`` in place of the legacy data structure ``rr_node_indices`` in routing resource graph builder functions.
This PR addresses the comment, where we fully remove the use of ``rr_node_indices`` in builder functions.
As a result, ``RRGraphBuilder`` data structure is the only one that builder functions are talking to.
Should pass all the existing tests, since this PR is about refactoring.
> Deploy RRGraphBuilder in place of rr_node_indices in routing resource graph builder functions

- .github/gha/install_dependencies.sh
- .github/workflows/test.yml
- BUILDING.md
- Dockerfile
The CI compatibility tests currently only go up to GCC 9 and clang 8, which are both quite old. While clang 11 and 12 aren't in Ubuntu 18.04, clang 10 and GCC 11 are possible.
This will only work once #1749 is merged.
To test vtr with modern compilers.
Since this only adds new tests, there's not much to test.
> CI: Test compatibility with recent compilers

- .github/gha/install_dependencies.sh
- .github/workflows/test.yml
- BUILDING.md
- Dockerfile
- ODIN_II/SRC/include/odin_error.h
- ODIN_II/SRC/odin_error.cpp
- vpr/CMakeLists.txt
- vpr/src/base/vpr_types.h
See #1754 for the motivation.
GCC 5 and 6 were still used for many CI runs, so the default was updated to GCC 11. This created a few new warnings that didn't exist in the older compilers, causing the `-Werror` job to fail - I've included the fixes in this pull request.
Resolves #1754
All CI jobs work (again).
> CI: Drop GCC 5&6 support

- .gitpod.Dockerfile
- .gitpod.yml
- README.md
1. The origin remote of the repository in Gitpod was the Loksu fork -> changed to the main VTR repo
2. Running tasks in the `gitpod.yml` caused errors at the starting point of the Gitpod -> removed
3. Setting the working directory for the docker file as VTR_ROOT env.
wrong URL and removing errors
> Gitpod configuration

- dev/upgrade_vtr_archs.sh
the following warnings are showing while `dev/upgrade_vtr_archs.sh` is called. Odin's XMLs are to read the configuration of each run. There is no need to go through the Odin directory looking for XML files.
removing warning generated by `upgrade_vtr_arch.sh`
> Avoiding Odin's xml config file to be considered as arch file

- .gitpod.yml
signed-off-by: Seyed Alireza Damghani <sdamghan@unb.ca>
VTR will be compiled in debug mode in GitPod prebuilt.
follow up on #1766
> Building VTR in debug mode in GitPod Initialization

- doc/src/vtr/tasks.rst
- vtr_flow/benchmarks/hdl_include/ch_intrinsics_modified.v
- vtr_flow/benchmarks/hdl_include/include/README.md
- vtr_flow/benchmarks/hdl_include/include/generic_definitions1.vh
- vtr_flow/benchmarks/hdl_include/include/generic_definitions2.vh
- vtr_flow/benchmarks/hdl_include/include/memory_controller.v
- vtr_flow/scripts/python_libs/vtr/flow.py
- vtr_flow/scripts/python_libs/vtr/odin/odin.py
- vtr_flow/scripts/python_libs/vtr/task.py
- vtr_flow/scripts/run_vtr_flow.py
- vtr_flow/tasks/regression_tests/vtr_reg_basic/hdl_include/config/config.txt
- vtr_flow/tasks/regression_tests/vtr_reg_basic/task_list.txt
1. `includes_dir` and `include_list_add` have been added to task config files as optional parameters. Users can pass additional (.v) or (.vh) files including some extra feature to the VTR flow. 
2. A modified version of ch_intrinsics has been added to benchmarks without `define macros
3. New header files have added to cover the ch_intrinsics definitions
4. New test is added to vtr_reg_basic/no_timing to test the new feature
Usage:
- For **run_vtr_flow** users need to added the parameter `-include 1.v 2.vh ...`
- For **run_vtr_task**, `includes_dir` and `include_list_add` need to be specified in the task config.txt
PR #1753 
Support a new feature to add separate files than the main circuit design to cover additional design supports like macro definitons
`run_vtr_task`
`run_vtr_flow` …
> Adding includes_dir and include_list_add to task config file

- vpr/src/base/region.cpp
- vpr/src/place/initial_placement.cpp
The intersection function belonging to the Region class was modified to also consider cases where one region has no subtile specified and the other region has a subtile specified.
Previously, the region intersection function would only calculate the intersection when the two regions passed in both had no subtiles specified, or both had the same subtiles specified. However, this meant that the routine would miss out on some cases. 
For example, if region r1 was constrained from region (0,0) to (10,10) with subtile 0 specified, and region r2 was constrained from region (0,0) to (10,10) with no subtile specified, the previous intersection function would say that there is no intersection between these two regions. The new intersection function would return (0,0) to (10,10) with subtile 0 as …
> Improve region intersect function

- doc/src/arch/reference.rst
- doc/src/tutorials/arch/fracturable_multiplier_bus.rst
Fixed documentation errors found within the architecture modelling tutorials section and the architectural reference section.
- Within the Tutorials section
- Under the Fracturable Multiplier Bus-Based Complete Example
- When describing the primitives within the DSP slice, number of flip-flops to be instantiated was 64, but should be 72
- Within the Architecture Reference section
- Under the <row> tag 
- The optional attributes for spaces between tiles should be incrx not incry 
- Under the <region> tag
- The descritpion for incry should be "An expression specifying the vertical increment between block instantiations
within the region." instead of "An expression specifying the horizontal increment between block instantiations
within the region." 
- Under the <equivalent_sites> tag
- The …
> Fixing up minor errors within the documentation

- vpr/src/device/rr_spatial_lookup.cpp
- vpr/src/device/rr_spatial_lookup.h
- vpr/src/pack/post_routing_pb_pin_fixup.cpp
- vpr/src/place/timing_place_lookup.cpp
- vpr/src/route/route_common.cpp
- vpr/src/route/router_lookahead_map.cpp
- vpr/src/route/router_lookahead_map_utils.cpp
This PR focuses on updating client functions of the ``rr_node_indices``, which are ``placer``, ``router`` and post-routing synchronizer.
We use the refactored data structure ``RRGraphBuilder`` to replace the legacy data structure ``rr_node_indices``.
This PR aims to eliminate the use of ``rr_node_indices`` in the client functions, as one step further in deprecating the legacy data structure.
Checklist:
This pull request is a follow-up PR on the routing resource graph refactoring effort https://github.com/verilog-to-routing/vtr-verilog-to-routing/pull/1693
After the previous PR #1747 , we start reworking all the source files that use the legacy data structure ``rr_node_indices`` in a high priority, in order to deprecate the legacy data structure as soon as possible.
Current statistics on …
> Deploy ``RRGraphBuilder`` in Client Functions to replace the use of ``rr_node_indices``

- doc/src/vtr/power_estimation/index.rst
- vpr/src/power/power_sizing.cpp
Some documentation changes for the power estimation flow.
1. Fixing the heading hierarchy
2. Changing function name from power_calc_primitive to power_usage_primitive
3. Adding some clarity in the flow steps and what's the name of the output file.
4. Adding example command of run_vtr_flow with -power enabled
5. Adding that the power model doesn't model single-bit adders in logic blocks.
Also, a fix that was identified here: https://groups.google.com/g/vtr-users/c/7IzU83_amKs
https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/1797
> Modifications to the power estimation flow and documentation

- vpr/src/device/rr_spatial_lookup.cpp
- vpr/src/device/rr_spatial_lookup.h
- vpr/src/route/clock_connection_builders.cpp
- vpr/src/route/clock_connection_builders.h
- vpr/src/route/clock_network_builders.cpp
- vpr/src/route/clock_network_builders.h
- vpr/src/route/rr_edge.h
- vpr/src/route/rr_graph.cpp
- vpr/src/route/rr_graph2.cpp
- vpr/src/route/rr_graph_clock.cpp
- vpr/src/route/rr_graph_clock.h
This PR focuses on updating RRGraph clock builder functions, where we use the refactored data structure ``RRGraphBuilder`` to replace the legacy data structure ``rr_node_indices``.
This PR aims to eliminate the use of ``rr_node_indices`` in the RRGraph clock builder, as one step further in deprecating the legacy data structure.
Checklist:
This pull request is a follow-up PR on the routing resource graph refactoring effort https://github.com/verilog-to-routing/vtr-verilog-to-routing/pull/1779
After the previous PR #1779  , we start reworking all the source files that use the legacy data structure ``rr_node_indices`` in a high priority, in order to deprecate the legacy data structure as soon as possible.
Current statistics on the files that use ``rr_node_indices`` (in total there are 143 …
> Deploy ``RRGraphBuilder`` in RRGraph Clock Builder to replace the use of ``rr_node_indices``

- README.developers.md
Described valgrind and the sanitizer suppression files in the developer debugging aids documentation.
We didn't document these, so many people didn't know how to run them properly outside the CI system.
- [ x] My change requires a change to the documentation
- [ x] I have updated the documentation accordingly
> Update README.developers.md : Added sanitizer suppression file info, and mention of valgrind.

- ODIN_II/regression_test/parse_result/parse_result.py
The PR is to show "Expected Failure" status in Odin verification script
Issue #1808 
PR #1807
> [Odin]: show expected failure status in verify odin script

- vpr/src/device/rr_graph_view.h
- vpr/src/draw/draw.cpp
- vpr/src/power/power.cpp
- vpr/src/route/check_rr_graph.cpp
- vpr/src/route/rr_graph.cpp
- vpr/src/route/rr_graph_area.cpp
- vpr/src/route/rr_node.h
- vpr/src/route/rr_node_impl.h
In this PR, I have implemented `RRGraphView::node_fan_in()` throughout VTR. Every time `device_ctx.rr_nodes[index].fan_in()` was called has been replaced with `rr_graph.node_direction(RRNodeId(index))`. In order to do this, I followed a pattern similar to that in the last PR.
These changes are a continuation of the RRGraphView API implementation effort.
I have run the regression tests for `vtr_reg_strong` along with the QoR testing found at `    $ ../scripts/run_vtr_task.py regression_tests/vtr_reg_nightly_test3/vtr_reg_qor_chain`. Results from these QoR tests can be found below. The file containing all results can be found [here](https://github.com/verilog-to-routing/vtr-verilog-to-routing/files/6810934/node_fan_in.xlsx)
Only rows that are different are shown.
|	| VTR Before These …
> RRGraphView::node_fan_in() Implementation

- dev/nix/shell.nix
~Pins the local nix shell channel to 20.09, a known working version.~
Drop Python 2.7 in the the nix shell
There are issues with Python 2.7 deprecations in the latest 21.05 channel, that cause errors
in nix-shell startup. ~I have not investigated further, just want to build VTR :)~
N/A
The described actions in: https://docs.verilogtorouting.org/en/latest/building/building/#using-nix
did not work as expected.
Local tests using:
```
nix-shell dev/nix/shell.nix
make
```
N/A for the above.
> [nix] drop python 2.7

- vtr_flow/scripts/run_vtr_task.py
specifying the `common_task_prefix` variable type while initializing it
fix CI error for python-format
> [Infra]: fix run_vtr_task lint error

- vpr/src/route/route_common.h
I was looking through the VPR router to compare it to nextpnr's one and noticed a small issue in one of the assertions, base cost was being multiplied twice instead of by the accumulated historical cost. This caused an assertion failure when debug assertions are enabled.
> route_common: Fix cost check assertion

- doc/src/api/vpr/index.rst
- doc/src/api/vpr/rr_graph.rst
- vpr/src/device/rr_graph_builder.h
- vpr/src/device/rr_spatial_lookup.h
This is a follow-up pull request to address the comments in #1828 
It also addressed the issue #1834 
Checklist:
**Note: the code comments in ``rr_graph_view.h`` is untouched to avoid merging conflicts as @ethanroj23 is working on it.
This pull request is part of the refactoring effort of routing resource graph #1828 
Along with refactoring, RRGraph APIs are being developed with enriched comments. It is time to build the documentation for the APIs.
The documentation changes can be previewed at the readthedocs in the pull request checks.
Screenshots taken from the readthedocs:
> Add ``RRGraph``-related API to documentation and clean-up ``RRSpatialLookup`` methods

- libs/EXTERNAL/libezgl/examples/basic-application/basic_application.cpp
- libs/EXTERNAL/libezgl/examples/basic-application/main.ui
- libs/EXTERNAL/libezgl/include/ezgl/application.hpp
- libs/EXTERNAL/libezgl/include/ezgl/callback.hpp
- libs/EXTERNAL/libezgl/include/ezgl/graphics.hpp
- libs/EXTERNAL/libezgl/include/ezgl/point.hpp
- libs/EXTERNAL/libezgl/src/application.cpp
- libs/EXTERNAL/libezgl/src/callback.cpp
- libs/EXTERNAL/libezgl/src/canvas.cpp
- libs/EXTERNAL/libezgl/src/graphics.cpp
Update libezgl subtree to the latest version. The latest version adds some bug fixes and functionality (scaling and justification options), and most importantly, uses the left mouse button for panning instead of the middle mouse button.
Panning with the left mouse button is easier than the middle button with touchpads. It is also more common. 
The graphics are tested using the -disp on option. The update does not require any modifications to the VTR code.
> Update libezgl external subtree

- vpr/src/device/rr_graph_builder.cpp
- vpr/src/device/rr_graph_builder.h
- vpr/src/route/clock_connection_builders.cpp
- vpr/src/route/clock_network_builders.cpp
- vpr/src/route/rr_graph.cpp
- vpr/src/route/rr_graph_uxsdcxx_serializer.h
- vpr/src/route/rr_node.cpp
- vpr/src/route/rr_node.h
This PR focuses on updating routing resource graph builder functions, where we use the refactored data structure `RRGraphBuilder` to shadow the discreted data structure `rr_graph_storage`.
This PR aims to fully deprecate the direct use of the legacy API `set_coordinates()` from `rr_node` data structure.
After this PR, the `set_coordinates` API is fully deprecated and the `set_node_coordinates` from the refactored data structure `RRGraphBuilder` is the only way to use.
Checklist:
This pull request is a follow-up PR on the routing resource graph refactoring effort [ #1805 ](https://github.com/verilog-to-routing/vtr-verilog-to-routing/pull/1805)
This PR is the continuation to the refactoring effort with a focus on shadowing the `rr_graph_storage` APIs in `RRGraphBuilder` data structure.
This …
> Add a new API set_node_coordinates() to RRGraphBuilder

- vtr_flow/scripts/run_vtr_flow.py
Logs peak memory usage during VPR CI run. The information is extracted from the `vpr.out` (which I assumed obtained using valgrid)
Addresses part of issue  #1808 
https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/1808#issuecomment-904022281
It has been tested locally, I have attached the screenshot.
> [CI] Logs Memory during CI Run

- vtr_flow/scripts/run_vtr_flow.py
The change in this pull request is the same as PR #1827. Added the change to a new branch because I wasn't able to checkout the other remote branch as it was on a fork off of the main remote repo verilog-to-routing/vtr-verilog-to-routing.
The original change was to make sure the runner looks at the argument track_memory_usage to see whether memory tracking should be turned on or off, instead of just always making it on.
An additional change was made that was requested in a comment on #1827 - the default value of track_memory_usage was set to "True" so that track_memory_usage is always on unless the argument specifies that it should be off.
- [ x] Bug fix (change which fixes an issue)
> fix_track_memory_usage

- dev/check-format-py.sh
- dev/check-format.sh
As discussed in https://github.com/verilog-to-routing/vtr-verilog-to-routing/pull/1804#discussion_r672426293, maybe the common CI script does not need to be sourced in the `dev/check-format*` scripts.
/cc @mithro
> dev scripts should not depend on ci scripts

- vpr/src/device/rr_graph_builder.h
- vpr/src/route/rr_graph.cpp
**Description**
This PR focuses on updating routing resource graph builder functions, where we use the refactored data structure `RRGraphBuilder` to shadow the discrete data structure `rr_graph_storage`.
This PR aims to fully refactored/deprecate the direct use of the legacy API `remap_rr_node_switch_indices()` from the `rr_node` data structure.
After this PR, the `remap_rr_node_switch_indices()` from the refactored data structure `RRGraphBuilder` is the only way to use it.
**Checklist:**
**Related Issue**
This pull request is a follow-up PR on the routing resource graph refactoring effort #1805, #1868
**Motivation and Context**
This PR is a continuation of the refactoring effort with a focus on shadowing the `rr_graph_storage` APIs in the `RRGraphBuilder` data structure.
This PR …
> Add a new API remap_rr_node_switch_indices() to RRGraphBuilder

- vpr/src/device/rr_graph_builder.h
- vpr/src/route/rr_graph.cpp
- vpr/src/route/rr_graph_uxsdcxx_serializer.h
**Description**
This PR focuses on updating routing resource graph builder functions, where we use the refactored data structure `RRGraphBuilder` to shadow the discrete data structure `rr_graph_storage`.
This PR aims to fully refactored/deprecate the direct use of the legacy API `init_fan_in()` from the `rr_node` data structure.
After this PR, the `init_fan_in()` from the refactored data structure `RRGraphBuilder` is the only way to use it.
**Checklist:**
**Related Issue**
This pull request is a follow-up PR on the routing resource graph refactoring effort #1805, #1868
**Motivation and Context**
This PR is a continuation of the refactoring effort with a focus on shadowing the `rr_graph_storage` APIs in the `RRGraphBuilder` data structure.
This PR refactored the `init_fan_in()` API among …
> Add a new API init_fan_in() to RRGraphBuilder

- vpr/src/device/rr_graph_builder.h
- vpr/src/route/clock_connection_builders.cpp
- vpr/src/route/clock_network_builders.cpp
- vpr/src/route/rr_graph.cpp
- vpr/src/route/rr_graph_uxsdcxx_serializer.h
- vpr/src/route/rr_node.cpp
- vpr/src/route/rr_node.h
**Description**
This PR focuses on updating routing resource graph builder functions, where we use the refactored data structure `RRGraphBuilder` to shadow the discrete data structure `rr_graph_storage`.
This PR aims to fully refactored/deprecate the direct use of the legacy API `set_node_cost_index()` from the `rr_node` data structure.
After this PR, the `set_cost_index()` API is fully deprecated, and the `set_node_cost_index()` from the refactored data structure `RRGraphBuilder` is the only way to use it.
**Checklist:**
**Related Issue**
This pull request is a follow-up PR on the routing resource graph refactoring effort [#1805](https://github.com/verilog-to-routing/vtr-verilog-to-routing/pull/1805), [#1868](https://github.com/verilog-to-routing/vtr-verilog-to-routing/pull/1868) …
> Add a new API set_node_cost_index() to RRGraphBuilder

- vpr/src/base/read_activity.cpp
The power flow currently prints an info message containing the word "error". This needs to be warning as discussed in the related issue.
Issue #1797 
Removes confusing error message from log files
Minor change. I checked that the message prints as a warning.
> Issue #1797: Change VTR_LOG to VTR_LOG_WARN and remove the string "Error"

- ODIN_II/Makefile
- ODIN_II/regression_test/tools/run_yosys.sh
- ODIN_II/regression_test/tools/synth.tcl
Adding a few handy makefile options for the Yosys+Odin-II synthesizer.
complimentary changes to PR #1798 
Users can use all Odin-II makefile options for Yosys+Odin-II as long as the ``ELABORATOR=YOSYS`` is passed to the make call.
For example:
```
make build ELABORATOR=YOSYS
make debug ELABORATOR=YOSYS
make test ELABORATOR=YOSYS
make regenerate_expectation ELABORATOR=YOSYS
```
**NOTE**: the value of the ``ELABORATOR`` could be ``ODIN`` or ``YOSYS``. By default, the value is considered as ``ODIN`` and the value is not case sensitive. If nothing is passed to the make call, it automatically considers ``ODIN`` as the elaborator.
> Yosys+Odin-II's new  makefile options

- vpr/src/device/rr_graph_view.h
- vpr/src/route/rr_graph.cpp
This fixes two issues with the string description of rr nodes (describe_rr_node)
1. Adds a missing space character.
2. Adds the x,y location for SINK and SOURCE rr nodes.  This was previously missing and it made it difficult to locate a given SOURCE/SINK rr node from an error message (in my case it was failed routing error message that only printed SOURCE and SINK description).
> Small improvements to string description of rr nodes

- utils/fasm/test/test_fasm.cpp
- vpr/src/base/read_route.cpp
- vpr/src/device/rr_graph_view.h
- vpr/src/draw/draw.cpp
- vpr/src/draw/search_bar.cpp
- vpr/src/route/check_route.cpp
- vpr/src/route/check_rr_graph.cpp
- vpr/src/route/clock_connection_builders.cpp
- vpr/src/route/clock_network_builders.cpp
- vpr/src/route/overuse_report.cpp
- vpr/src/route/route_common.cpp
- vpr/src/route/router_lookahead_extended_map.cpp
- vpr/src/route/router_lookahead_map.cpp
- vpr/src/route/router_lookahead_map_utils.cpp
- vpr/src/route/rr_graph.cpp
- vpr/src/route/rr_graph_uxsdcxx_serializer.h
- vpr/src/route/rr_node.h
- vpr/src/route/rr_node_impl.h
- vpr/src/util/vpr_utils.cpp
In this PR, I have implemented `RRGraphView::node_ptc_num()`, `RRGraphView::node_pin_num()`, `RRGraphView::node_class_num()`, `RRGraphView::node_track_num()` throughout VTR. Every time `device_ctx.rr_nodes[node].node_ptc_num()` was called has been replaced with `rr_graph.node_ptc_num(RRNodeId(node))`. The same pattern was followed for the other functions in this PR. In order to do this, I followed a pattern similar to that in the last PR.
These changes are a continuation of the RRGraphView API implementation effort.
I have run the regression tests for `vtr_reg_strong` along with the QoR testing found at `    $ ../scripts/run_vtr_task.py regression_tests/vtr_reg_nightly_test3/vtr_reg_qor_chain`. Results from these QoR tests can be found below. The file containing all results can be found …
> RRGraphView node_ptc_num(), node_pin_num(), node_class_num(), node_track_num() Implementation

- vtr_flow/parse/parse_config/common/vtr_flow.txt
While a new VPR memory usage stat is added to the run_vtr_flow output, the value of VTR elapsed time is no longer read by parse scripts due to a mismatch in the corresponding regex expressions.
> [Infra]: fix missing VTR time in parse_results 

- libs/libarchfpga/src/read_fpga_interchange_arch.cpp
- vpr/test/test_interchange_device.cpp
This PR adds basic support for the architecture reading:
- Device
- Layout
- Switches
This is part of the FPGA Interchange support in VTR
Catch2 testing framework
> libs: arch: interchange: add basic device information

- vpr/src/base/vpr_context.h
- vpr/src/device/rr_graph_view.cpp
- vpr/src/device/rr_graph_view.h
- vpr/src/power/power.cpp
- vpr/src/power/power_sizing.cpp
- vpr/src/route/router_lookahead_extended_map.cpp
- vpr/src/route/rr_graph.cpp
- vpr/src/route/rr_graph_reader.cpp
- vpr/src/route/rr_graph_uxsdcxx_serializer.h
- vpr/src/util/vpr_utils.cpp
In this PR, I am implementing RRGraphView::rr_segments(PRSegmentId Seg_Id ) throughout VTR. Every time device_ctx.rr_segment[Seg_Id] was called has been replaced with rr_graph.rr_segment(Seg_Id). In order to do this, I followed a pattern similar to that in the last PR.
These changes are a continuation of the RRGraphView API implementation effort.
> RRGraphView rr_segments() Implementation

- .gitignore
- vpr/src/device/rr_graph_view.h
- vpr/src/route/rr_graph_util.cpp
In this PR, I have implemented RRGraphView::node_first_edge() throughout VTR. Every time device_ctx.graph.first_edge() was called has been replaced with rr_graph.node_first_edge( RRNodeId (index)). In order to do this, I followed a pattern similar to that in the last PR.
These changes are a continuation of the RRGraphView API implementation effort.
> RRGraphView::node_first_edge() Implementation

- libs/libvqm/vqm_parser.l
- libs/libvqm/vqm_parser.y
- utils/vqm2blif/src/base/vqm2blif_util.h
This PR includes a few minor modifications to the vqm2blif parser.  Small changes have been made to the parser grammar files (vqm_parser.l and vqm_parser.y) in order to achieve the following objectives:
- The synthesis attributes and directives inside (* and *) delimiters should be ignored
- The names that start with \ (called TOKEN_ESCAPEID) should be allowed to be used for declaration of a vector. Currently the name of the vectors can only start with alphabetic characters and _ (TOKEN_REGULARID).
- If a line in the code ends with a TOKEN_ESCAPEID and there is no space between the token and the ; at the end of the line, ; should not be considered part of the TOKEN_ESCAPEID. 
- The ! operator is escaped. Though it should be noted that this results in the lut_mask parameter being incorrect …
> Update the vqm2blif parser to add support for Stratix 10 and Agliex vqm files

- vpr/src/device/rr_graph_view.h
> Updated comments to elaborate configurable/non-configurable edges()

- vtr_flow/parse/parse_config/common/vtr_flow.txt
- vtr_flow/scripts/run_vtr_flow.py
The `run_vtr_flow.py` script gets stuck on calling `get_memory_usage(logfile)` when the logfile does not exist. This PR fixes the bug, in addition to showing the maximum memory of all VTR flow stages instead of only the VPR stage in the final output.
Issue #1949 
If an input file has errors and the VTR front-ends fail, the `run_vtr_task` script gets stuck and the terminal does not come back to the prompt
> fix `run_vtr_task.py` getting stuck if an input has an error

- vpr/src/pack/cluster.cpp
- vpr/src/pack/cluster_util.cpp
- vpr/src/pack/cluster_util.h
The clustering code is doing most of the real packer functionality. It contains an extra-long function (do_clustring) that is more than 470 lines of code. In this PR, several helper functions are introduced to make the clustering code more readable.
The packer code needs a lot of refactoring to be more readable and easier to follow. While this PR didn't completely solve the issue, it is just the first step.
By running vtr_reg_basic and vtr_reg_strong and getting exactly the same earlier results.
> Refactor the Clustering code 

- doc/src/vpr/command_line_usage.rst
- vpr/src/base/SetupVPR.cpp
- vpr/src/base/ShowSetup.cpp
- vpr/src/base/netlist_writer.cpp
- vpr/src/base/netlist_writer.h
- vpr/src/base/read_options.cpp
- vpr/src/base/read_options.h
- vpr/src/base/vpr_api.cpp
- vpr/src/base/vpr_types.h
This PR adds two options:
- post_synth_netlist_unconn_inputs {unconnected, nets, gnd, vcc}
- post_synth_netlist_unconn_outputs {unconnected, nets}
These options can be used to enforce how unconnected ports are treated in Verilog output. They can be tied to vcc, gnd, 1'bX (unconnected) or to a special net named __vpr__unconnXX (XX number is incremented to generate unique net for each port).
https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/1721
Previously unconnected input ports were always tied to 1'b0 and output ports were tied to a common net DummyOut which is incorrect.
These options were tested with **symbiflow-arch-defs**
To reproduce the test, build the vpr end set env variable:
```
make -j `nproc`
export VPR=$PWD/build/vpr/vpr
```
Then, in a different directory, …
> Add unconnected port options for Verilog netlist

- doc/src/vpr/command_line_usage.rst
- doc/src/vpr/file_formats.rst
- vpr/src/analysis/timing_reports.cpp
- vpr/src/base/SetupVPR.cpp
- vpr/src/base/ShowSetup.cpp
- vpr/src/base/ShowSetup.h
- vpr/src/base/read_options.cpp
- vpr/src/base/read_options.h
- vpr/src/base/vpr_api.cpp
- vpr/src/base/vpr_types.h
- vpr/src/place/place.cpp
- vpr/src/timing/timing_util.cpp
- vpr/src/timing/timing_util.h
This PR adds 2 new options:
* `--write_block_usage`
* `--write_timing_summary`
which enable VPR to write two summary files in JSON format.
The first one reports the usage of specific blocks of given architecture for implemented design during packing step in format:
```
{
"num_nets": "<int>",
"num_blocks": "<int>",
"input_pins": "<int>",
"output_pins": "<int>",
"blocks": {
"<block_type_name_0>": <int>,
"<block_type_name_1>": <int>,
...
"<block_type_name_n>": <int>
}
}
```
Second option writes final timing summary for the design evaluated in routing step. It consist of Critical Path Delay (cpd), Max Circuit Frequency (Fmax), setup Worst Negative Slack (sWNS), setup Total Negative Slack (sTNS). The format is as follows:
```
{
"cpd": <double>,
"fmax": <double>,
"swns": <double>,
"stns": …
```
> VPR: Add options for writing machine readable summary files

- .github/kokoro/steps/hostsetup.sh
Signed-off-by: Pawel Czarnecki <pczarnecki@antmicro.com>
I see that kokoro fails in recent CI runs with:
```
++ pyenv install -f 3.6.3
Downloading Python-3.6.3.tar.xz...
-> https://www.python.org/ftp/python/3.6.3/Python-3.6.3.tar.xz
Installing Python-3.6.3...
Installed Python-3.6.3 to /home/kbuilder/.pyenv/versions/3.6.3
++ pyenv global 3.6.3
++ curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 2548k  100 2548k    0     0  18.8M      0 --:--:-- --:--:-- --:--:-- 18.8M
++ python3 get-pip.py
ERROR: This script does not work on Python 3.6 The minimum supported Python version is 3.7. …
```
> CI: fix kokoro failures

- vpr/src/base/vpr_context.h
- vpr/src/device/rr_graph_builder.cpp
- vpr/src/device/rr_graph_builder.h
- vpr/src/device/rr_graph_view.cpp
- vpr/src/device/rr_graph_view.h
- vpr/src/route/rr_graph.cpp
- vpr/src/route/rr_graph_reader.cpp
- vpr/src/route/rr_graph_writer.cpp
- vpr/src/route/rr_metadata.cpp
- vpr/test/test_vpr.cpp
In this PR the owner of data structures  rr_node_metadata/rr_edge_metadata has been changed from device_ctx to rr_graph_builder. 
The metadata is an internal data structure used in rr_graph_builder so it should be part of this class 
These changes are continuation of reorder_nodes function location change
> Data structure rr_node_metadata/rr_edge_metadata owner change

- doc/src/tutorials/arch/classic_soft_logic.rst
- doc/src/tutorials/arch/configurable_memory.rst
- doc/src/tutorials/arch/configurable_memory_bus.rst
- doc/src/tutorials/arch/fracturable_multiplier.rst
- doc/src/tutorials/arch/fracturable_multiplier_bus.rst
Deleted "gridlocations" xml tags in pb_type xml examples throughout the architecture tutorials, as well as one sentence explaining the meaning of the gridlocations tag in the tutorial text.
The "gridlocations" xml tag is no longer supported and has already been removed from the documentation (other than these tutorials).
It hasn't been.  It is low risk since the change only impacts the documentation.
- [x ] My change requires a change to the documentation
- [ x] I have updated the documentation accordingly
> removed deprecated gridlocations xml tag from arch tutorials

- doc/src/index.rst
This is just a typo in the first sentence of the docs.
> doc/index: typo

- doc/src/conf.py
The year shown at the footer of the docs is `2016`. This PR updates it to `2012-2022`. @vaughnbetz what should be the proper starting year?
*None*
The docs have been updated since 2016...
It's changing the content of a hardcoded string. There is no functionality change at all. It's tested in CI.
> doc: update copyright year

- .github/scripts/hostsetup.sh
- .github/scripts/run-vtr.sh
- .github/scripts/vtr-build.sh
- .github/scripts/vtr-full-setup.sh
- .github/scripts/vtr-test.sh
- .github/workflows/large-tests.yml
- CMakeLists.txt
- libs/librrgraph/CMakeLists.txt
This PR moves the infrastructure from Kokoro to GH actions to run large tests on GH custom runners
https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/1965
> ci: transition to GH custom runners for nightly builds

- Dockerfile
Fixed broken Dockerfile script located at the project root.
- The target image is now based on Ubuntu 20:04 LTS
- Build packages are now extracted from install_apt_packages.sh & requirements.txt files in VTR root
- Image build process is now in accordance with the latest build instructions available in VTR documenation.
https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/1756
As an option for building VTR, there is a docker container build script. VTR's fixed Dockerfile allows it to be built on different OSs and architectures effortlessly, by just running one command. This can especially be useful for building VTR on devices with Apple Silicon processors which currently lack native Linux support but support Linux-based docker containers.
The fixed Dockerfile script now …
> Fixed root Dockerfile for building vtr container

- doc/requirements.txt
- doc/src/conf.py
Some of the tweaks in the docs requirements file seem to be outdated.
*None*.
The "section captions" in the sidebar are shown incorrectly. I think that's because docutils and sphinx pinned to old versions. This PR unpins them.
See https://vtr--1982.org.readthedocs.build/en/1982/.
> doc/requirements: update

- .github/workflows/containers.yml
As discussed in #1970, this PR adds a CI workflow to test building the Dockerfile, and to push it to ghcr.io.
- #1970
Test when the Dockerfile breaks.
It's CI, so self-tested.
> ci: add GitHub Actions workflow 'Containers'

- doc/src/z_references.bib
Points "On Biased and Non-Uniform Global Routing Architectures and CAD Tools for FPGAs" to https://www.eecg.utoronto.ca/~vaughn/papers/techrep.pdf -- a known working link of the paper referenced. Resolving https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/1967
Fixing `z_references.bib` link.
https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/1967
Broken link. 
Tested with a known-good link. No impact to code base. 
This is documentation bug fix. No checklist items below apply.
> Fix `Global Routing` tech report link

- .github/workflows/large-tests.yml
With the new GH custom runners, CI for large tests cannot run on forks, as the custom runners are not deployed for usage outside of the scope of the `verilog-to-routing` org. This prevents the workflow from failing due to unavailable runners.
> gha: prevent from running large tests on forks

- ODIN_II/Makefile
When trying to build the test target with the ODIN's Makefile, encountered a syntax error which I fixed.
I have made the same edit on two lines of the Makefile.
It resoves the error when trying to make the test target.
The "make test" command now works and starts the benchmarks.
> Fixed small syntax errors in ODIN's Makefile test target.

- vpr/src/pack/attraction_groups.cpp
- vpr/src/pack/attraction_groups.h
- vpr/src/pack/cluster.cpp
- vpr/src/pack/output_clustering.cpp
- vpr/src/pack/pack.cpp
- vpr/src/place/centroid_move_generator.cpp
- vpr/src/place/critical_uniform_move_generator.cpp
- vpr/src/place/feasible_region_move_generator.cpp
- vpr/src/place/median_move_generator.cpp
- vpr/src/place/move_utils.cpp
- vpr/src/place/move_utils.h
- vpr/src/place/uniform_move_generator.cpp
- vpr/src/place/weighted_centroid_move_generator.cpp
- vpr/src/place/weighted_median_move_generator.cpp
During place moves, if a cluster is constrained, we do an additional step of intersecting the cluster's move range limit with its floorplan constraint before we create a move.
Related to adding floorplan constraints to VPR - issue #932
When running with floorplan constraints, placement time was increasing due to an increased number of aborted moves. This increase was a result of moves being created that moved the block out of its floorplan constraints. By adjusting the range limit, we reduce the number of moves that are illegal with respect to floorplanning and so the place time decreases. Although the place time still increases relative to running with no constraints, the increase is minimized.
The reduction in place time on different titan circuits that were run with floorplan …
> Optimize floorplan checks during place moves

- libs/EXTERNAL/CMakeLists.txt
added flags to ignore warnings when compiling unit tests that use the catch2 framework
VTR currently uses the catch2 framework for unit tests. But compiling any project with the catch2 framework causes warnings to appear that are within the catch2 project. This PR removes the warnings due to the catch2 framework so they do not appear during compilation.
The "-w" flag has been added to all unit test projects so that any warnings related to the catch2 framework are ignored.
This PR is related to issue 1935.
It is preferred to have a warning free build.
This has been tested by compiling VTR locally and verifying that all the warnings related to the catch2 framework do not appear.
> added flags to ignore warnings when compiling unit tests that use the catch2 framework

- ODIN_II/SRC/YYosys.cpp
A minor change to the Yosys synthesis script to make it more configurable for the Yosys+Odin-II synthesizer.  
Now, users can specify `(* nomem2reg/mem2reg = 1/0 *)` before a reg declaration in a Verilog file to specify whether it should be an array of registers or a memory hard block.
make test and VTR regression tests
> Removing "-nomem2reg" for input Verilog circuits in Yosys+Odin-II

- libs/libvtrutil/src/vtr_ndmatrix.h
There is a [change in llvm](https://github.com/verilog-to-routing/vtr-verilog-to-routing.git) that soon won't automatically
surface symbols from a transitive include of `<algorithm>`, so we need to make sure to IWYU.
> Add missing include for <algorithm>.

- doc/src/vpr/file_formats.rst
- vpr/src/base/netlist_writer.cpp
- vpr/src/base/read_blif.cpp
- vpr/src/base/read_blif.h
- vtr_flow/benchmarks/tests/test_eblif.eblif
A proposed solution to https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/1662
- Updated EBLIF cell parameter specification
- Added EBLIF parameter value validation on reading
- Added binary prefix to relevant parameters in post-routing Verilog netlist writing.
> EBLIF cell parameter interpretation

- ODIN_II/SRC/BLIFReader.cpp
- ODIN_II/SRC/hard_blocks.cpp
Follow up on PR #1953 
Hardblocks, used by Yosys elaborator, are flaged to print their .model in the final BLIF file
> Speciy used hardblocks to print their model in the blif generation phase

- ODIN_II/SRC/BLIFElaborate.cpp
- ODIN_II/SRC/include/multipliers.h
- ODIN_II/SRC/multipliers.cpp
Removing pins extension of the multipliers output ports, that were connected to PAD node, and extending the output port using new pins to avoid unconnected wires in the output BLIF (which is resulting in ABC segfault). 
NOTE: the new output pins are removed at the end of Odin-II execution since their nets do not have any fanouts. While PAD pins remained in the output netlist in the previous version
fix issue #2007
> [Yosys+Odin]: creating extra pins to extend the mult output port

- ODIN_II/SRC/partial_map.cpp
I found 3 unused if statements in ODIN's partial_map.cpp which they were never executed and removed them from the source.
> Removed 3 unused if conditions from ODIN's partial_map.cpp.

- vpr/src/draw/draw.cpp
- vpr/src/draw/search_bar.cpp
1) Added a missing line of code to the NO_PICTURE_TO_ROUTING version of the initial setup function to set a default search option
2) Added a check to ensure a type was selected, and create a warning dialog window if one was not selected. 
When opening vpr graphics, no initial search type is selected. Any attempts to search with no search type selected will crash the program. This fix aims to rectify that.
Searches with all different search settings were attempted before and after the change, and produced identical results. It no longer crashes the program, and it now opens with a default search type selected.
- [ X] Bug fix (change which fixes an issue)
> (Bug-Fix) No default search type

- .gitignore
- libs/libarchfpga/src/arch_util.cpp
- libs/libarchfpga/src/read_xml_arch_file.cpp
1- .gitignore file is changed to accommodate the files generated by Clion IDE.
2- Other than the pb_types defined in xml file, another level of pb_type is added to the structure if the pb_type in the XML file uses a [class](https://docs.verilogtorouting.org/en/latest/arch/reference/#classes).
Normal pb_types are initialized in "ProcessPb_Type" function in "libs/libarchfpga/src/read_xml_arch_file.cpp". However, the newly added pb_types are initialized in "alloc_and_load_default_child_for_pb_type" in "libs/libarchfpga/src/arch_util.cpp". Since they are initialized in two different functions, some pb_type members are missed in the second function.
3- Three members of t_physical_tile_type are not initialized properly. Each tile consists of, potentially, several types of sub_tiles. Each …
> Pb graph bug fixes

- vpr/main.ui
- vpr/src/draw/draw.cpp
- vpr/src/draw/search_bar.cpp
- vpr/src/draw/search_bar.h
Added an auto-complete function for Block Names in VPR. Search bar still only searches on clicking search button, so selection of an option from auto-complete menu only fills it into the search bar. Should still be quite helpful considering how long some of the names get. 
Uses GtkListStore to store objects and GtkEntryCompletion to display/auto-complete the different entries. Added two helper functions:
**search_type_changed**: Manages auto-completion models based on search type. Currently sets model to null unless selected type is block name
**load_block_names**: Stores block names in listStore that is set as completion model when appropriate
Also added a few comments on last pull request, where a default search option was set. 
This was tested on some of the larger circuits (mcml.v and …
> Added Auto-Complete Functionality for Block Names (VPR)

- doc/src/arch/reference.rst
This PR is a minor documentation update that adds information on the new features created by PR #1836 (the ability to specify details for x and y channels separately).
This PR will resolve #2023.
> Added documentation details for specifying separate x and y channel 

- vpr/src/draw/buttons.cpp
- vpr/src/draw/draw.cpp
- vpr/src/draw/draw_debug.cpp
PR that solves Issue #2040. VPR Graphics no longer crash when invalid input is entered.
- [X ] Bug fix (change which fixes an issue)
> VPR Graphics Crash Fixed

- doc/src/vpr/placement_constraints.rst
Added a documentation page to describe how a user can run VPR with placement constraints.
Related to the features add for issue #932.
> Document VPR placement constraints

- doc/src/api/vpr/index.rst
- doc/src/api/vpr/mapping.rst
In this PR, I am adding some documentation under VPR API section of the docs to explain how we can map between the atom and clustered netlists.
- [x ] I have updated the documentation accordingly
> Adding documentation for the mapping between atom and clustered netlist

- vpr/src/place/analytic_placer.cpp
- vpr/src/place/cut_spreader.cpp
- vpr/src/place/initial_placement.cpp
- vpr/src/place/place_util.cpp
- vpr/src/place/place_util.h
The analytical placement approach used to fail in some large titan benchmarks due to some logical bugs. The bugs have been resolved in this branch.
Function update_macros did not check whether macro can be placed with the current head position. Hence, in some cases, blk_locs for some macro members remained -1 until the end of the flow and produced an error at the end. 
Some assertions were removed since they were not logically correct, and some extra conditions were added in Cut_Spreader.cpp file to avoid producing errors in large designs. 
@vaughnbetz
> analytical placement's bugs are fixed

- doc/src/vpr/command_line_usage.rst
- vpr/src/base/read_options.cpp
Documentation for running graphics commands was made more clear. 
Running any graphics command examples from the documentation, such as sample command `$VTR_ROOT/vpr/vpr $VTR_ROOT/vtr_flow/arch/timing/EArch.xml $VTR_ROOT/vtr_flow/benchmarks/blif/tseng.blif --route_chan_width 100 --analysis --save_graphics on --graphics_commands save_graphics place.png`, did not work. The documentation neglected to mention that graphics commands must be surrounded by quotation marks, as argparse considers space filled strings as multiple arguments even if the user intended it to be just one. 
A fix to Issue #2001. 
Ran
`$VTR_ROOT/vpr/vpr $VTR_ROOT/vtr_flow/arch/timing/EArch.xml $VTR_ROOT/vtr_flow/benchmarks/blif/tseng.blif --route_chan_width 100 --analysis --save_graphics on --graphics_commands …
> Graphics Command Documentation Updated

- .github/scripts/hostsetup.sh
The issue seems to be related to outdated python pip or setuptools on google servers that run the CI tests. I have added a command to update pip before installing python packages.
https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/2072
It will resolve failures in CI tests
> Fixed CI tests fail due to failure in installing required python packages

- doc/src/vpr/index.rst
- doc/src/vpr/placement_constraints.rst
Indentation for documentation for https://docs.verilogtorouting.org/en/latest/vpr/placement_constraints/?highlight=floorplanning fixed. 
xml example on the page wasn't showing up properly:
Indented a code block to match that of working xml example (specifically, https://github.com/verilog-to-routing/vtr-verilog-to-routing/edit/master/doc/src/vpr/file_formats.rst#routing-resource-graph-format-example)
Mentioned in #2079 .
> Placement constraints docs update

- ODIN_II/SRC/enum_str.cpp
- ODIN_II/SRC/include/odin_types.h
- ODIN_II/SRC/netlist_statistic.cpp
This PR is enhances printing the synthesis statistics at the end of Odin.
Added a case for printing used and unused top IO nodes separately in netlist_statistic.cpp.
https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/2090
Currently the printed statistics at the end of synthesis stage only shows number of used top IO nodes. It's more convenient to print number of used and unused nodes since we don't delete unconnected IO nodes in Odin.
> Odin detailed report num of nodes

- ODIN_II/SRC/BLIFReader.cpp
- ODIN_II/SRC/include/config_t.h
- ODIN_II/SRC/include/odin_types.h
- ODIN_II/SRC/odin_ii.cpp
- doc/src/yosys+odin/user_guide.rst
- libs/EXTERNAL/CMakeLists.txt
- vtr_flow/scripts/python_libs/vtr/odin/odin.py
- vtr_flow/scripts/run_vtr_flow.py
- vtr_flow/tasks/regression_tests/vtr_reg_basic/hdl_include_odin/config/config.txt
- vtr_flow/tasks/regression_tests/vtr_reg_basic/hdl_include_yosys/config/config.txt
- vtr_flow/tasks/regression_tests/vtr_reg_basic/hdl_include_yosys_odin/config/config.txt
As Yosys generates a coarse-grained BLIF file for Odin-II partial mapper, all BLIF components were interpreted as black boxes at the beginning of Odin-II partial mapping. Therefore, node names were generated based on the type of each subcircuit, which was a unique name and did not include hierarchical information about modules/submodules. This PR extracts the hierarchical information related to each node from the name of its output signals and then sets the node(and its nets) name(s) based on the operation type of each node and the hierarchical information.
P.S: the similar approach is taken in Odin-II, which makes the readability of netlists better and eases the tracking of the critical path in the final VTR timing analysis.
> Node naming, including hierarchical history in Yosys+Odin-II 

- .github/workflows/test.yml
Since GCC 5 and 6 were removed from the CI workflow 'test', a field in job Compatibility is not used anymore.
- https://github.com/verilog-to-routing/vtr-verilog-to-routing/commit/eb6f4b9ea234f7f5a20cea24608362c8ece4886b
It's a cleanup. Instead of an empty ` BUILD_TYPE`, it's set to `release`.
It's a change in CI, so self tested.
> ci/test: remove unused matrix field

- vpr/src/route/route_tree_timing.cpp
- vpr/src/route/route_tree_timing.h
This PR is created to address the [issue #2078](https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/2078)
@vaughnbetz
> Issue #2078

- vtr_flow/scripts/qor_compare.py
Fix to Issue #2107. Changed the seperator between QoR metrics in parse_results.txt files to be '\t  ' instead of '\t' so users don't have to change the parse_results.txt files in order to run the comparison script, QoR_compare.py.
> Changed sep to be '\t  ' in QoR comparison script

- vpr/main.ui
- vpr/src/draw/buttons.cpp
- vpr/src/draw/buttons.h
- vpr/src/draw/draw.cpp
- vpr/src/draw/draw_toggle_functions.cpp
- vpr/src/draw/draw_toggle_functions.h
- vpr/src/draw/draw_types.h
- vpr/src/draw/search_bar.cpp
- vpr/src/draw/search_bar.h
- vpr/src/draw/ui_setup.cpp
- vpr/src/draw/ui_setup.h
**Search **
Updated search functionality to include Block and Net Name suggestions/autocomplete, toggleable by hitting the "Enter" or "Return" key.  
Additionally, switched search to include Cluster and Atom netlist for Blocks, and the Atom netlist for nets (Cluster netlist is a subset of atom). The autosuggest algorithm/set up is meant to only run once when you hit enter, so you may need to rehit the key to reactivate it. Upon hitting enter, the program will search through all of the names and display all of the names that **contain** the given substring. This is obviously a large operation, and will take a bit of time. 
Furthermore, searching a subblock now highlights the block if it is visible at the current zoom lvl, and if not, highlights the containing cluster block. Additionally, a …
> Search Update + NoC GUI Update

- doc/src/vpr/placement_constraints.rst
This fixes a couple of mistakes in the VPR Placement Constraints documentation - the example constraints XML is now valid and accepted by VPR, and the `--read_vpr_constraints` option is formatted as as a VPR option, whereas before an erroneous space led to unintended characters appearing.
#2111 
The example XML in the docs previously caused VPR to fail - if you're used to XML the cause is pretty obvious but otherwise it might cause a bit of confusion, so hopefully this can avoid that. 
The docs successfully build, and the HTML page renders as it should.
> Fix mistakes in VPR Placement Constraints documentation

- ODIN_II/SRC/VerilogWriter.cpp
The generated Verilog file by Odin-II, including the black box declaration of complex blocks for the Yosys elaborator, has the upper limit of the ports in wrong values. The upper limit was considered as the size of the port while it should have been decremented by 1.
Fix issue related to the number of DSP blocks in `gemm_layer.v`, part of the new Koios++ benchmark suite
> Aman:
>> I was looking at the difference in resource usage when running benchmarks through ODIN-only flow and ODIN+Yosys flow.
>> In a couple cases, I see that both synthesis tools produced the same number of multipliers, but VPR packed them differently. For example, in the gemm_layer design, there are 400 multipliers (I think these are 8-bit multipliers). In one …
> Fix dsp models port sizes in the Verilog file generated by Odin-II

- vtr_flow/scripts/qor_compare.py
See Issue #2107.
Different computers interpret parse_results.txt files differently in the number of spaces they add before/after every data entry. To address this, this PR fixes the initial correction to this problem (see PR #2108 ) by ignoring any whitespace after the delimitter.
> Fix to QoR Comparison Script

- vpr/src/pack/re_cluster_util.cpp
- vpr/src/place/initial_placement.cpp
- vpr/src/place/initial_placement.h
Initial placement used to fail in case of high utilization or long chains. New approach called dense_placement has been added to initial placement, make it possible to redo initial placement if random placement could not find a legal solution for high utilization designs.
Relate issue : [https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/2036#issuecomment-1184739027](Initial Placement issue)
List of Design that passing now:
- Brainwave
- tpu_like.small.os
- tpu_like.small.ws
- tpu_like.medium.os
- tpu_like.medium.ws
- dla_like.large
@MohamedElgammal @vaughnbetz
> Dense initial placement

- .gitignore
- doc/src/yosys+odin/dev_guide/contributing.rst
- doc/src/yosys/dev_guide.rst
- libs/EXTERNAL/libyosys/CMakeLists.txt
- libs/libarchfpga/CMakeLists.txt
- libs/libarchfpga/src/main.cpp
- libs/libarchfpga/src/write_arch_bb.cpp
- libs/libarchfpga/src/write_models_bb.cpp
- libs/libarchfpga/src/write_models_bb.h
- vtr_flow/misc/yosyslib/synthesis.tcl
- vtr_flow/scripts/python_libs/vtr/paths.py
- vtr_flow/scripts/python_libs/vtr/yosys/yosys.py
This PR adds an ability to `libarchfpga` to generate a file that includes the declaration of non-vtr-primitive complex blocks (complex blocks that are defined by users, not adder, dual_port_ram, ...) in the Verilog format.
With such a file, the Yosys standalone frontend can synthesize user-defined complex blocks as black boxes since it is provided with Verilog declarations of them.
Syntax to use `write_arch_bb`:
```
-----------------------------------------------------------------------------------------------------------------------
write_arch_bb - Read a VPR architecture file and output a Verilog file including the declaration of models as black boxes
Usage: write_arch_bb <arch_file.xml> <output_file>
ex: write_arch_bb k4_n10.xml dsp_bb.v
Read timing-driven architecture k4_n10.xml and …
```
> Providing Yosys Frontend with the Declaration of Custom Complex Blocks

- vpr/src/draw/draw.cpp
- vpr/src/draw/ui_setup.cpp
There was a bug where as you proceeded through placement and routing of a circuit, the UI options/buttons available would not update to reflect the new state of vpr. This was caused by two things:
1. In the new initial setup functions, a guard if statement was placed that would return if a new window was not being created, which worked in the old nested format, but now that we are not nesting initial setup functions, we need to instead check if it is a new window, and only run the default_setup function if it is new. 
2. When hiding menu options, we were using gtk_widget_hide, but were not using gtk_widget_show when showing menu options.
These bugs have been fixed in this PR.
> Fixed Bug where VPR UI was not changing when switching mode

- ODIN_II/Makefile
- ODIN_II/SRC/enum_str.cpp
- ODIN_II/SRC/odin_util.cpp
- ODIN_II/regression_test/tools/run_yosys.sh
- ODIN_II/verify_odin.sh
- libs/EXTERNAL/CMakeLists.txt
- vtr_flow/scripts/python_libs/vtr/__init__.py
- vtr_flow/scripts/python_libs/vtr/odin/odin.py
- vtr_flow/scripts/python_libs/vtr/yosys/__init__.py
- vtr_flow/scripts/python_libs/vtr/yosys/yosys.py
- vtr_flow/scripts/run_vtr_flow.py
- vtr_flow/tasks/regression_tests/vtr_reg_yosys_odin/FX68K/config/config.txt
- vtr_flow/tasks/regression_tests/vtr_reg_yosys_odin/f4pga_button_controller/config/config.txt
- vtr_flow/tasks/regression_tests/vtr_reg_yosys_odin/f4pga_pulse_width_led/config/config.txt
- vtr_flow/tasks/regression_tests/vtr_reg_yosys_odin/f4pga_timer/config/config.txt
- vtr_flow/tasks/regression_tests/vtr_reg_yosys_odin/hdmi/config/config.txt
This PR fixes the UHDM file extension inference bug for the Yosys+Odin-II front-end.
After this PR,  Both Yosys and Yosys+Odin-II front-ends require the `-parser` option given to the `run_vtr_flow` script to specify the Yosys parser explicitly.
> fix a UHDM parser bug for the Yosys+Odin-II front-end

- ODIN_II/Makefile
- ODIN_II/SRC/BLIFElaborate.cpp
- ODIN_II/SRC/BLIFReader.cpp
- ODIN_II/SRC/BitwiseOps.cpp
- ODIN_II/SRC/include/BitwiseOps.hpp
This PR provides the utility for reduce operations generated in Yosys coarse-grained BLIF file to decode them into nodes with 2 input signals and 1 output signal.
An internal issue raised by the Koios++ development team
> Decoding BitwiseOps in Yosys+Odin-II

- vpr/src/route/rr_graph.cpp
This PR is created to fix issue #2145
@vaughnbetz
> Fix rr_graph direct link

- doc/src/vpr/command_line_usage.rst
One of placement command line options was not documented, and one of the default values was incorrect in existing document.
[https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/2125]
> Placement command line options is updated in documentation

- ODIN_II/SRC/include/odin_error.h
- ODIN_II/SRC/include/odin_util.h
- ODIN_II/SRC/odin_ii.cpp
- ODIN_II/SRC/odin_util.cpp
This PR removes the input file extension checking function in Yosys+Odin-II as checking the file extension is not required, and such a process is not performed by Yosys and UHDM parsers. So, Yosys+Odin-II only decides the parser based on the user request, not the file extension.
Issue reported by @aman26kbm 
An email thread:
> Hi Seyed,
> There is a problem with the .sv files in the master branch. It used to work earlier (maybe a month back). Did the UHDM related checkin mess it up?
> In the recent PR where you were upgrading Yosys+ODIN flow, you had fixed it with [this](https://github.com/verilog-to-routing/vtr-verilog-to-routing/pull/2148/commits/699ea98642f6bbf57545a646c737980d166d7542) commit. I think just this commit should be extracted into a separate PR. I'm thinking of merging …
> Fixing a bug in receiving .sv extensions without Yosys plugins installed

- doc/src/dev/tutorials/edit_vpr_ui.rst
Adding a link to the EZGL documentation in the VPR UI editing tutorial in VTR Docs
> Add link to EZGL Documentation in VPR docs

- .github/workflows/test.yml
- CMakeLists.txt
- Makefile
- vpr/src/base/read_circuit.cpp
- vpr/src/place/initial_placement.cpp
- vpr/src/place/place.cpp
- vpr/src/place/timing_place_lookup.cpp
This PR contains some general fixes
The PR fixes build errors when `VERBOSE` is defined. It also fixes VPR ignoring netlist verbosity commandline option.
The need for debugging
Locally, and hopefully in the CI
> Fix build errors with VERBOSE

- vpr/src/place/place.cpp
Wirelength estimation after placement was removed from vpr report.
> Wirelength Estimation is printed after placement

- vpr/src/place/simpleRL_move_generator.cpp
The compiler warns about this with
"moving a temporary object prevents copy elision"
(if -Wpessimizing-move is enabled)
Signed-off-by: Henner Zeller <hzeller@google.com>
> Remove unnecessary std::move of temporary object.

- README.developers.md
As vtr_nightly_test1 contains some symbiflow tests, we need to get_symbiflow_benchmarks to be able to run it. This is not included in the docs. Only titan and ISPD benchmarks are listed. In this PR, I have added the instruction of getting symbiflow benchmarks to the running tests section of the docs
> Add missing instruction to run tests to the documentation

- libs/EXTERNAL/libpugixml/CMakeLists.txt
- libs/libarchfpga/CMakeLists.txt
- libs/liblog/CMakeLists.txt
- libs/libpugiutil/CMakeLists.txt
- libs/librtlnumber/CMakeLists.txt
- libs/libvtrutil/CMakeLists.txt
This PR provides minor modifications to the cmake build file of the following libraries to install their header files alongside their binaries:
- libarchfpga
- liblog
- libpugixml
- libpugiutil
- libvtrutil
- librtlnumber
#2218
To reuse the compiled binaries of the libraries outside of the VTR scope in other projects.
the library headers are installed to the `CMAKE_INSTALL_INCLUDEDIR` after running the `make install` command.
> install `LIB_HEADERS` to `CMAKE_INSTALL_INCLUDEDIR`

- vpr/src/base/vpr_constraints_writer.cpp
- vpr/src/pack/cluster_util.cpp
- vpr/src/pack/cluster_util.h
- vpr/src/pack/pack.cpp
- vpr/src/pack/re_cluster_util.cpp
- vpr/src/place/place_constraints.cpp
In this PR, I am using the atom-cluster lookup in the context everywhere in the flow instead of rebuilding a lookup every time we need it. I am also changing all the queries to use the cluster_to_atoms function. The lookup is not built first time itis queried.
> Fix atom lookup

- vpr/src/place/simpleRL_move_generator.cpp
- vpr/src/route/clock_connection_builders.cpp
A few small edits to allow building with -std=c++17
- std::bind was removed from c++17, as seen here: https://en.cppreference.com/w/cpp/utility/functional/bind12
- std::random_shuffle was removed from c++17, https://en.cppreference.com/w/cpp/algorithm/random_shuffle
- Replaced code with modern equivalents.
https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/2202
vpr is being considered as a benchmark for the next SPEC CPU benchmark suite. We discovered this issue as part of that vetting process. Thus we are feeding back the changeset here.
I tested a handful of commandlines before and after the change, and there was no change in the output.
> vpr: changes to conform to c++17 standard

- vpr/src/base/gen/vpr_constraints_uxsdcxx.h
- vpr/src/base/gen/vpr_constraints_uxsdcxx_interface.h
- vpr/src/base/route_constraint.cpp
- vpr/src/base/route_constraint.h
- vpr/src/base/vpr_api.cpp
- vpr/src/base/vpr_constraints.cpp
- vpr/src/base/vpr_constraints.h
- vpr/src/base/vpr_constraints.xsd
- vpr/src/base/vpr_constraints_reader.cpp
- vpr/src/base/vpr_constraints_reader.h
- vpr/src/base/vpr_constraints_serializer.h
- vpr/src/base/vpr_constraints_writer.cpp
- vpr/src/base/vpr_constraints_writer.h
- vpr/src/base/vpr_context.h
- vpr/src/util/vpr_utils.cpp
- vpr/src/util/vpr_utils.h
- Allow router to route or skip specific signals.
- Currently, VPR ignores or routes a global signal through clock modeling options; it does not allow a specific signal to be treated seperately as desired. See details in #2235 
- Allow route constraints applied to specific signals.
> Route constraint for local clock and reset.

- vtr_flow/arch/xilinx/simple-7series.xml
Adds a simple implementation of the BRAM memory block to  the `simple-7series.xml` architecture file, as described in Xilinx documentation.
Currently implemented features:  
Future features:
> Add basic BRAM

- vpr/src/place/move_utils.h
- vpr/src/place/simpleRL_move_generator.cpp
RL agent move generator had an order dependency with e_move_type data structure defined in the "moves_util.h" file. The previous code uses the enum structure as an index of an array to access different move generators. However, the order of enum variables and avail_moves (defined in the "simpleRL_move_generator.cpp" file) array were different.
Hence, placement output for centroid and weighted centroid move was inaccurate. This change expects no performance change but removes the order dependency between these structures.
Also, the centroid move in e_move_type should be the third option (it is used to be the fourth) since if the placement algorithm is not timing, it is only used three first moves (Uniform, Median, Centroid). Having the weighted centroid move as the third move type in the …
> RLplace move mismatch

- cmake/modules/AutoClangFormat.cmake
- libs/librtlnumber/src/include/internal_bits.hpp
- libs/librtlnumber/src/rtl_int.cpp
- libs/libvtrutil/src/vtr_geometry.h
- libs/libvtrutil/src/vtr_pair_util.h
- libs/libvtrutil/src/vtr_strong_id.h
- odin_ii/src/core/adders.cpp
- odin_ii/src/simulate/simulate_blif.cpp
- odin_ii/src/utils/atomic_buffer.h
- vpr/src/power/power_sizing.cpp
- vpr/src/util/vpr_utils.cpp
Run 
```
make format-cpp
```
to format all the C++ codes using clang-format-14. 
To resolve the issue #2268 
As stated in #2268 already, clang-format-14 (used in Ubuntu 22.04) apply code formatting in a slight different way than clang-format-7 (used in Ubuntu 18.04)
> Cpp format Fix-up

- .github/scripts/install_dependencies.sh
Update libtbb setting to libtbb-dev in build dependency.
Update libtbb setting to libtbb-dev in build dependency.
Issue: https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/2269
We are seeing parallel timing analysis is not activated in Ubuntu 22.04 CI test, because the libtbb is not set properly. This change is grab it back.
CI Test.
> check libtbb-dev.

- vtr_flow/scripts/python_libs/vtr/task.py
- vtr_flow/tasks/regression_tests/vtr_reg_nightly_test5/vpr_noc_nearest_neighbor_topology/config/config.txt
There is a typo in the following file: `vtr_flow/tasks/regression_tests/vtr_reg_nightly_test5/vpr_noc_nearest_neighbor_topology/config/config.txt`. Specifically, when a NoC traffic flow file is specified, the suffix of the file (".flows") should also be included in the filename.
@vaughnbetz
> Fix a Typo in NoC Config File

- CMakeLists.txt
- ace2/CMakeLists.txt
- blifexplorer/CMakeLists.txt
- doc/src/parmys/quickstart.rst
- libs/EXTERNAL/libargparse/CMakeLists.txt
- libs/EXTERNAL/libblifparse/CMakeLists.txt
- libs/EXTERNAL/libpugixml/CMakeLists.txt
- libs/EXTERNAL/libsdcparse/CMakeLists.txt
- libs/EXTERNAL/libtatum/CMakeLists.txt
- libs/libarchfpga/CMakeLists.txt
- libs/liblog/CMakeLists.txt
- libs/libpugiutil/CMakeLists.txt
- libs/librrgraph/CMakeLists.txt
- libs/librtlnumber/CMakeLists.txt
- libs/libvqm/CMakeLists.txt
- libs/libvtrutil/CMakeLists.txt
- odin_ii/CMakeLists.txt
- parmys/CMakeLists.txt
- utils/fasm/CMakeLists.txt
- utils/route_diag/CMakeLists.txt
- utils/vqm2blif/CMakeLists.txt
- vpr/CMakeLists.txt
- yosys/CMakeLists.txt
This PR solves the [issue](https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/2271) . We need CMake version higher than 3.16 to be able to build the current master branach. Hence, I have updated the required version in all our CMakeLists.txt files in the repository and Documentation from 3.9 to 3.16 as a minimum version.
[Issue 2271](https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/2271)
> Update CMake version in "CMakeLists.txt" files

- vpr/src/base/echo_files.cpp
- vpr/src/draw/draw.cpp
- vpr/src/pack/pb_type_graph.cpp
- vpr/src/place/place_macro.cpp
- vpr/src/power/power_components.cpp
- vpr/src/power/power_sizing.cpp
- vpr/src/route/route_timing.cpp
- vpr/src/route/rr_graph.cpp
- vpr/src/route/rr_graph_area.cpp
- vpr/src/route/rr_graph_timing_params.cpp
- vpr/src/util/vpr_utils.cpp
> Make delete calls not look like function calls.

- vpr/src/place/RL_agent_util.cpp
- vpr/src/place/noc_place_utils.cpp
- vpr/src/place/noc_place_utils.h
- vpr/src/place/place.cpp
After combining RLPlace 2.0 and NoC placement, details about placement statistics (which block has been moved, how many moves were accepted/rejected, ..) was printed twice for NoCs. Since RLPlace 2.0 code was general and contained all block types, I have removed noc code related to printing information about moves to avoid duplication. 
In addition to that, we needed block type information regardless of using RL agent as placement algorithm. Hence, I have moved the block type extraction function to execute regardless of the placer algorithm, so we can have information printed even if we are using StaticMoveGenerator. 
@vaughnbetz
> Placement move type and block type print information

- vtr_flow/scripts/python_libs/vtr/vpr/vpr.py
- vtr_flow/scripts/run_vtr_flow.py
This pull request updates the behavior of the "run_vtr_flow.py" script to correctly handle the "max_router_iterations" argument. Currently, the script assumes that this argument is only for the router iterations on relaxed channel width. Thus, the VPR's default value of 50 iterations was used when attempting to find the minimum channel width. With this update, "max_router_iterations" determines the number of iterations for finding the minimum channel width, while "crit_path_router_iteration" is used for the relaxed channel width.
For example, running the script with the following command:
`run_vtr_flow.py ch_intrinsics.v k6_frac_N10_frac_chain_mem32K_40nm.xml -start odin -max_router_iterations 100 -crit_path_router_iteration 150`
Will set the maximum number of iterations for finding the …
> Min Chan W Number of Router Iterations

- run_quick_test.py
Allow -j argument to quick test
None
Currently quick test can only be run j=1 
Test providing various j values (and no j argument).  Correct value is passed on to subsequent script.
> Allow -j argument to quick test

- doc/src/vpr/command_line_usage.rst
Documentation for router_lookahead has the wrong default; it should be map.
> Update command_line_usage.rst map lookahead default

- doc/src/api/vprinternals/index.rst
- doc/src/api/vprinternals/noc_data_types.rst
- doc/src/api/vprinternals/noc_link.rst
- doc/src/api/vprinternals/noc_router.rst
- doc/src/api/vprinternals/noc_routing.rst
- doc/src/api/vprinternals/noc_storage.rst
- doc/src/api/vprinternals/noc_traffic_flows.rst
- doc/src/api/vprinternals/vpr_noc.rst
- doc/src/arch/reference.rst
- doc/src/vpr/command_line_usage.rst
- doc/src/vpr/file_formats.rst
- vpr/src/noc/noc_data_types.h
- vpr/src/noc/noc_link.h
- vpr/src/noc/noc_router.h
- vpr/src/noc/noc_routing.h
- vpr/src/noc/noc_routing_algorithm_creator.h
- vpr/src/noc/noc_storage.h
- vpr/src/noc/noc_traffic_flows.h
- vpr/src/noc/xy_routing.h
Adding documentation for the NoC related data structures. 
Created a new section under VPR INTERNALS called VPR NoC. This section includes documentation for the following data structures:
- NoC Router
- NoC Link
- NoC Storage
- NoC Traffic Flows
- NoC Routing
- NoC Data Types
Its good to have documentation for all internal datastructures within VPR.
THis has been tested by building the documentation locally and visually verifying the docs.
- [x ] I have updated the documentation accordingly
> Noc documentation

- vpr/src/noc/noc_storage.cpp
- vpr/src/noc/noc_storage.h
- vpr/src/noc/noc_traffic_flows.cpp
- vpr/src/noc/noc_traffic_flows.h
- vpr/src/noc/xy_routing.cpp
- vpr/src/noc/xy_routing.h
- vpr/src/place/initial_placement.cpp
- vpr/src/place/noc_place_utils.cpp
- vpr/src/place/noc_place_utils.h
- vpr/src/place/place.cpp
- vpr/src/place/place_checkpoint.cpp
- vpr/src/place/place_checkpoint.h
- vpr/test/test_noc_place_utils.cpp
When a placement checkpoint is restored, wirelength and timing-driven costs are computed from scratch. However, NoC costs were left intact, meaning that a mismatch between router locations in the restored checkpoint and the placement before restoring the checkpoint causes the NoC costs to be no longer valid. Changes in this pull request make sure that NoC-related costs and internal data structures are re-initialized when a placement checkpoint is restored.
If NoC-related costs are not re-computed after restoring a checkpoint, NoC costs may not be valid.
Placement checkpoints are only stored during quench. I could not find a reproducible case where routers are swapped during the quench, and as result, the restored checkpoint ended up having a different router placement. Since checkpoints …
> Recompte noc costs when restorting a checkpoint

- libs/librrgraph/src/io/rr_graph_uxsdcxx_serializer.h
Description
The pull request is to fix the segmentation fault that occurred when reading in the rr graph that had different segment types in the X and Y directions. The error was caused by some parts of the code that set the node cost index, which still relied on the assumption that the X and Y axes have the same segment types. The issue has been fixed by updating the relevant code.
How Has This Been Tested?
The changes have been tested using the Stratix 10 architecture. Before the fix, the rr graph could not be read in properly, resulting in the segmentation fault. After applying the fix, the issue has been resolved, and the rr graph is now correctly processed without any errors.
> Fix Seg Fault error when reading in an RR Graph with different x-y segment types

- libs/librrgraph/src/io/gen/rr_graph_uxsdcxx.h
- libs/librrgraph/src/io/gen/rr_graph_uxsdcxx_capnp.h
- libs/librrgraph/src/io/gen/rr_graph_uxsdcxx_interface.h
- libs/librrgraph/src/io/rr_graph_uxsdcxx_serializer.h
- libs/libvtrcapnproto/gen/rr_graph_uxsdcxx.capnp
While adding a layer in to grid in rr graph specification, a bug has been merged with master branch causing the reading rr graph to crash because of a function argument mismatch. I generated the files again and fixed the interface to run correctly.
> Function Argument Mismatch in RRGraph reader/writer

- vtr_flow/arch/noc/mesh_noc_topology/coffe_7nm_NoC_mesh_topology.xml
- vtr_flow/benchmarks/noc/Large_Designs/MLP/MLP_1/verilog/mlp1_complete_engine.v
- vtr_flow/benchmarks/noc/Large_Designs/MLP/MLP_1/verilog/mlp_1.v
- vtr_flow/benchmarks/noc/Large_Designs/MLP/shared_verilog/hard_block_include.v
- vtr_flow/benchmarks/noc/Large_Designs/MLP/shared_verilog/simple_collector.v
- vtr_flow/benchmarks/noc/Large_Designs/MLP/shared_verilog/simple_dispatcher.v
- vtr_flow/benchmarks/noc/Large_Designs/MLP/shared_verilog/simple_mvm.v
- vtr_flow/tasks/regression_tests/vtr_reg_nightly_test5/vpr_noc_mlp_odin_ii/config/config.txt
Former NoC flow used Quartus and vqm2blif script to generate netlist. In this pull request, we added a smaller dispatcher and collector to enable synthesis through Odin-II.
> Pass MLP design through Odin-II

- libs/librrgraph/src/io/gen/rr_graph_uxsdcxx.h
- libs/librrgraph/src/io/gen/rr_graph_uxsdcxx_capnp.h
- libs/librrgraph/src/io/gen/rr_graph_uxsdcxx_interface.h
- libs/librrgraph/src/io/rr_graph.xsd
- libs/librrgraph/src/io/rr_graph_uxsdcxx_serializer.h
- libs/libvtrcapnproto/gen/rr_graph_uxsdcxx.capnp
In this pull request, I have made changes to the RR Graph reader to enable it to read RR graph files that do not specify the layer number of nodes and grid.
After updating VPR to support 3D architecture, the layer number is now included in both the RR node description and the grid description of the XML file. However, some RR graph files generated by older runs may not have this information. As a result, if the reader cannot find the layer number, it would raise an error, causing issues for users using these older RR graph files.
With the updated RR Graph reader, we ensure that it can handle both cases seamlessly, allowing users to work with RR graph files from both older and newer runs without encountering any errors.
> RR Graph Reader - Backward Compatiblity

- vtr_flow/scripts/run_vtr_flow.py
Solve the issue[#2347](https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/2347)
> Change temp_dir default to abs dir

- vpr/src/place/centroid_move_generator.cpp
- vpr/src/place/critical_uniform_move_generator.cpp
- vpr/src/place/feasible_region_move_generator.cpp
- vpr/src/place/median_move_generator.cpp
- vpr/src/place/place.cpp
- vpr/src/place/place_constraints.h
- vpr/src/place/uniform_move_generator.cpp
- vpr/src/place/weighted_centroid_move_generator.cpp
- vpr/src/place/weighted_median_move_generator.cpp
Enhance debug output for the placer by providing additional information when a move is aborted.
@vaughnbetz
> Add More Debugging Messages When Move Is Aborted

- vpr/src/route/segment_stats.cpp
This PR addresses issue[#2399](https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/2399)
Sample output:
> Fix Segment Usage Message

- .github/scripts/hostsetup.sh
- libs/libarchfpga/src/read_xml_arch_file.cpp
- libs/libpugiutil/src/pugixml_util.cpp
While checking for a file extension with `.find_last_of()` the 'not found' scenario also needs to be checked.
While using FOEDAG + VPR at Quicklogic, we already have an internal encryption-decryption mechanism which is in use and that uses different file extensions (neither `.xml` nor `.xmle`), and in many cases no extension at all.
These kind of XMLs with no extension, cause the check for finding the extension to throw `std::out_of_range` as the return value for `position` is actually `std::string::npos` which needs to be checked before using it in the the `substr()` call.
Additionally a typo fix while checking to warn users of unrecognized extension.
As this change is specific to `openfpga` branch, I have not raised an issue for this.
Please let me know if I need to raise the issue.
Fix …
> Add 'not found' check for finding file extension of arch xml

- doc/src/vpr/command_line_usage.rst
We are missing documentation for this command line option; this PR adds it.
> Added --quench_recompute_divider documentation

- doc/src/vpr/command_line_usage.rst
- doc/src/vpr/dusty_sa.rst
The vpr command line option description has some confusing text and a broken link to the Dusty annealing schedule. This fixes it.
> Vb doc update - dusty annealing schedule link

- BUILDING.md
- doc/src/quickstart/index.rst
This updates the docs to instruct users to initialize submodules.
Documentation for #2437
> Add instructions on initializing submodules

- libs/libvtrutil/src/vtr_strong_id_range.h
- libs/libvtrutil/test/test_strong_id.cpp
In this PR, the operators that don't use private methods are moved outside of StrongIdIterator class. The "friend" identifier of other operators inside of the class is removed to avoid redefinition of them when an operator is used.
> StrongIdIterator Operator Overloading

- vpr/src/route/connection_router.cpp
- vpr/src/route/connection_router.h
- vpr/src/route/route.cpp
- vpr/src/route/router_stats.h
- vtr_flow/parse/parse_config/common/vpr.route_fixed_chan_width.txt
- vtr_flow/parse/parse_config/timing/vpr.route_relaxed_chan_width.txt
In this pull request, the routing status message has been modified. With this update, details such as the count of internal/external nodes pushed to/popped from the heap, breakdown of the node types pushed to/popped from the heap, and other extraneous messages will now be displayed only if `VTR_ENABLE_DEBUG_LOGGING` is defined. In case it is not defined, the output will be limited to the total number of routed nets and connections, along with the overall count of nodes pushed to and popped from the heap.
The PR would address the issue #2453
> Routing Stats

- .github/labeler.yml
- .github/workflows/labeler.yml
Pull Request Labeler v5 was released, introducing new syntax. Since the new syntax is not compatible with v4, triage job fails.
To prevent triage job from failing, we need to update labeler.yml file.
"infra" label for this PR was automatically added after the bug was fixed.
> Update labeler.yml to v5 syntax

- CHANGELOG.md
- doc/src/vtr/get_vtr.rst
I have created a Docker image for VTR 8 and VTR master branch and highlighted how to run these images in the documentation
> Add documentation for Docker images of vtr8 and VTR master

- vpr/src/draw/draw.cpp
- vpr/src/draw/draw_basic.cpp
- vpr/src/draw/intra_logic_block.cpp
- vpr/src/draw/intra_logic_block.h
Net Max Fanout is now used to filter out both primitive nets and cluster nets.
Net Max Fanout was previsouly compared to the number of pins, not the number of sinks. This problem was also fixed in this PR.
[Issue](https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/2451) 
Net Max Fanout was not working for clustered nets. More specifically, when this setting was changed, nets with fanout higher that the specified value were not filtered out.
Manually. I just ran vpr with --disp on and check if correct nets are shown.
> Net max fanout issue in Net Settings graphics 

- doc/src/vpr/command_line_usage.rst
- vpr/src/route/router_lookahead_map.cpp
- vpr/src/route/router_lookahead_map_utils.cpp
In this PR, the ".bin" extension has been added as an acceptable file extension for the router lookahead file.
> Router lookahead file extension

- .github/workflows/test.yml
CI  has been failing in master since two days ago. This PR fixes the problem. This is not the cleanest fix, but the alternative is to wait until next Friday when Github deploys the fix into their Ubuntu image.
[Issue](https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/2504)
Preventing CI test from failing in master.
Two CI tests fail in the master branch, but not in this one.
> Fix CI failures in master

- .github/workflows/test.yml
- CMakeLists.txt
- libs/EXTERNAL/libargparse/README.md
- libs/libarchfpga/CMakeLists.txt
- libs/librrgraph/CMakeLists.txt
- libs/libvtrutil/CMakeLists.txt
- libs/libvtrutil/src/vtr_util.cpp
- libs/libvtrutil/src/vtr_util.h
- utils/fasm/CMakeLists.txt
- utils/vqm2blif/CMakeLists.txt
- vpr/CMakeLists.txt
- vpr/src/base/ShowSetup.cpp
- vpr/src/base/ShowSetup.h
Fixes [this issue](https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/2507).
According to [filesystem library documentation](https://en.cppreference.com/w/cpp/filesystem), gcc versions older than 9.1 and clang prior to 9.0 need filesystem library to be explicitly linked. This PR adds the compiler option when it is necessary.
When trying to reproduce the compilation failure, I realized gcc-8.4 does not need the additional compiler option. However, to be consistent with the official documentation, I add the compiler flag for versions older than 9.1.
Current Github Ubuntu images do not have gcc-8 installed by default. When I manually installed gcc-8.4, VTR was built without any problem. It seems that it is only gcc-8.3 and older version sthat need the link flag. I reproduced …
> Link stdc++fs for older gcc versions

- libs/librrgraph/src/base/rr_graph_storage.h
- libs/librrgraph/src/base/rr_graph_view.h
- vpr/src/base/vpr_types.h
- vpr/src/route/connection_router.h
- vpr/src/route/route_common.cpp
- vpr/src/route/route_common.h
- vpr/src/route/route_net.cpp
- vpr/src/route/route_net.tpp
- vpr/src/route/route_path_manager.cpp
- vpr/src/route/route_tree.cpp
Cleaned up the rr_node_route_inf type as per issue #2499 
Removed target_flag
Removed prev_node
Updated the comment for prev_edge
resolves issue #2499 
Ran the Titan benchmarks on an unloaded machine and compared the results presently in Master with these changes:
As shown in the image above, there was no affect on QoR at all (which is to be expected since this MR does not change any functionality).
The max memory used by VPR reduced by 0.4%, which is in the order of 10 MB on the Titan benchmarks.
The runtime did not change. Although the results show a slight reduction in crit_path_route_time, both pack time and place time reduced by the same amount. Since this PR does not affect those two stages, it can be that the entire run was slightly faster due to testing conditions.
> [Route][Types] Clean Up rr_node_route_inf

- libs/libarchfpga/CMakeLists.txt
- libs/libarchfpga/src/read_fpga_interchange_arch.cpp
- libs/libarchfpga/src/read_fpga_interchange_arch.h
- vpr/CMakeLists.txt
- vpr/src/base/read_interchange_netlist.cpp
- vpr/src/route/router_lookahead_map.cpp
There were many build errors that arose when CAPNPROTO was disabled. It looks like there was a dependency in libarchfpga on libvtrcapnproto even though the library is disabled if the user passes a flag to disable it. Removed this dependency when the flag is disabled.
VPR also had a similar issue. This appears to have been handled in the past, but has since regressed. We should consider adding this build to CI to prevent further regressions (if this feature is needed).
resolves #2510 
Built using:
```
make CMAKE_PARAMS="-DVTR_ENABLE_CAPNPROTO=OFF"
```
and
```
make CMAKE_PARAMS="-DVTR_ENABLE_CAPNPROTO=ON"
```
> [CAPNPROTO][CMake] Fixed Build When CAPNPROTO is Disabled

- vpr/src/route/connection_router.cpp
- vpr/src/route/heap_type.cpp
- vpr/src/route/heap_type.h
- vpr/src/route/route_common.cpp
- vpr/src/route/route_common.h
A previous commit removed prev_node from t_rr_node_route_inf. This was because the prev_node can be uniquely identified by the prev_edge (but not the other way around).
The same methedology can be applied to the t_heap type. This was only being set, but it was never being used (with the exception of one debug message). Therefore this is only good for performance and memory overhead.
issue #2499 
This cleans up the t_heap struct some, which reduces memory overhead. This makes it easier to work with the heap and also may improve performance slightly.
> [Route][Heap] Removed prev_node From t_heap

- libs/libvtrutil/cmake/modules/configure_version.cmake
- vpr/src/route/router_lookahead_extended_map.cpp
During the CI build process of the new "R: Basic with CAPNPROTO disabled" job, there were a couple of basic warnings that I thought I would resolve.
The first were some warnings directly caused by CAPNPROTO being disabled:
These were easy to fix by commenting out the unused variables.
Next were some CMake warnings which appear to be affecting all builds:
It looks like the [exec_program](https://cmake.org/cmake/help/latest/command/exec_program.html) command was deprecated and the suggested replacement was to use the [execute_process](https://cmake.org/cmake/help/latest/command/execute_process.html#command:execute_process) command instead. The syntax was similar, but required a few extra arguments in order to properly get the Git version.
Some build warnings that showed up that caught my …
> Fixed a Couple Simple Warnings

- vpr/src/draw/draw.cpp
- vpr/src/place/place.cpp
- vpr/src/route/route_utilization.cpp
There were some warnings of unused variables when NO_GRAPHICS was declared. Explicitly cast these variables to void to mark them as purposely unused.
This was one of the issues in issue #2518
> [NO_GRAPHICS][Warnings] Resolved Unused Variables

- yosys/Makefile
Fixed a warning where "fatal: not a git repository: './/.git' was being printed during builds of VPR.
This is caused by Yosys being included as a subtree instead of a git submodule. The Makefile in Yosys is trying to get the current version of git for Yosys but it cannot do it since it is not a git repo.
Just commented out the line causing the warning for now.
This was actually a very interesting warning to debug.
I started by debugging the make command without using multiple threads to see what CMake command was causing this warning:
```
make -d &> temp.dump
```
Looking into the temp.dump file, I found that the warning was being printed when generating "yosys-bin":
Not only that, but it was being printed twice.
I then opened up yosys' CMakeList to find this beauty:
It looks like all this …
> [Yosys][Warnings] Fixed Fatal Not Git Repo Warning

- libs/libvtrutil/test/test_array_view.cpp
- utils/vqm2blif/src/base/cleanup.cpp
Fixed a couple of warnings in libvtrutil and vqm2blif
See issue #2518
> Removed Warnings in libvtrutil and vqm2blif

- libs/librrgraph/src/base/rr_graph_storage.cpp
The std::sort function requires operands to be "pointer-like", this requires that de-referencing a const pointer should be allowed.
This was not an issue in the past, but in LLVM17 this property is required. The edge_sort_iterator did not follow this property. This has been fixed.
See issue #2517 
The LLVM17 build failed due to a const edge_sort_iterator unable to be de-referenced. This PR fixes that issue.
The problem is that this required the `swapper_` member to be a pointer to allow this to work. This means that the `swapper_` object needs to be declared on the heap. This may have affects on the performance of this implementation. To prevent regression in performance, this needs to be profiled to ensure we do not slow down the current high-priority builds for future builds.
issue …
> [RR_GRAPH] Fixed Bug in LLVM17 Build

- doc/src/vtr/benchmarks.rst
Typo fix : should be Koios instead of VTR in one spot in the docs.
> Update benchmarks.rst to fix a typo where we said VTR instead of Koios

- CMakeLists.txt
- yosys/CMakeLists.txt
CMake was calling another Make command, but was explicitly passing the number of threads to use. Make files should not pass the number of threads to use since it may cause more threads to be consumed than what the user intended.
For example, if the user used `make -j10`, the parent make would use 10 threads, and the child make would also use 10 threads (20 threads in total); but this is not what the user wanted. I think CMake recognized this and was suppressing this behaviour anyways. I believe that CMake will pass the number of threads for the child make to use anyways, but in a way that would prevent the above issue.
Removed the ability to set the number of threads for Yosys builds to handle the warning.
See issue #2518
> [Yosys][Warnings] Fixed Make Being Called With Multiple Threads

- .github/scripts/install_dependencies.sh
A warning was being generated by EZGL when pre-processing the resources for main.ui. This could not be removed since the library we use to preprocess always tries to use XMLLINT even when it is not used.
If the system does not have XMLLINT installed, it will always give a warning saying it is not installed.
As a quick fix, we can make it so the CI has it installed, since this is technically the use case we want tested.
See issue #2518
> [CI][XML] Added XMLLINT to CI Dependencies

- blifexplorer/CMakeLists.txt
- libs/libvtrutil/src/vtr_util.cpp
- libs/libvtrutil/src/vtr_util.h
- utils/fasm/src/fasm.cpp
- utils/fasm/src/fasm.h
- utils/fasm/src/fasm_utils.cpp
- utils/fasm/src/fasm_utils.h
- vpr/src/base/read_blif.cpp
- vpr/src/base/vpr_api.cpp
This PR fixes fasm warnings mentioned in [this issue](https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/2518). It also replaces some std::string and const std::string& arguments with std::string_view. When an rvalue char* is passed as an std:string& argument, an std::string object needs to be constructed, which involves memory allocation and copying. std::string_view doesn't need to allocate memory and copy the null terminated string because it directly points to rvalue char*.
> Fix fasm warnings

- utils/vqm2blif/src/base/hard_block_recog.cpp
- utils/vqm2blif/src/base/preprocess.cpp
- utils/vqm2blif/src/base/vqm2blif_util.cpp
Cleaned up a few warnings that were simply resolved.
See issue #2518 
This also resolves one of the warnings in issue #2294
> [vqm2blif][Warnings] Removed std::regex and strncpy Warnings

- doc/src/vpr/command_line_usage.rst
- vpr/src/base/read_options.cpp
This pull request adds documentation related to `router_profiler_astar_fac` to the VTR documentation. (issue [#2536](https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/2536))
@vaughnbetz
> Astar Profiler Document

- doc/src/quickstart/index.rst
- doc/src/tutorials/flow/basic_flow.rst
- requirements.txt
1. Quickstart now shows how to build for use with ODIN II
2. Updated basic design flow tutorial to remove redundant instructions to run ``parse_vtr_task.py``
3. Changed version of black in ``requirements.txt`` to 21.4b0 so that ``make env`` works
1. The quickstart guide did not tell users how to build to that ODIN II could be used for synthesis. They would have to go to the ODIN II page and see to navigate to the ``odin_ii`` directory and ``make build``. The new command in the quickstart guide allows them to build ODIN II when they build VTR.
2. There was an instruction to run ``parse_vtr_task.py`` in the Basic Design Flow Tutorial, the reason being it created a ``parse_results.txt`` file, but this is already created by the earlier ``run_vtr_task.py``
3. ``make env`` did not work with the …
> Quickstart, requirements, and flow tutorial update

- libs/libarchfpga/src/device_grid.cpp
- libs/libvtrutil/src/vtr_ndmatrix.h
- vpr/src/base/CheckSetup.cpp
- vpr/src/base/SetupGrid.cpp
- vpr/src/base/SetupGrid.h
- vpr/src/base/SetupVPR.cpp
- vpr/src/base/read_options.cpp
- vpr/src/base/read_options.h
- vpr/src/base/vpr_types.h
- vpr/src/place/RL_agent_util.cpp
- vpr/src/place/RL_agent_util.h
- vpr/src/place/move_generator.h
- vpr/src/place/move_utils.cpp
- vpr/src/place/place.cpp
- vpr/src/place/simpleRL_move_generator.cpp
- vpr/src/place/simpleRL_move_generator.h
- vpr/src/place/static_move_generator.cpp
- vpr/src/place/static_move_generator.h
Currently, we pass the number of available moves to the KArmedBanditAgent's constructor to specify which moves are available. This interface assumes that move types have a specific order. This PR changes the interface so that available moves can be specified explicitly.
The main motivation for this PR is to add NoC-specific move types that are disabled for conventional architectures.
> Specify available moves explicitly

- libs/libarchfpga/src/echo_arch.cpp
In the current codebase, when we activate --echo_file, we might get a segmentation file while writing the architecture file. The reason is that we look at the number of layouts instead of layers. The architecture might have different layouts but still not be 3D using multiple <fixed_layout> options.  
This PR addresses the following issue:
[Segmentation Fault](https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/2449)
@vaughnbetz
> Architecture Seg Fault Issue

- README.developers.md
- libs/libarchfpga/CMakeLists.txt
- libs/libvtrutil/CMakeLists.txt
Modified the Developer Guide to give a basic tutorial for how to (1) run testers and (2) create unit tests, including a simple example. Also added ```test_archfpga``` to the list of tests that are run by ```make test```.
There was only a brief tutorial on how to run unit tests in the guide previously: one instruction to run ```make && make test```. This is not very helpful for anyone wanting to create their own unit tests, or run individual tests that target part of the software.
> Added a tutorial for running and creating unit tests.

- vpr/src/pack/re_cluster.cpp
- vpr/src/pack/re_cluster_util.cpp
- vpr/src/pack/re_cluster_util.h
> Re-clustering API bug fixes

- libs/librrgraph/src/base/rr_node_impl.h
- libs/librrgraph/src/base/rr_node_types.h
- libs/libvtrutil/src/vtr_ragged_matrix.h
See issue #2557 for more context.
Removed the uses of std::iterator that were very simple to remove. These just required declaring some types that the users of the iterators expect and removing the inheritance on the std::iterator.
The other cases in VTR which use std::iterator are a bit more complicated and may require some work to remove correctly.
> Removed Simple Uses of STD Iterator

- .github/workflows/test.yml
- vpr/src/route/connection_router.cpp
To prevent warnings from showing up in the build in the future, made the
CI error on any warnings during the regression tests.
It looks like VPR originally had the ability to error on warning;
however, it was specific to only VPR. This CMAKE method will now work
for all executables compiled during the tests.
With this merged, this should completely resolve issue #2518
> [CI] Made the Regression Tests Error on Warning

- vtr_flow/arch/titan/stratix10_arch.timing.xml
This PR addresses the outdated comments for the routing architecture model of the S10 architecture file. The comments were based on an old version of VPR where different x and y wire segments could not be modeled. The comments have been updated to reflect the new routing model that captures horizontal and vertical routing wires separately.
- [ x] Bug fix (change which fixes an issue)
> Fix the S10 arch file comments for routing segments and switches

- libs/EXTERNAL/libtatum/libtatum/tatum/tags/TimingTags.hpp
- libs/libvtrutil/src/vtr_array_view.h
- libs/libvtrutil/src/vtr_vector.h
See issue #2557 for context.
As with PR #2558 , removed slightly more complicated uses of std::iterator after discussing this more.
This PR modifies Tatum, I will upstream these changes back to the Tatum library after the PR is merged.
After this PR, the only use of std::iterator would be in the Capnproto library, which may be quite a bit more complicated to resolve.
> Removed Less-Simple Uses of STD Iterator

- .github/workflows/containers.yml
- .github/workflows/labeler.yml
- .github/workflows/test.yml
The Annotations section of the CI was full of deprecation warnings:
Node.js 16 actions were deprecated. Upgraded setup-python, checkout, and upload-artifact to their most recent version. See: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
v3 of upload-artifact was also deprecated. v4 claims to be 98% faster, however, may come with some breaking changes. Pertaining to us, artifacts cannot have the same name now and there is a limit of 500 artifacts. See:
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
Upgrade summary:
- actions/setup-python@v4 -> actions/setup-python@v5
- actions/checkout@v3 -> actions/checkout@v4
- actions/upload-artifact@v3 -> actions/upload-artifact@v4
NOTE: Had to leave the nightly …
> [CI] Upgraded Actions

- doc/src/arch/reference.rst
Clarified these are defaults only for rr-graph construction and can be overridden in custom switch blocks.
Current text implied to some that this data was crucial in the routing arch, when it is actually just a default for rr-graph construction.
> Doc update: mux and wire_switch for segments in arch file

- .github/workflows/test.yml
Reverted a change I made in PR #2568 which caused the CI to not generate artifacts on failure for the nightly tests.
Added a comment to document what this feature does and prevent this issue for the future.
> [CI] Fixed Issue with Artifacts not Being Saved On Failure

- .gitmodules
Solves [this issue](https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/2586)
Since sockpp uses ssh to clone the repo, ssh keys need to be set up. Alternatively, we can use https for cloning the repo.
> Fix submodule init issue

- .github/workflows/containers.yml
- .github/workflows/test.yml
Changed the workflow triggers for the test and container workflows such that they only run when there is a push to master.
Also added concurrency such that if a CI was called on a particular PR or branch that is already running the CI, it will cancel the old run. This will prevent useless runs of the CI.
> [CI] Changed the Workflow Triggers

- README.developers.md
Added documentation on how to upgrade the version of a subtree. This is non-trivial since many repos store their versions on different branches. Change the branch of a subtree is basically creating a new subtree, so the old subtree needs to be completely remove from VTR first.
> [Docs] Updated Subtree Docs for Upgrading Versions

- vpr/src/pack/re_cluster_util.h
As Vaughn mentioned in a comment for another PR, I forgot to document the temp_cluster_noc_grp_id of start_new_cluster_for_mol() fucntion. This PR adds a comment saying what is returned in temp_cluster_noc_grp_id.
> document temp_cluster_noc_grp_id argument of start_new_cluster_for_mol

- .github/workflows/containers.yml
- .github/workflows/test.yml
Solved https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/2598.
Added a `path-ignore` filter to the GitHub Actions triggers (including `push` and `pull_request`) to filter out any push or pull request that only includes docs updates.
The "Test" and "Containers" workflows will be skipped if a push or a PR only contains changes to the documentation, such as the developer guide and README, so that we can save CI resources for other uses.
For more details, please refer to the issue page :)
> [CI] Prevented Running the CI If Only the Documentation Is Updated

- vpr/src/route/connection_router.cpp
In an old version of the router, a catch was made to exit the router with no solution and not to retry at max bounding box; however, the function was rewritten to explicitly do this. The old catch statement was left in the code and was unreachable.
Removed the unreachable code.
This resolves issue #2570
> [Route] Removed Unreachable Code

- .github/scripts/install_noble_dependencies.sh
- .github/workflows/noble.yml
- .github/workflows/test.yml
- vpr/src/server/bytearray.h
- vpr/src/server/telegramheader.h
Ubuntu 24.04 uses GCC-13 as its default GCC version. The CI should ensure that VTR builds for this version of GCC.
Also added the version of Clang that would come with Ubuntu 24.04
Versions of tools were found from here:
https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
> [CI] Added GCC-13 as a Compatability Test

- .github/workflows/containers.yml
- .github/workflows/test.yml
When artifacts were being saved for the regression tests, it was saving
all of the benchmarks as blif files. This is incredibly wasteful (72 MB
per regression test or around 720 MB per CI run). These tests will no
longer save .blif files as artifacts anymore. If anyone needed these
files they could generate them themselves or can add a condition to add
the exact .blif files they may need.
The CI was also always generating artifacts (at least for the nightly
tests) even when the run was cancelled. Made it so the artifacts are
only saved if the run is not cancelled. This would mean an artifact is
generated if the run succeeds or fails.
save-output was deprecated. Resolved. See:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> [CI] Cleaned Up Artifacts and Resolved Deprecation

- libs/libarchfpga/src/physical_types.h
- vpr/src/pack/pb_type_graph.cpp
Added a flat_site_idx to pb_graph_node struct, along with code to populate it in alloc_and_load_pb_graph.
As alloc_and_load_pb_graph builds the graph from the top down, each parent computes its child's flat index and passes it to them as an argument to alloc_and_load_ph_graph.  
The child's flat site is computed by the parent as:
(parent's flat site)*(total children of this type) + child's sibling index.
This is used to help the legalizer place a molecule on a user specified site. It is better to store this value in the node than to recompute it over and over.
Compared this value to locally computed value in the legalizer, which is then printed to a flat placement file and compared via a script.  I tested on both StratixIV and ISPD Ultrascale architectures.  In all cases, computed sites …
> add flat idx to pb_graph_node , populate in alloc_and_load_pb_graph

- libs/libvtrutil/src/vtr_assert.cpp
When debugging, I find that sometimes when the program hits an assertion, some log would not be printed as expected. Manually flushing before abort() brings more consistent printing.
> Enable VTR to flush stdout and stderr before assertion

- libs/libarchfpga/src/physical_types.h
- vpr/src/pack/cluster_placement.cpp
- vpr/src/pack/cluster_placement.h
- vpr/src/pack/cluster_util.cpp
- vpr/src/pack/cluster_util.h
- vpr/src/pack/re_cluster_util.cpp
- vpr/src/pack/re_cluster_util.h
Added an optional primitive site parameter; if specified, vpr will either place the molecule on the specified site or fail; if not specified, vpr will select an available, legal site (if possible).
Added optional force_site parameter to pack_mol_in_existing_cluster and start_new_cluster_for_mol; these functions pass the parameter to try_pack_mol, which passes it to get_next_primitive_list.  If a force site is passed to get_next_primitive_list, it either places the molecule on this site or else returns failure. 
This is required for reconstructing clusters from an externally generated flat placement.
This has been tested by ingesting and reconstructing VPR-generated flat placement files.
This has no impact on QoR (in a previous PR I reported results for this and several other …
> enable option to force molecule placement on a specified primitive site

- vpr/src/pack/cluster_placement.h
cluster_placement.h needs vpr_types.h for definitions of t_pack_molecule and t_cluster_placement_stats.
added #include "vpr_types.h" to cluster_placement.h
VPR fails to compile when cluster_placement.h is included in a .cpp file that does not include vpr_types.h earlier in the file.
VPR still compiles and there is no change in QoR (based on quick neuron test referenced in another PR).
> cluster_placement.h is missing #include vpr_types.h

- vpr/src/pack/cluster_util.cpp
g_vpr_ctx.cl_helper().atom_noc_grp_id is not initialized when try_pack() is not called. This causes a segfault when re-clustering API is used as atom_cluster_noc_group_check() tries to access an uninitialized vector. This PR fixes this problem by check whether the vector is initilzided.
> Fix segfault in atom_cluster_noc_group_check()

- vpr/src/pack/re_cluster.cpp
- vpr/src/pack/re_cluster_util.cpp
When removing a molecule from a cluster or adding a molecule to an existing cluster, the clb-atoms lookup is updated in the helper function responsible for the change.  For consistency, I've moved the lookup update to the helper function for creating a new cluster for a molecule.
Moved code that resizes the lookup and adds all molecule atoms to the entry for the new cluster from the top level api function in re_cluster.cpp to the utility function in re_cluster_util.cpp.
In the legalizer, it is confusing to sometimes have to update this data structure and sometimes not; always doing it in the helper function is more clear.  It does not change the functionality of the re-clustering API.
> move lookup update to start_new_cluster... for consistency

- vpr/src/draw/draw_types.cpp
- vpr/src/util/vpr_utils.cpp
- vpr/src/util/vpr_utils.h
`get_physical_tile_type` is a function that returns a pointer to the physical tile corresponding to a `ClusterId`. There is a similar function in `vpr_utils` with similar functionality (`physical_tile_type`). The only difference is that `get_physical_tile_type` will return a tile type even if the cluster is not placed (for drawing purposes). Instead of having a separate function, I call that function directly if the block is not placed.
> Redundant Physical Type

- doc/src/api/vprinternals/router_heap.rst
- vpr/src/route/heap_type.h
Two changes to [Router Heap documentation](https://docs.verilogtorouting.org/en/latest/api/vprinternals/router_heap/#classHeapInterface_1af6cf3e31510d0ab16da15dfcb4f0ce35):
1. _Currently_: ``u`` is protected and so doesn't appear in the documentation, but [the descriptions of its accessors/mutators refer to it](https://docs.verilogtorouting.org/en/latest/api/vprinternals/router_heap/#classHeapInterface_1af6cf3e31510d0ab16da15dfcb4f0ce35:~:text=inline%20t_heap%20*next_heap_item,Set%20u.prev_edge.). _Now_: these functions' descriptions don't reference ``u`` and state explicitly what they do.
2.  _Currently_: there are duplicate descriptions for public pure virtual functions inherited from ``HeapInterface`` and/or ``KAryHeap``. _Now_: only ``HeapInterface`` has descriptions for its public …
> Router Heap documentation update

- vpr/src/route/rr_graph2.cpp
While creating RR edge, incremental and decremental tracks use the same seg_details of inc_track. Although this is incorrect, it doesn't affect the quality of results because we don't have an architecture that uses different muxes for incremental and decremental tracks. So, I don't expect anything to change by this fix.
> RR graph edge creation uses a incorrect switch type for decremental tracks

- .github/workflows/test.yml
This update brings Yosys to the latest version, 0.42, which includes several bug fixes, performance improvements, and new features that enhance the synthesis capabilities of our flow. Notable additions in this version include : 
-New commands and options
-Verific support
-Added support for using the ABCs library
-Added support for VHDL 2009
...
For a detailed list of changes and improvements in Yosys 0.42 (June 7, 2024), please refer to the [release notes](https://github.com/YosysHQ/yosys/releases/tag/yosys-0.42).
-Update Yosys [The latest version in the VTR flow is 0.32]
> Yosys Update -> v0.42

- .github/workflows/test.yml
Reverts verilog-to-routing/vtr-verilog-to-routing#2596
The PR was merged at a point when it only turned off testcases without pushing code which broke them.
The testcases should be re-enabled until the code that needs them off is merged.
> Revert "Yosys Update -> v0.42"

- README.developers.md
Close #2545.
Rewrote the existing Profiling VTR section, specifically the one using GNU `gprof` tool.
Added another subsection to explain how to use the Linux `perf` tool to profile VPR and visualize its output.
> [Docs] Updated Profiling VTR Section in Developer Guide

- vtr_flow/arch/ispd/ultrascale_ispd.xml
Updated fracturable LUT connectivity in order to successfully reconstruct known legal clusters.
Added complete interconnect from fracturable LUT data inputs to data inputs for each half LUT.
Unable to reconstruct known legal RippleFPGA-generated clusters without this change.
Successfully reconstructed RippleFPGA solutions for all 12 ISPD benchmarks.
> update fracturable LUT connectivity based on known legal external placements

- .github/workflows/nightly_test.yml
The self-hosted runners inexplicably came back to life. Turning back on the NightlyTests on PR synchronization.
> [CI] Turned On NightlyTests on PR

- vpr/src/place/initial_noc_placement.cpp
- vpr/src/place/move_transactions.cpp
- vpr/src/place/move_transactions.h
- vpr/src/place/move_utils.cpp
- vpr/src/place/move_utils.h
- vpr/src/place/net_cost_handler.cpp
- vpr/src/place/net_cost_handler.h
- vpr/src/place/noc_place_utils.cpp
- vpr/src/place/place.cpp
- vpr/src/place/place_constraints.h
- vpr/src/place/placer_breakpoint.cpp
- vpr/src/place/placer_breakpoint.h
- vpr/test/test_noc_place_utils.cpp
1. In "[net_cost_handler.cpp](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fverilog-to-routing%2Fvtr-verilog-to-routing%2Fblob%2Fplacement_move_primitive%2Fvpr%2Fsrc%2Fplace%2Fnet_cost_handler.cpp&data=05%7C02%7Cyulang.luo%40mail.utoronto.ca%7C5e26bbdc343c4119a05f08dc9fb5ddf1%7C78aac2262f034b4d9037b46d56c55210%7C0%7C0%7C638560850665905503%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=58ozr4ygx6cDyqFr5NL0%2BYAXmebPJsq5xthyQtC28iA%3D&reserved=0)", there are [three](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fverilog-to-routing%2Fvtr-verilog-to-routing%2Fblob%2Fplacement_move_primitive%2Fvpr%2Fsrc%2Fplace%2Fnet_cost_handler.cpp%23L62-L77&data=05%7C02%7Cyulang.luo …
> [vpr][place] Placement move primitive refactoring

- vtr_flow/arch/ispd/ultrascale_ispd.xml
Reverts verilog-to-routing/vtr-verilog-to-routing#2668
vtr_reg_nightly_test5 now times out after 7 hours when it used to take around 3 hours. Only 3 PRs were merged yesterday, and I think this PR may have been the cause. Reverting the PR to see if the timeout goes away.
> Revert "update fracturable LUT connectivity based on known legal external placements"

- doc/src/vpr/command_line_usage.rst
- vpr/src/base/SetupVPR.cpp
- vpr/src/base/ShowSetup.cpp
- vpr/src/base/read_options.cpp
- vpr/src/base/read_options.h
- vpr/src/base/vpr_types.h
- vpr/src/place/timing_place_lookup.cpp
- vpr/src/route/connection_router.cpp
- vpr/src/route/connection_router_interface.h
- vpr/src/route/route_net.tpp
- vpr/src/route/router_delay_profiling.cpp
- vpr/test/test_connection_router.cpp
Using an astar_offset can help better tune the ordering heuristic for the search used to find the shortest path in the routing graph. It is also necessary to ensure that the heuristic is an underestimate (without setting the astar_fac to 0.0).
> [Route] Added astar_offset Parameter

- vpr/src/base/SetupVPR.cpp
- vpr/src/base/read_options.cpp
- vpr/src/base/read_options.h
- vpr/src/base/read_place.cpp
- vpr/src/base/vpr_types.h
- vpr/src/place/initial_placement.cpp
- vpr/src/place/place.cpp
In this PR, I have added an option to the CLI to read the initial placement. It was tested on the Titan Murax circuit, and the results from reading the initial placement from a file were the same as those from running the initial placement during the flow.
> Read Initial Placement

- requirements.txt
- vtr_flow/scripts/tuning_runs/README.md
- vtr_flow/scripts/tuning_runs/control_runs.py
This PR adds a script that automates setting up large runs to tune multiple parameters. It also helps with parsing the resultant data generating a single .xlsx file with the full parsed data, average results over the different seeds and geometrically average results over all the circuits. The PR also includes a README that explains  how to used the new script.
> Automate tuning runs

- vpr/src/place/initial_placement.cpp
- vpr/src/route/rr_graph.cpp
Previously, when the run-flat option was used and the RR graph was read from a file, the assumption was that all switch types (both inter-cluster and intra-cluster) were listed under the switch tag in the RR graph file. Consequently, when adding intra-cluster edges, if the RR graph builder encountered an edge that didn't have a corresponding switch type, it would throw an error.
In this PR, we removed this assumption. Now, if the RR graph builder cannot find a switch type, it will add a new RR switch type.
To test this PR, I used the Titan Murax circuit. The first run was with run-flat enabled, and the graph was built from scratch. For the second run, I first wrote the RR graph with run-flat disabled, so the RR graph file did not contain any of the intra-cluster switches. Then, I ran VPR …
> Fix for Handling Missing Switch Types in RR Graph Builder

- libs/librrgraph/src/io/gen/README.gen.md
- libs/librrgraph/src/io/gen/rr_graph_uxsdcxx.h
- libs/librrgraph/src/io/gen/rr_graph_uxsdcxx_capnp.h
- libs/librrgraph/src/io/gen/rr_graph_uxsdcxx_interface.h
- libs/librrgraph/src/io/rr_graph.xsd
- libs/librrgraph/src/io/rr_graph_uxsdcxx_serializer.h
- libs/libvtrcapnproto/gen/rr_graph_uxsdcxx.capnp
In this PR, the feature requested in issue #2503 has been implemented. To maintain backward compatibility, adding the `length` attribute is optional. However, if the attribute is included and the specified length is incompatible with the one in the architecture file, an error will be raised.
> [RR Graph] Add length attribute to segment tag

- doc/src/vpr/vpr_constraints.rst
Cleaning up the documentation so the initial summary makes clear we support two types of constraints (some of the info was outdated and referred only to placement regions).
> Update vpr_constraints.rst summary to cover placement and global signals

- doc/src/quickstart/index.rst
I have made a few grammatical fixes I found while reading the Quick Start Guide. @vaughnbetz please let me know if I have made any errors in the formatting of this pull request for future contributions.
Allows the guide to be followed smoothly, improving clarity and consistency
> Fix typo in Quick Start

- doc/src/vpr/file_formats.rst
Updated the .place file documentation.
#2439 
Provides Clarity
> Updated  documentation for .place file

- CMakeLists.txt
- libs/EXTERNAL/libtatum/libtatum/tatum/tags/TimingTags.hpp
- libs/libvqm/vqm_common.c
- vpr/CMakeLists.txt
- vpr/src/base/ShowSetup.h
- vpr/src/draw/draw_rr.cpp
- vpr/src/power/power.cpp
- vpr/src/power/power_components.cpp
- vpr/src/power/power_components.h
- vpr/src/power/power_util.cpp
- vpr/src/power/power_util.h
- vpr/src/route/route_path_manager.h
- vpr/test/test_post_verilog.cpp
This PR resolves several small issues which were causing warnings in the GCC13 build. Trying to get GCC13 warning clean before we upgrade the CI.
This resolves the following warnings:
- Fixed incorrect forward declaration
- Fixed ambiguous unique pointer allocation
- Converted an int into a size_t
- Fixed array access out of bounds
- Fixed potential memory leak
- Changed C String to STD String
- Fixed const reference
- Removed -lz flag from compilation
- Added missing headers to a file
See each of the associated commits for more details.
There are still warnings coming from the nDMatrix class (discussed previously) which should be resolved in its own PR. There are also a couple of other small warnings which are slightly more complex to resolve.
> [Warnings] Cleaned Up Most Warnings in GCC-13

- vpr/src/base/vpr_context.h
- vpr/src/base/vpr_types.cpp
- vpr/src/base/vpr_types.h
- vpr/src/pack/cluster.cpp
- vpr/src/pack/cluster.h
- vpr/src/pack/cluster_util.cpp
- vpr/src/pack/cluster_util.h
- vpr/src/pack/pack.cpp
- vpr/src/pack/pack.h
- vpr/src/pack/prepack.cpp
- vpr/src/pack/prepack.h
- vpr/src/timing/PreClusterDelayCalculator.h
- vpr/src/util/vpr_utils.cpp
- vpr/test/test_connection_router.cpp
- vpr/test/test_post_verilog.cpp
- vpr/test/test_vpr.cpp
The original Prepacker API created a lot of global variables which were confusing to work with and hard to maintain.
Created a Prepacker class which maintains the state of the Prepacker and provides methods to access prepacking information.
I also tried to remove the accesses to the global scope from within the prepacker to isolate it from the rest of VTR. This is in an attempt to make it easier to work with.
> [Prepacking] Re-Designed Prepacker API

- .github/workflows/test.yml
- vpr/src/place/place_timing_update.cpp
This PR addresses [this issue](https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/2705).
The compilation error reported in the issues has been fixed. A new CI test compiler VTR with VTR_ASSERT_LEVEL=4 and tests vtr_reg_basic.
> Fix compilation error with VTR_ASSERT_LEVEL=4

- vpr/src/base/atom_netlist.h
- vpr/src/base/clustered_netlist.h
Updated the documentation for the AtomNetlist and ClusteredNetlist classes to reflect the new behavior of the create_* functions. The documentation now specifies that these functions will return the existing ID if an element (block, port, pin, or net) with the specified name or ID already exists, instead of creating a duplicate
closes #2690 
The update was necessary to avoid performance issues caused by unnecessary duplicate creations in the netlist
> Update Netlist Creation Function Documentation to Prevent Duplicates

- vpr/src/analytical_place/ap_netlist.cpp
- vpr/src/analytical_place/ap_netlist.h
- vpr/src/analytical_place/ap_netlist_fwd.h
- vpr/test/test_ap_netlist.cpp
The APNetlist class holds the blocks and nets used during the AP flow. In the AP context, a block is a collection of primitives which would want to be placed in the same location (i.e. they want to move together). Currently, each block represents a pack molecule (created by the Prepacker). The nets are logical connections between blocks. The APNetlist will not contain any nets which are not needed for AP.
The APNetlist is tested using a Unit Test which tests its basic functionality (features that differ from the base Netlist class).
This is the first of many commits which will bring Analytical Placement into VPR.
> [AP] Created The APNetlist Class

- vpr/src/analytical_place/analytical_placement_flow.cpp
- vpr/src/analytical_place/ap_netlist.cpp
- vpr/src/analytical_place/ap_netlist.h
- vpr/src/analytical_place/gen_ap_netlist_from_atoms.cpp
- vpr/src/analytical_place/gen_ap_netlist_from_atoms.h
This method reads the atom netlist and uses the results of the prepacker to generate an APNetlist. It also fixes the block locations based on the user place constraints.
> [AP] Added Ability to Read The Atom Netlist

- vpr/src/analytical_place/partial_placement.cpp
- vpr/src/analytical_place/partial_placement.h
- vpr/test/test_ap_partial_placement.cpp
Added the partial placement object. This object is used during the Analytical Placement flow to store the positions of the APBlocks. This placement is not gaurenteed to be legal; however, it does gaurentee that the blocks are placed on the device and the fixed blocks are placed in valid locations.
> [AP] Added Partial Placement Object

- vtr_flow/scripts/python_libs/vtr/log_parse.py
- vtr_flow/scripts/python_libs/vtr/parse_vtr_flow.py
Added affixes to the regex pattern string, i.e., `$.*(my pattern).*$` to ensure that the searched pattern is not strictly required to start from the beginning of the string or line; it only needs to be part of the line.
This makes the definition of the pattern rules easier and makes the VTR flow log parser more robust.
(The following texts are copied from #2743)
The VTR flow log parser currently *only* parses/matches the regex pattern starting from:
- either the beginning of the line, e.g., `(my pattern)...`
- or the character right after one or multiple #, e.g., `#### (my pattern)...`
(Note: The parse function and a brief intro of how the VTR log parser works can be found in the appendix.)
The above assumptions can break the parser in some cases, causing chaotic failures in the …
> [TestScript] Enhanced the Robustness of the VTR Flow Log Parser Script

- libs/librrgraph/src/base/rr_graph_utils.cpp
- libs/librrgraph/src/io/gen/rr_graph_uxsdcxx.h
Couple fixes from SPEC CPU work:
- Provide rr_graph_utils with full definition of lambda function. 
- Remove/replace __attribute since MSVC doesn't know about it.
> Couple fixes from SPEC CPU work

- libs/libarchfpga/src/physical_types.h
- libs/librrgraph/src/io/rr_graph_uxsdcxx_serializer.h
- utils/fasm/src/main.cpp
- utils/fasm/test/test_fasm.cpp
- vpr/src/base/atom_lookup.cpp
- vpr/src/base/atom_lookup.h
- vpr/src/base/read_netlist.cpp
- vpr/src/base/vpr_api.cpp
- vpr/src/base/vpr_context.h
- vpr/src/draw/search_bar.cpp
- vpr/src/pack/pack.cpp
- vpr/src/pack/post_routing_pb_pin_fixup.cpp
- vpr/src/pack/post_routing_pb_pin_fixup.h
- vpr/src/pack/sync_netlists_to_routing_flat.cpp
- vpr/src/pack/sync_netlists_to_routing_flat.h
- vpr/src/route/annotate_routing.cpp
- vpr/src/route/annotate_routing.h
- vpr/src/route/route_common.cpp
- vpr/src/route/route_utils.h
- vpr/src/util/vpr_utils.cpp
Re-opened #2691 to see if that fixes the CI.
> Add flat version of sync_netlists_to_routing

- vpr/src/timing/slack_evaluation.cpp
In debug mode, the STA checks if the incremental STA matches the STA computed from scratch. In this check it checked for if the critical nodes matched; however, the nodes returned are not stably deterministic (it does not break ties in a deterministic way). After discussing with Vaughn, it is safe to just remove the nodes check since it would not change the result of the analysis.
closes #2754
> [STA] Fixed Incremental Slack Timing Analysis Verify Code

- libs/libarchfpga/src/physical_types.h
- vpr/src/base/SetupVPR.cpp
- vpr/src/base/ShowSetup.cpp
- vpr/src/base/place_and_route.cpp
- vpr/src/base/read_options.cpp
- vpr/src/base/read_options.h
- vpr/src/base/read_route.cpp
- vpr/src/base/vpr_types.h
- vpr/src/route/connection_router.cpp
- vpr/src/route/route.cpp
- vpr/src/route/route_net.tpp
- vpr/src/route/route_utils.cpp
- vpr/src/route/route_utils.h
- vpr/src/route/router_stats.h
- vtr_flow/tasks/regression_tests/vtr_reg_nightly_test7/vtr_reg_qor_large_depop_run_flat/config/config.txt
> Turn On Choke Point By Default

- vpr/src/place/net_cost_handler.cpp
- vpr/src/place/net_cost_handler.h
When using 3D architectures, two types of bounding boxes are available: per-layer and cube bounding boxes. For the cube bounding box, the cost function previously depended only on the bounding box's dx and dy dimensions, with dz being ignored. In this PR, we added chanz_place_cost_fac_ to the NetCostHandler class, which contains the inverse of the average number of inter-die connections for each [subheight][sublow] pair. This data structure is multiplied by the bounding box’s dz and added to the placement cost.
QoR:
3D SIV without Z cost vs 3D SIV with Z cost:
> Add Z Cost to Placement Cost Function [WIP]

- libs/libvtrutil/src/vtr_vector.h
- vpr/test/test_odd_even_routing.cpp
I couldn't reproduce the unit test failure on a local machine, so I created this PR to trigger a CI run and hopefully locate the segault.
> Trying to fix the failing unit test

- .github/workflows/nightly_test.yml
The Nightly Tests have not worked for weeks. There is no reason to keep trying to run them everytime we raise a PR.
I still left the cron job on so we can see if it ever comes back.
This just makes merging PRs easier.
> [CI] Turned Off Nightly Tests on PR and Merge

- doc/src/vpr/command_line_usage.rst
This PR updates the documentation for command line options that are related to NoC support in VPR.
> Update NoC options in command_line_usage.rst

- vpr/src/place/median_move_generator.cpp
- vpr/src/place/weighted_median_move_generator.cpp
Removes unnecessary call to `floor()` in median move generators.
> Remove calls to floor() in median move generators

- vpr/src/base/vpr_types.h
- vpr/src/pack/cluster.cpp
- vpr/src/pack/cluster_legalizer.cpp
- vpr/src/pack/cluster_legalizer.h
- vpr/src/pack/cluster_util.cpp
- vpr/src/pack/prepack.cpp
- vpr/src/pack/prepack.h
- vpr/src/util/vpr_utils.cpp
- vpr/src/util/vpr_utils.h
Pack molecules originally contained a flag called "valid" which signified that the molecule has not been clustered yet. This flag is not necessary since the Cluster Legalizer maintains this information internally. Removed the valid flag from the pack molecule struct.
See issue #2791
> [Prepacker] Removed Valid Flag From Molecules

- vpr/src/analytical_place/full_legalizer.cpp
- vpr/src/base/vpr_api.cpp
- vpr/src/place/place.cpp
- vpr/src/place/place_constraints.cpp
- vpr/src/place/place_constraints.h
- vpr/src/place/verify_placement.cpp
- vpr/src/place/verify_placement.h
Created a method that would independently verify the placement in the VPR flow. If a placement passes this verification, it is assumed that it can be used in routing without issue.
By design, this method does not use any global variables (everything needs to be passed in) and recomputes everything that it does not assume. This allows it to be independent of the placement flow being used, so this method can be used in the AP flow as well.
> [Place] Independent Placement Verification

- vpr/src/analytical_place/full_legalizer.cpp
- vpr/src/base/vpr_api.cpp
- vpr/src/pack/verify_clustering.cpp
- vpr/src/pack/verify_clustering.h
Created a method that would independently verify the clustering in the VPR flow. If a clustering passes this verification, it is assumed that it can be used in placement and routing without issue.
By design, this method does not use any global variables (everything needs to be passed in) and it recomputes everything that it does not assume. This allows it to be independent of the packing flow, so this method can also be used in the AP flow.
> [Clustering] Independent Clustering Verification

- vpr/src/place/manual_move_generator.cpp
This bug was introduced when `BlkLocRegistry` was added to the project. In `manual_move_generator`, the global instance of `BlkLocRegistry` was used instead the one stored in `placer_state_`. This caused a segfault as the global object is initialized at the end of placement.
> Fix segmentation fault when moving blocks manually

- vpr/src/draw/manual_moves.cpp
- vpr/src/draw/manual_moves.h
- vpr/src/place/place.cpp
This PR is a follow-up on PR #2804 to fix a segmentation fault that happens during manual moves after the latest refactors. It also adds an widget for the layer in the manual move prompt.
The manual move was facing segmentation fault due to 2 reasons:
1.  The global instance of `BlkLocRegistry` was used instead the one stored in `placer_state_` --> fixed in PR #2804 but still after this fix, whenever the user accepts or rejects the move, it will result in a seg fault.
2. After the move, the code is trying to update the RL agent Q table and the move statistics while the move type is manual (not recognized by the agent) --> fixed in this PR
> Fix manual move

- libs/EXTERNAL/libezgl/CMakeLists.txt
- libs/EXTERNAL/libezgl/examples/basic-application/CMakeLists.txt
- utils/route_diag/CMakeLists.txt
The CI currently always runs on the latest version of CMake. I am not sure why this is, its not the best practice, but CMake is a fairly stable application so it should be fine.
CMake is deprecating version 3.9, and a few CMake files require the minimum version to be 3.9 or larger. Changed these files to be 3.10 or later.
This is currently causing the CI to fail for basically all of the tests with the following errors:
> [CMake] Upgrade Minimum Version to 3.10

- libs/libvtrutil/src/vtr_ndmatrix.h
This change was originally proposed by @heshpdx
c++20 disallows template IDs from the constructor of templated classes. This is a strange thing to do anyways and was likely done by mistake. Removed the template IDs from both the standard constructor and the copy constructor.
Resolves #2818
> [NDMatrix] Removed Template ID From Constructors

- vpr/src/base/SetupVPR.cpp
- vpr/src/base/ShowSetup.cpp
- vpr/src/base/vpr_types.h
- vpr/src/pack/attraction_groups.cpp
- vpr/src/pack/attraction_groups.h
- vpr/src/pack/cluster_legalizer.h
- vpr/src/pack/cluster_util.cpp
- vpr/src/pack/cluster_util.h
- vpr/src/pack/greedy_clusterer.cpp
- vpr/src/pack/greedy_clusterer.h
- vpr/src/pack/pack.cpp
- vpr/src/pack/pack_types.h
Cleaned up the overall clustering algorithm in the greedy clusterer class. This change is non-functional, the control flow was rearanged and inlined / outlined to make the overall clustering algorithm more clear.
More needs to be done to abstract timing and the gain calculation which is coming soon.
> [Packer] Clean Up Clustering Algorithm

- vpr/src/route/DecompNetlistRouter.h
- vpr/src/route/DecompNetlistRouter.tpp
- vpr/src/route/ParallelNetlistRouter.h
- vpr/src/route/ParallelNetlistRouter.tpp
- vpr/src/route/SerialNetlistRouter.h
- vpr/src/route/SerialNetlistRouter.tpp
- vpr/src/route/connection_router.cpp
- vpr/src/route/netlist_routers.h
- vpr/src/route/partition_tree.cpp
- vpr/src/route/partition_tree.h
- vpr/src/route/route.cpp
- vpr/src/route/route_utils.cpp
- vpr/src/route/route_utils.h
- vpr/src/route/sink_sampling.h
- vpr/src/route/spatial_route_tree_lookup.cpp
Paper version of the net decomposing router. Major fixes are:
1. Don't count pruned sinks towards high fanout case's chan_nodes_added
2. Add a minimum bin size for the HF case to prevent minuscule bins when flat routing is enabled
3. Incrementally update the PartitionTree instead of rebuilding on every iteration
> Net decomposition: tuning and polishing

- libs/libvtrutil/src/vtr_ndmatrix.h
GCC13 introduced a warning for potentially dangling references. The NDMatrix class was creating temporary objects to store the offseted pointer and then returning refrences to these pointers. Although this is correct, since the pointer is owned by the base NDMatrix object, it was confusing the compiler which is not something you want to do in general.
Changed how the NDMatrix proxy class works by storing the offset into the pointer directly and passing a reference to the base pointer instead. This makes it clear to the compiler that this pointer belongs to another class and we are returning a reference to a portion of that memory, which is allowed.
> [NDMatrix] Resolved Dangling Reference Warning

- vpr/src/route/DecompNetlistRouter.tpp
Looks like sinks no longer "grow" to the size of their tile. In that case, it's better to use the tile bounding box to sample sinks for the net decomposing router.
This seems to fix the runtime blowup I started to see again with the decomp + flat router. Here is a table with "actual" route times from the flat router which I get by adding up the iteration times.
| circuit                                  | master | mine  | decomp | decomp (fixed) |
|------------------------------------------|--------|-------|--------|----------|
| gsm_switch_stratixiv_arch_timing.blif    |  113.7 |   108 |   72.2 |     63.6 |
| mes_noc_stratixiv_arch_timing.blif       |  467.7 | 254.6 |  733.6 |    655.4 |
| dart_stratixiv_arch_timing.blif          |   68.5 |  68.2 |   47.8 |     42.7 |
| …
> Net decomposing router: hotfix

- libs/librrgraph/src/io/gen/rr_graph_uxsdcxx.h
- vpr/src/base/gen/vpr_constraints_uxsdcxx.h
- vpr/src/draw/draw_rr.cpp
- vpr/src/draw/search_bar.cpp
Resolved a warning in search_bar.cpp which warned about a reference to a temporary. Simply fixed by splitting the statement into two lines.
Resolved a warning in draw_rr.cpp where a print statement was trying to access an invalid location in an array. The print statement did not make sense, it was trying to print an undefined side. This was removed.
Resolved a warning in the automatically generated vpr_constraints file. This was an interesting warning due to the decltype method returning the attributes of the FILE pointer, but this was passed into a template which discards the attributes (this generates a warning). Resolved this manually locally and raised a PR on the uxsdcxx repo with this fix: https://github.com/SymbiFlow/uxsdcxx/pull/53
> [Warnings] Resolved Basic Warnings for GCC13

- libs/libvtrutil/src/specrand.cpp
- vpr/src/base/netlist_writer.cpp
Fixed a warning with a loop induction variable not being initialized.
Fixed a warning where a method overrides the base class, but was not explicitly declared as override.
Resolves #2831
> [Warnings] Fixed Minor Warnings

- doc/src/vpr/command_line_usage.rst
- doc/src/z_references.bib
Adds documentation for the net decomposing and baseline parallel routers and removes the experimental warning.
> Update docs for parallel router

- .github/workflows/test.yml
- libs/EXTERNAL/libezgl/src/application.cpp
Now that the GCC-13 build on Ubuntu Noble is warning clean, adding it to the CI to maintain it. This is a stepping stone to moving the entire CI to Ubuntu Noble.
> [CI] Added GCC-13 on Ubuntu Noble as a Compatibility Test

- libs/librrgraph/src/io/rr_graph_uxsdcxx_serializer.h
This PR converts the switch error check with the architecture to a warning. 
@vaughnbetz
> convert switch id check with architecture to warning instead of error

- vpr/src/draw/draw_basic.cpp
We didn't allocate any space for the 'rr_node_costs' vector and accessed it directly using operator[], resulting in segfaults. This commit fixes the crash by preallocating all the needed space before any accesses.
https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/2373
> Fixed segfault in draw_routing_costs

- doc/src/vpr/command_line_usage.rst
- vpr/src/base/FlatPlacementInfo.h
- vpr/src/base/SetupVPR.cpp
- vpr/src/base/load_flat_place.cpp
- vpr/src/base/load_flat_place.h
- vpr/src/base/read_options.cpp
- vpr/src/base/read_options.h
- vpr/src/base/vpr_api.cpp
- vpr/src/base/vpr_types.h
- vpr/src/pack/pack.cpp
- vpr/src/pack/pack.h
- vpr/src/pack/verify_flat_placement.cpp
- vpr/src/pack/verify_flat_placement.h
Added the read_flat_place option to VPR's CLI. This allows the user to pass a flat placement file into the packer.
Added code to parse this file into a FlatPlacementInfo object which only verifies that the atom given in the file exists in the atom netlist.
Added code in the packer to read in the flat placement and verify that the flat placement is valid for use in the packer.
> [APPack] Added read_flat_place Option and Verifier

- doc/src/vpr/command_line_usage.rst
- vpr/src/base/read_options.cpp
- vpr/src/base/vpr_types.h
- vpr/src/place/net_cost_handler.h
place_cost_exp was set to 1 by default. This option was removed in #2799. This PR removes this command line option from documentation.
> Remove place_cost_exp from documentation

- .github/workflows/test.yml
- CMakeLists.txt
- libs/EXTERNAL/libezgl/include/ezgl/point.hpp
- libs/EXTERNAL/libezgl/include/ezgl/rectangle.hpp
- libs/EXTERNAL/libtatum/libtatum/tatum/util/tatum_strong_id.hpp
- libs/libarchfpga/CMakeLists.txt
- libs/libarchfpga/src/cad_types.h
- libs/libarchfpga/src/parse_switchblocks.cpp
- libs/libarchfpga/src/physical_types.h
- libs/librrgraph/src/base/rr_graph_utils.h
- libs/libvtrutil/src/vtr_flat_map.h
- libs/libvtrutil/src/vtr_geometry.h
- libs/libvtrutil/src/vtr_geometry.tpp
- libs/libvtrutil/src/vtr_ndoffsetmatrix.h
- libs/libvtrutil/src/vtr_strong_id.h
- libs/libvtrutil/src/vtr_strong_id_range.h
- vpr/src/base/setup_noc.h
- vpr/src/noc/noc_traffic_flows.h
- vpr/src/pack/pack_types.h
- vpr/src/place/grid_tile_lookup.cpp
- vpr/src/route/route_common.cpp
- vpr/src/route/router_lookahead_map_utils.cpp
- vpr/src/timing/PreClusterDelayCalculator.h
> Increase C++ version from 17 to 20

- doc/src/quickstart/index.rst
- install_dnf_packages.sh
Added a script that installs all needed packages to run vtr on Fedora/RHEL distributions and updated the documentation showing how to use it. This is analogous to the 'install_apt_packages.sh' script that does the same for Ubuntu/Debian. This commit didn't really change anything in the actual code but to be safe I ran the basic and strong test and didn't see any failures.
> Added dependency installer script for Fedora

- .github/workflows/nightly_test_manual.yml
This commit adds the new nightly test workflow to the list of workflows. Unfortunately to test GitHub actions workflows there has to be a version of it in the master branch, but after this PR is merged we can debug and resolve any issues in the "savi_nightly_test" branch so thankfully we don't have to test on master. This workflow can only be manually dispatched so there shouldn't be any automatic runs that could overwhelm the SAVI machines while we're working on the workflow and fixing any potential issues.
> Add initial nightly test workflow

- .gitmodules
Dependabot was having issues with our gitmodules file since we put a comment in the same line as the URL for a git submodule:
This was easily resolved by moving the comment to another line.
> [Git] Resolved Error in Dependabot

- vpr/src/base/vpr_types.h
- vpr/src/route/check_route.cpp
- vpr/src/route/edge_groups.cpp
- vpr/test/test_edge_groups.cpp
We previously checked every node in a route tree against all non-configurable RR sets, leading to O(n²) complexity. This PR limits checks to RR sets within the route tree, reducing complexity to O(n). As a result, the check_all_non_configurable_edges() function's execution time dropped from 2045s to 1.1s on the bgm benchmark in a 7-series architecture.
> Update VTR 9 branch with faster check_non_configurable_edges

- vpr/src/base/load_flat_place.cpp
Added the ability to print the max displacement from the placement reconstruction to the original flat placement.
This metric will help show another dimension to the flat placement reconstruction. Generally, if the average displacement is low, that may not be good if that means that one atom is placed way farther away than where it would like. This can really hurt quality.
I also turned the distance calculation from the Euclidean distance to the Manhattan distance. This should better represent the objective in terms of FPGAs (where the fastest path between two points is not necessarily a straight line).
I reran the results of the flat placement reconstruction on MCNC and VTR-Chain (same testing procedure as the last PR).
MCNC:
iter_num | pack_time(s) | device_util | total_wl | CPD(ns) | …
> [APPack] Added Max Displacement Metric

- vpr/src/base/vpr_api.cpp
- vpr/src/pack/pack.cpp
- vpr/src/pack/pack.h
The try_pack API required an approximation for the inter-cluster delay; however, this approximation was always being made the same way and did not need to be brought in externally. Inlined this into the packer itself to make the interface easier to work with.
This cleanup will help with integrating the APPack code into the AP flow.
> [Pack] Cleaned Up try_pack API

- vpr/src/base/vpr_context.h
- vpr/src/pack/attraction_groups.cpp
- vpr/src/pack/attraction_groups.h
- vpr/src/pack/constraints_report.cpp
- vpr/src/pack/constraints_report.h
- vpr/src/pack/greedy_clusterer.cpp
- vpr/src/pack/pack.cpp
- vpr/src/route/clock_connection_builders.cpp
- vpr/src/route/clock_network_builders.cpp
- vpr/src/route/rr_graph.cpp
- vpr/src/route/rr_graph_timing_params.cpp
After each pack, the partition regions are checked to see if any of the partition regions are overfilled. During this process, the overfilled partition regions were stored in the Floorplanning context (likely for legacy reasons). This was then read from a few lines later in another function.
Since this is only used in such a localized scenario, turned this into a local variable instead of a global variable.
> [Pack] Removed Global Overfilled Partition Regions

- .github/workflows/nightly_test.yml
Since NightlyTest is currently not working, we should stop it from running automatically everyday. We still have the option to manually run the workflow if we need to.
> Change NightlyTest workflow to not run automatically

- doc/src/vpr/command_line_usage.rst
Clarified that setting any target_ext_pin_utilization values turns off auto mode and the target pin utilization for any unspecified pin types is set to 100% in that case.
This previously confused researchers at Cornell.
> Clarified target_ext_pin_utilization command line option documentation

- vpr/src/analytical_place/full_legalizer.cpp
- vpr/src/base/blk_loc_registry.cpp
- vpr/src/base/blk_loc_registry.h
- vpr/src/base/grid_block.cpp
- vpr/src/base/grid_block.h
- vpr/src/base/vpr_api.cpp
- vpr/src/base/vpr_context.cpp
- vpr/src/base/vpr_context.h
- vpr/src/place/initial_placement.cpp
- vpr/src/place/place.cpp
- vpr/src/place/place.h
- vpr/src/place/place_util.cpp
- vpr/src/place/place_util.h
- vpr/src/place/placer.cpp
- vpr/src/place/placer.h
Cleaned up how the variables in the placement context were initialized to make it easier to initialize the placement context outside of the placement stage (Analytical Placement).
Added an optional argument to the Placer class to allow an initial placement to be passed in. This allows a different initial placement to be used without having to pull the initial placer out of the Placer class.
With this change, it should be easier to create the Detailed Placer in Analytical Placement.
> [Place] Cleaned Up Placement Context Initialization

- vpr/src/base/vpr_types.h
- vpr/src/pack/cluster_placement.cpp
- vpr/src/place/annealer.cpp
- vpr/src/timing/read_sdc.cpp
There were some legacy macro constants defined in vpr_types.h. This PR removes those and uses the standard library instead.
In particular:
- MAX_SHORT was replaced with the equivalent std::numeric_limits<short>::max()
- HUGE_POSITIVE_FLOAT was replaced with std::numeric_limits<float>::infinity(). The values are not equal but it was used similar to an infinite value. The same thing was previously done in route_common.cpp:reset_path_costs
- EPSILON was used for two different things:
- In annealer.cpp as a generic small value. Since this could possibly change QoR it was substituted with a local constexpr variable of the same value.
- For float comparision. Changed this to std::numeric_limits<float>::epsilon() which is \*not\* equal to 1.e-15 and is instead 1.19209e-07. The way float …
> Remove some defines in vpr types in favor of standard library constants

- libs/libvtrutil/src/vtr_prefix_sum.h
- libs/libvtrutil/test/test_prefix_sum.cpp
- vpr/src/place/net_cost_handler.cpp
- vpr/src/place/net_cost_handler.h
A prefix sum is a classic data structure for quickly finding the sum of any sub-region of fixed N-Dimensional array of values. It pre-computes the partial sums of regions within an array and uses that information later to save time.
This is currently used in the net_cost_handler to pre-compute number of inter-die connections.
This class can be useful in other algorithms. For example, in a Partial Legalizer in an AP flow, it can allow for quick lookups into the capacity and utilization of regions on the FPGA.
Moved the Prefix Sum class from the net_cost_handler into the VTR Util.
> [VTR][Util] Added Prefix Sum Class

- vtr_flow/arch/COFFE_22nm/k6FracN10LB_mem20K_complexDSP_customSB_22nm.xml
For the Koios and Titan benchmark suites, went through each circuit and found their minimum device size created after packing. The circuits were then categorized into different device families based on their minimum device size and their limiting block utilization. The device families were chosen to be around 1.5x larger than the previous.
Put these fixed device families into the architecture files for these benchmarks.
> [Arch] Added Fixed Architecture Sizes for Koios and Titan

- vpr/src/route/channel_stats.cpp
This PR fixes a bug that ignored y channels when computing channel utilization histogram and maximum channel utilization.
> Fixed ignored y channels in computing routing channel utilization histogram.

- vpr/src/place/net_cost_handler.cpp
- vpr/src/place/net_cost_handler.h
- vpr/src/place/placement_log_printer.cpp
When printing information about the initial placement, the wirelength cost, td cost, and CPD estimate are shown, but the wirelength estimate is not printed. I think it would be useful to include this information as well, and this PR addresses that.
> Initial Placement Wirelength Est.

- vpr/src/analytical_place/full_legalizer.cpp
The print_pb_type_count function is currently called twice: once in vpr_oad_packing and again in AAPack::legalize after loading the packing from a file. In this PR, the redundant second call is removed.
> Remove Redundant print_pb

- libs/librrgraph/src/base/rr_node_types.h
- libs/librrgraph/src/base/rr_spatial_lookup.cpp
- vpr/src/route/rr_graph2.cpp
- vpr/src/route/rr_graph2.h
This PR updates rr_node_indices_ to store RRNodeId instead of int. This change addresses issues that arise when the RR graph contains more than 2 million nodes. Additionally, it simplifies handling of invalid RRNodeId values and eliminates the need to cast unsigned int to int. This issue was flagged by @heshpdx.
> [RR Graph] RR Node Indices Value Type

- doc/src/vpr/placement_constraints.rst
Updated the placement constraint documentation to clarify that the `name_pattern` specified in the `<add_atom>` tag is interpreted as a regular expression. Also fixed a minor issue in the examples: the documentation previously suggested using `*` after a name to match any suffix (e.g., `"alu*"`), but in regex, `*` applies only to the preceding character. To correctly match any suffix, the pattern should use `.*` (e.g., `"alu.*"`).
> [Place] Fix regex pattern note in constraints doc

- vpr/src/analytical_place/analytical_placement_flow.cpp
- vpr/src/base/SetupGrid.cpp
- vpr/src/base/SetupGrid.h
- vpr/src/base/stats.cpp
- vpr/src/base/stats.h
- vpr/src/base/vpr_api.cpp
- vpr/src/base/vpr_api.h
- vpr/src/pack/pack.cpp
- vpr/test/test_vpr.cpp
Fix the placement of device utilization and netlist info printing to prevent them from being printed when the clustered netlist is not built (i.e., when AP is enabled).
> [Pack] Device Util Output 

- libs/libvtrutil/src/vtr_thread_pool.h
- vpr/src/base/ShowSetup.cpp
- vpr/src/base/read_options.cpp
- vpr/src/base/vpr_types.h
- vpr/src/route/NestedNetlistRouter.h
- vpr/src/route/NestedNetlistRouter.tpp
- vpr/src/route/netlist_routers.h
TBB's thread pool doesn't let us block in tasks, so we have to implement a custom thread pool if we want to integrate a parallel netlist router with a parallel connection router.
> Add a NestedNetlistRouter to enable integration with fine grained parallel router

- doc/src/vpr/command_line_usage.rst
- vpr/src/base/SetupVPR.cpp
- vpr/src/base/read_options.cpp
- vpr/src/base/read_options.h
- vpr/src/base/vpr_types.h
- vpr/src/place/placer.cpp
- vpr/src/place/placer.h
This PR adds a CLI parameter to VPR that allows users to skip the annealing phase and run only the quench phase. By default, this parameter is disabled, meaning the annealing phase is performed as usual.
> [Place] Add CLI Option to Skip Annealing Phase in VPR

- vpr/src/analytical_place/full_legalizer.cpp
- vpr/src/base/vpr_api.cpp
- vpr/src/pack/pack.cpp
- vpr/src/pack/pack.h
- vpr/src/pack/prepack.cpp
The AP flow makes its own prepacker which it uses throughout. However, a full legalizer in the AP flow (APPack) uses the try_pack method which creates its own prepacker. This creates two independent prepacker objects when only one is needed.
Move the construction of the prepacker object into vpr_api and have it get passed into the try_pack function.
Resolves #2950
> [Prepacker] Moved the Prepacker Out of Try Pack

- vpr/src/analytical_place/full_legalizer.cpp
- vpr/src/analytical_place/full_legalizer.h
- vpr/src/base/SetupVPR.cpp
- vpr/src/base/ShowSetup.cpp
- vpr/src/base/vpr_api.cpp
- vpr/src/base/vpr_types.h
- vpr/src/pack/cluster_util.cpp
- vpr/src/pack/cluster_util.h
- vpr/src/pack/greedy_candidate_selector.cpp
- vpr/src/pack/greedy_candidate_selector.h
- vpr/src/pack/greedy_clusterer.cpp
- vpr/src/pack/greedy_clusterer.h
- vpr/src/pack/greedy_seed_selector.cpp
- vpr/src/pack/greedy_seed_selector.h
- vpr/src/pack/pack.cpp
- vpr/src/pack/pack.h
- vpr/src/timing/PreClusterTimingManager.cpp
- vpr/src/timing/PreClusterTimingManager.h
Timing was intermixed into the packer. It appears as though the code originally was designed to recalculate the timing information every so often in the packer, but the idea was abandoned. This left timing code in disperse locations around the Packer and the timing was being recomputed every time clustering was restarted which was unecessary.
Collecting all of the timing information from the Packer into a single object called PreClusterTimingManager which abstracts all of the timing info in the Packer.
The ultimate goal is to bring this Manager class into the AP flow to be used together with the Global Placer. By sharing this manager class, the AP flow may be able to update the timing info with flat placement information to make the timing more accurate.
> [Pack][Timing] Abstracted How Timing is Used in the Packer

- doc/src/api/vtrutil/index.rst
- doc/src/api/vtrutil/parallel.rst
- libs/libvtrutil/src/vtr_thread_pool.h
Adds some doxygen docs for `vtr::thread_pool` and sets up to show them on the RTD page.
> add docs for `vtr::thread_pool`

- .github/workflows/stale.yml
- CONTRIBUTING.md
We currently have too many old and abandoned issues, which makes the issues tab not very important for maintainers. 
The added workflow will close up to 30 old issues every day, starting from the oldest ones. Issues that have been inactive for more than a year will be first marked as stale, and if they remain stale after 15 days they will be automatically closed. If for any reason you want an issue to be exempt from being close by this workflow, you can mark it as 'no-stale'. The workflow runs every day at 1PM UTC or 9AM Toronto time.
I have commented out some code that does the same thing for PRs but I think it might be too much currently and we only agreed to automatically close old issues, not PRs. I left it in there in case the situation is different in the future.
Since there's a …
> Add Github action to close stale issues

- libs/libarchfpga/src/cad_types.h
- vpr/src/pack/cluster_legalizer.cpp
- vpr/src/pack/cluster_placement.cpp
- vpr/src/pack/cluster_placement.h
- vpr/src/pack/prepack.cpp
This commit changes some functions in the packer and prepacker that used C-style arrays to use std::vector instead. Previously we used the .data() method of std::vector to pass a pointer to these functions.
> Change some internal packer APIs to not use C-style arrays

- vpr/src/base/netlist_writer.cpp
- vpr/src/base/netlist_writer.h
The SDF file generated by the post-implementation netlist writer was only using the max delays of timing connections in the timing graph. In the SDF file, it set all values of the rising and falling triples to the max delay. When using this SDF file for external timing analysis, the minimum timing (hold) paths were incorrect.
Updated the netlist writer to work with triples instead of bare delays. This allows (minimum, typical, maximum) delays to be passed through the different functions and be printed cleanly. For standard delay signals in the circuit (not setup / hold times) Tatum provides the minimum delays. These are now being printed in the SDF file and the minimum timing paths are being found correctly in the external timing analyzer.
Cleaned up some parts of the netlist printing …
> [STA] Updated SDF File Generation to Include Min Delays

- vpr/src/place/initial_placement.cpp
The old Initial Placer used in the AP flow was constructed within the initial placer of the non-AP flow. This forced the AP flow to try to place blocks one at a time with minimum displacement. This is non-ideal since blocks that were placed earlier were being getting first picks at locations, which may displace a future cluster which may be a better fit for that location.
Separated out the AP initial placement code. For AP, initial placement is done in passes.
The first pass will try to place clusters exactly at the tile that the centroid of all atoms within the cluster want to be placed (according to the global placement). Any clusters that could not be placed are reserved for the next pass.
The second pass will allow clusters to be placed within 1 tile of their centroid.
All subsequent …
> [AP][InitialPlacement] Created Isolated AP Flow

- vpr/src/pack/pack.cpp
While making the packer parallel, we removed these writes to the global context and nothing went wrong. This WIP PR does the same to VTR master. If these mutations are not needed, removing them will make the code cleaner (less "why is it doing this?") and could potentially make packing a bit faster.
The reason I think things should be mostly fine (other than passing the strong tests) is that atom_net lookup data is only ever changed after packing (add_atom_clb_net is only called after packing is done) and atom_clb is the same (set_atom_clb is only called after packing).
> Remove atom_net global context mutation from packer

- Dockerfile
- doc/src/quickstart/index.rst
- install_apt_packages.sh
Add clang-format-18 to the list of required packages
> [packages] add clang-format

- vpr/src/analytical_place/analytical_solver.cpp
After moving fixed blocks to the center of tiles, there is a very small chance that blocks go off the device due to rounding. This is such a small effect that it does not show up locally on my machine, but it shows up on CI. Clamping the positions of blocks after solving to be just within the device region.
This should fix the failure in the nightly tests.
> [AP][HotFix] Fixed Bug With Solver Putting Blocks Off-Device

- .github/workflows/stale.yml
The default 30 API call per day limit for the stale issue github action was too low. This workflow consumes 2 API calls to check if a stale issue should be closed, which means that when we mark 15 issues as stale the workflow gets stuck checking these for 15 days until they get closed. This changes the limit to 300 which should hopefully make things go a little bit faster, but not too fast.
> Increase the daily stale issue action API call limit

- vpr/src/analytical_place/partial_legalizer.cpp
- vpr/src/analytical_place/partial_legalizer.h
- vpr/src/analytical_place/primitive_vector.h
- vpr/test/test_ap_primitive_vector.cpp
Found that the mass legalizer was not spreading out the blocks well enough according to the mass.
Revistied the spatial partitioning in the mass legalizer. Before, we just cut the window in half in the larger dimension. This was fine, however it may create an inbalanced cut which can cause things to not spread well. Instead, we now search for the best partition by trying different partition lines and computing how balanced the partition is. Although this is more expensive than before, by creating more balanced partitions, it should allow the mass legalizer to converge faster. Time in the mass legalizer is also dominated by partitioning the blocks, so increasing the time to choose the partition line should not have that large of an effect anyways.
Found an oversight with how blocks were …
> [AP][MassLegalizer] Revistited Mass Legalizer

- doc/src/vpr/command_line_usage.rst
- vpr/src/base/SetupVPR.cpp
- vpr/src/base/ShowSetup.cpp
- vpr/src/base/netlist_writer.cpp
- vpr/src/base/read_options.cpp
- vpr/src/base/read_options.h
- vpr/src/base/vpr_types.h
- vpr/test/test_post_verilog_i_gnd_o_unconnected.golden.v
- vpr/test/test_post_verilog_i_nets_o_unconnected.golden.v
- vpr/test/test_post_verilog_i_unconnected_o_nets.golden.v
- vpr/test/test_post_verilog_i_unconnected_o_unconnected.golden.v
- vpr/test/test_post_verilog_i_vcc_o_unconnected.golden.v
When performing post-implementation timing analysis using OpenSTA, the generated netlist cannot use parameters since each module needs to correspond with a cell in a liberty file.
Added a command-line option which tells the netlist writer to not use parameters when generating the netlist. If a primitive cannot be generated without using parameters, it will error out.
> [STA] Added Option to Remove Parameters from Post-Implementation Netlist

- vpr/src/place/initial_placement.cpp
The cost terms in the AP initial placer were not placing fixed blocks early enough, causing other blocks to take their place and causing the initial placer to not return a solution.
Blocks which have region constraints are now placed first based on how constrained they are. More constrained blocks (can only be placed in a smaller region) will be placed first.
Also found that macros that contained fixed blocks were not observing these constraints when calculating the centroid position of the macro. For constrained macros, projected the centroid position onto the partition region to get the closest point in the partition region to the calculated centroid. This new centroid is used to then perform the placement.
Resolves #3002
> [AP][HotFix] Placed Fixed Blocks First During IP

- .github/workflows/stale.yml
This commit sets the number of days before marking issues or PRs as stale to 100 years. This number is overridden for issues to be 1 years but stays 100 years for PRs. This means that PRs effectively do not get marked as stale.
> [Hotfix][CI] Remove PR staling

- libs/libarchfpga/src/arch_util.cpp
- libs/libarchfpga/src/physical_types.h
- libs/libarchfpga/src/read_xml_arch_file.cpp
- vpr/src/analytical_place/flat_placement_mass_calculator.cpp
- vpr/src/base/netlist_walker.cpp
- vpr/src/base/read_netlist.cpp
- vpr/src/draw/intra_logic_block.cpp
- vpr/src/pack/cluster_legalizer.cpp
- vpr/src/pack/cluster_util.cpp
- vpr/src/pack/lb_type_rr_graph.cpp
- vpr/src/pack/output_clustering.cpp
- vpr/src/pack/pb_type_graph.cpp
- vpr/src/pack/pb_type_graph_annotations.cpp
- vpr/src/pack/prepack.cpp
- vpr/src/power/power_sizing.cpp
- vpr/src/util/vpr_utils.cpp
- vpr/test/test_vpr.cpp
This PR adds two new functions to the p_tb_type struct, is_root and is_primitive and changes the users to use these new functions instead of writing the logic every time. There's now less code duplication and the code a bit cleaner and more understandable.
I did have two questions about this part of code:
1.  What is the meaning of a t_pb without a name? There's a couple of places that call is_primitive and see if the associated t_pb doesn't have a name which could be cleaned up further
2. Regarding the added TODO comment in cluster_legalizer.cpp:836 of this PR: Should it be an assert?
> Add functions to p_tb_type for checking if it's root or primitive

- vtr_flow/parse/parse_config/common/vpr.place.txt
The wirelength from the initial placement is printed in scientific notation (e.g., `Initial placement BB estimate of wirelength: 2.5437e+07`), but the pattern was expecting an integer. I updated the pattern to accept any numeric format.
> Fix the regex pattern for initial placement WL

- vpr/src/timing/read_sdc.cpp
The get_clocks command is used in an SDC file to reference a set of clocks by name using a regex string. The code to do this tries to produce a warning if get_clocks is used on a regex string and no clocks could be found. The issue is that the code to do this was mistakenly producing this warning for each clock in the circuit. For example, if we had {clk1, clk2, clk3} and we wanted to do "get_clocks {clk3}", we will get two warnings since clk1 and clk2 did not match.
Fixed this by moving the warning out of one loop nest.
I noticed this when I was looking at the output of the directrf circuit and saw weird warnings:
This was strange since we clearly create the clocks with those names:
I think this was just a mistake and, since it was a warning, no one noticed.
> [Tatum][Parse] Fixed Extraneous Warning With get_clocks

- doc/src/vpr/command_line_usage.rst
- vpr/src/base/SetupVPR.cpp
- vpr/src/base/ShowSetup.cpp
- vpr/src/base/netlist_writer.cpp
- vpr/src/base/netlist_writer.h
- vpr/src/base/read_options.cpp
- vpr/src/base/read_options.h
- vpr/src/base/vpr_api.cpp
- vpr/src/base/vpr_types.h
Added an option to have VPR generate an SDC file containing the timing commands required for an external timing analysis of the post- implementation netlist to match VPR's timing analysis.
> [STA] Generating SDC Commands Post-Implementation

- .github/workflows/nightly_test_manual.yml
This PR uploads the .log and parse_results files of the nightly tests as artifacts. This should make it possible to see the details of a nightly test run without needing to login to the runner or re-running the tests on a machine you have access to.
> Add artifact upload to nightly test workflow

- vpr/CMakeLists.txt
- vpr/src/analytical_place/analytical_placement_flow.cpp
- vpr/src/analytical_place/analytical_solver.cpp
- vpr/src/analytical_place/analytical_solver.h
- vpr/src/analytical_place/global_placer.cpp
- vpr/src/analytical_place/global_placer.h
- vpr/src/base/SetupVPR.cpp
- vpr/src/base/vpr_types.h
The Eigen solver has the ability to use OpenMP to run the solver computations in parallel. Made the AP flow use the num_workers option to set the number of threads that Eigen can use.
VPR did not have the ability to build with OpenMP in its CMAKE. Added an option to the CMAKE to allow the user to enable OpenMP.
Resolves #3030 
Currently running the VTR circuits using 4 threads, will show the results. As a preview, MCML's Global Placement went from 141 seconds to 92 seconds on 4 threads.
I made OpenMP disabled by default for now since only the AP flow uses OpenMP. Perhaps we can enable this by default only when AP is enabled or just always enable it.
> [AP][Solver] Enabled Parallel Eigen

- .github/scripts/install_dependencies.sh
- .github/scripts/install_jammy_dependencies.sh
- Dockerfile
- install_apt_packages.sh
The install_apt_packages.sh script is no longer backward compatible with older versions of Ubuntu due to the dependency on clang-format-18.
Added an if statement to check if the distribution can support clang-format-18 and only installing it if it can.
Added this script to the CI build process so it can always be tested within the CI to prevent future regression.
> [Infra] Updated Install Packages Script For Backwards Compatibility

- libs/librrgraph/src/base/rr_graph_builder.cpp
- libs/librrgraph/src/base/rr_graph_view.h
- libs/librrgraph/src/base/rr_spatial_lookup.cpp
- libs/librrgraph/src/base/rr_spatial_lookup.h
- libs/librrgraph/src/io/rr_graph_uxsdcxx_serializer.h
- vpr/src/route/clock_network_builders.cpp
- vpr/src/route/rr_graph.cpp
- vpr/src/route/rr_graph2.cpp
- vpr/src/route/rr_graph2.h
`RRSpatialLookup` swaps the x and y coordinates of CHANX wires when putting them in the `rr_node_lookup` data structure, and `find_node()` function swaps them as well. This PR gets rid of these swaps.
Addresses #355 and #2978
> Clean up confusing rr-node lookup convention for x/y location of CHANX nodes

- vpr/src/pack/atom_pb_bimap.cpp
- vpr/src/pack/cluster_feasibility_filter.cpp
- vpr/src/pack/cluster_feasibility_filter.h
- vpr/src/pack/cluster_placement.cpp
- vpr/src/pack/cluster_router.cpp
- vpr/src/pack/cluster_router.h
- vpr/src/pack/cluster_util.cpp
- vpr/src/pack/pack_report.cpp
- vpr/src/pack/pack_types.h
- vpr/src/pack/pb_type_graph.cpp
- vpr/src/pack/pb_type_graph.h
- vpr/src/pack/pb_type_graph_annotations.cpp
- vpr/src/pack/pb_type_graph_annotations.h
- vpr/src/pack/sync_netlists_to_routing_flat.h
- vpr/src/pack/verify_flat_placement.cpp
Went through the header files in the pack folder and resolved any unused header files.
> [Infra] Cleaned Up Header Files in Pack Folder

- vpr/src/place/compressed_grid.h
- vpr/src/place/grid_tile_lookup.cpp
- vpr/src/place/grid_tile_lookup.h
- vpr/src/place/initial_noc_placement.cpp
- vpr/src/place/move_transactions.h
- vpr/src/place/move_utils.cpp
- vpr/src/place/noc_place_checkpoint.h
- vpr/src/place/place_checkpoint.h
- vpr/src/place/place_constraints.h
- vpr/src/place/place_util.h
- vpr/src/place/placement_log_printer.h
- vpr/src/place/placer_breakpoint.cpp
- vpr/src/place/placer_breakpoint.h
More cleanups in the Place folder.
> [Infra] Cleaned Up Header Files in Place Folder

- vpr/src/route/parallel_connection_router.h
- vtr_flow/parse/qor_config/qor_fg_parallel_router_fixed_chan_width.txt
The fine-grained parallel router was originally built before VTR upgraded to C++20, so we had to roll our own barrier. We originally had two barriers: spin barriers (thread spin on a lock while waiting) and a "mutex" barrer (where threads wait on a condition variable and potentially went to sleep).
Through experimentation, found that the choice of barrier implementation did not matter; however, the standard barrier provides slight performance improvements for very long routes and has a much cleaner interface.
Moved the FG parallel router to the standard barrier. The old implementations are left in as classes in case c++20 is not preferred for some users.
Also added a QoR script to make parsing FG parallel router runs easier.
> [FGParallelRouter] Updated Barrier to C++20 Std Barrier

- utils/fasm/src/fasm.cpp
- vpr/src/base/read_netlist.cpp
- vpr/src/route/route_utils.cpp
Found a bug within FASM's wire generation where it uses the index of the output pin to create the wire instead of the index of the input pin.
This stemmed from some confusing code which both verified that the wire was being used and returning the first valid pin. It just so happens that it checked the outputs first and returned the output pin instead.
Cleaned up the code and added more error checking to prevent issues like this in the future.
> [FASM] Fixed Bug With Wire Creation

- .github/workflows/test.yml
Since the CI always installs oneTBB and the execution engine is set to auto, I found that the CI always tested with the tbb execution engine. Some users may not have oneTBB installed for one reason or another and we need to ensure that VTR always builds.
Added a CI test which sets the parallel execution engine to serial for Tatum and VPR.
> [CI] Added Serial Execution Engine Test

- vpr/src/draw/draw_basic.cpp
https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/3062
using IPAClient app, drawing contour = on, selecting '"crit path routing"' mode
- [ x] Bug fix (change which fixes an issue)
> fix Draw crit path contour for crit path routing mode

- .readthedocs.yaml
---
Readthedocs was not correctly running sphinx autodoc on our python modules because of broken imports.  We were instructing readthedocs to install the `docs/requirements.txt`, but not the base `requirements.txt`.  The latter includes packages that are used by our Python scripts.  autodoc cannot document the Python files without having the necessary libraries available.
Fixes #2059
> Fixing documentation build

- libs/libarchfpga/src/logic_types.cpp
- libs/libarchfpga/src/logic_types.h
- libs/libarchfpga/src/read_fpga_interchange_arch.cpp
- vpr/src/base/atom_netlist.cpp
- vpr/src/base/atom_netlist.h
- vpr/src/base/atom_netlist_utils.cpp
- vpr/src/base/check_netlist.cpp
- vpr/src/base/clustered_netlist.cpp
- vpr/src/base/clustered_netlist.h
- vpr/src/base/read_blif.cpp
- vpr/src/base/read_circuit.cpp
- vpr/src/base/read_interchange_netlist.cpp
- vpr/src/pack/cluster_util.cpp
- vpr/src/pack/cluster_util.h
- vpr/src/pack/greedy_clusterer.cpp
- vpr/src/pack/prepack.cpp
- vpr/src/pack/prepack.h
Created static constexpr references to the library model IDs (such as input, output, names, and latch). It is very common to reference these models during execution of VPR. Often we would search for these models in the LogicalModels structure; however, these model IDs will always be the same.
By storing static references to these IDs, the compiler can easily optimize parts of the code which need to check if a model ID is an input/output for example.
> [LibArchFPGA] Added Library Model IDs as constexpr

- vpr/src/base/netlist_writer.cpp
- vpr/src/base/netlist_writer.h
- vpr/src/base/vpr_api.cpp
Through experimentation, found that dedicated clock routing worked with the external STA path. Removed the error check for this.
See #3027 
This does not resolve the issue above quite yet, since I found that issue to be unrelated to dedicated clock routing.
> [STA] Enabled Dedicated Routing SDC Generation

- vpr/src/base/blk_loc_registry.cpp
- vpr/src/base/grid_block.cpp
- vpr/src/base/grid_block.h
- vpr/src/place/noc_place_checkpoint.cpp
This PR removes the unused 'usage' member from t_grid_blocks and all associated routines  of set_usage, increment_usage, decrement_usage (get_usage changed as below).
Changes:
- Rewrote `get_usage()` to dynamically count valid blocks based on sub-tile occupancy.
- Improves maintainability and eliminates risk of stale or inconsistent 'usage' data.
This PR resolves the issue #1607
> Clean up the usage tracking in grid blocks.

- vpr/src/analytical_place/analytical_solver.h
- vpr/src/analytical_place/full_legalizer.h
- vpr/src/base/ShowSetup.h
- vpr/src/pack/greedy_clusterer.h
- vpr/src/pack/pack_types.h
- vpr/src/place/timing/place_timing_update.h
The Clang builds were warning that there were several forward declarations of structs which were supposed to be classes and vice-versa.
This is not necessarily a problem since in C++ classes and structs end up being basically the same from the compiler's perspective, but its still incorrect. Fixed the cases I could see in the Clang builds.
> [Infra] Fixed False Forward Declarations

- doc/src/tutorials/timing_analysis/index.rst
- vpr/src/base/netlist_writer.cpp
While presenting my tutorial on post-implementation timing analysis, I found that the SDC file generated did not look quite right. It was functionally correct, but some of the new-line characters were missing.
Added the missing new line characters.
Also added link to the tutorial video to the tutorial documentation.
> [STA] Updated Tutorial

- doc/src/vpr/command_line_usage.rst
Documenting a missing command line option and clarifying that other placement reading options take .place format (clustered) placements.
> vpr command line doc: add --read_initial_place_file and clarify file formats for place options

- .github/workflows/test.yml
- dev/vtr_test_suite_verifier/test_suites_info.json
- dev/vtr_test_suite_verifier/verify_test_suites.py
Found that we were regressing on many features in VTR due to tasks being
added to the appropriate test suite directory, but not being included in
the necessary task list. As such, it appeared as though the tests were
being run, but in reality they were not.
Added a script which will be run by the CI which will verify that all of
the test suites that we care about have all their tasks in the
appropriate task list.
From this tool, found many tasks which were not in the task lists.
Marked these tasks as "ignored" for now. These should be handled in a
separate PR.
> [CI] Added Test Suite Verification to CI

- vpr/src/base/SetupVPR.cpp
- vpr/src/base/read_options.cpp
- vpr/src/base/read_options.h
- vpr/src/base/vpr_api.cpp
- vpr/src/base/vpr_types.h
There may be cases where the user doesn’t want to sync the netlist to the routing results. This situation may especially arise when the flat router is enabled and global signals are not routed. Since the pins reserved for global nets are not visible to the flat router, it may use them, which can lead to crashes.
For this case, the current workaround is to enable skipping netlist syncing. However, the long-term solution would be to make these pins visible to the flat router.
> Skip syncing netlist to routing resutls

- vpr/src/analytical_place/global_placer.cpp
- vtr_flow/parse/qor_config/qor_ap_fixed_chan_width.txt
The global placer printed the post-GP estimated wirelength, but it did not print the post-GP CPD or TNS. Added these values to the log file.
Also updated the QoR parse script that I use internally to grab this information throughout the flow to track timing.
> [AP] Updated Timing Logging

- doc/src/vtr/run_vtr_flow.rst
- vtr_flow/scripts/python_libs/vtr/parmys/parmys.py
Updating VTR Docs -include Command
Updated run_vtr_flow docs and VTR Flow Python Library to have documentation for the -include command to pass in more than one circuit to run_vtr_flow.
Related to issue #1774
Removes the question "How can I run multiple circuits on the same architecture in one shot with run_vtr_flow?"
Ran CI tests to ensure doc building still works and had updated documentation revised by VTR mentors.
- [ x] I have updated the documentation accordingly
> Updating VTR Docs -include Command

- CMakeLists.txt
- blifexplorer/CMakeLists.txt
- libs/libarchfpga/CMakeLists.txt
- odin_ii/CMakeLists.txt
- utils/fasm/CMakeLists.txt
- utils/route_diag/CMakeLists.txt
- vpr/CMakeLists.txt
VTR is built with IPO by default. IPO tends to reveal false warnings in the compiler. This was causing many warnings when VTR was built by default.
Most of these warnings were coming from libarchfpga due to how it allocates arrays. Suppressed these warnings when IPO is turned on.
There are still link-time warnings coming from CapNProto; however, since this library is external, it is a harder to supress these warnings. We could suppress the warnings by globally setting the link option to ignore the warning, but that may be overkill.
Edit:
See discussion below, decided to globally suppress all known IPO warnings in VTR.
> [Build] Resolved All IPO Warnings in VTR

- CMakeLists.txt
Last PR had a typo in the comment. Fixing it.
> [Cmake] Fixed Typo in Cmake Comment

- vpr/src/analytical_place/global_placer.cpp
- vpr/src/analytical_place/partial_placement.cpp
- vpr/src/analytical_place/partial_placement.h
- vtr_flow/parse/qor_config/qor_ap_fixed_chan_width.txt
After a recent change where we are ignoring high-fanout nets in the global placer, this caused the high-fanout nets to also be ignored during wirlength estimation in the global placement.
This wirelength is used in the global placer to decide when to stop and to print logs to the user. I would like to continue to ignore these nets when computing the objective of the global placer since it is the wirelength of the nets which are not ignored; however, for the user, I would like them to see a more accurate estimation of the wirelength.
Created a function which tries to estimate the wirelength of the global placement solution assuming all blocks can be placed exactly where their flat placement wants them to be placed.
See https://github.com/verilog-to-routing/vtr-verilog-to-routing/pull/3137 …
> [AP][GP] Added Post-Global Placement Wirelength Estimation

- vpr/src/analytical_place/analytical_solver.cpp
- vpr/src/analytical_place/analytical_solver.h
After investigating some of the slowest running testcases, I realized that we were not handling disconnected blocks in the solver.
Especially after we started thresholding out high-fanout nets, some circuits were taking far longer to solve than they should. They especially took a long time to set up the matrices. After investigating, I realized that there were many blocks which we completely disconnected from the rest of the circuit. There is no reason to optimize the location of these blocks since the AP objective is formulated based on net connectivity. As such, these disconnected blocks should be completely ignored during placement.
Ignoring these blocks reduces the number of variables in the A matrix, which can greatly improve runtime. Early results on Titan show up to a 3.5x …
> [AP][Solver] Ignored Disconnected Blocks in AP Solver

- libs/librrgraph/src/base/rr_graph_builder.cpp
- libs/librrgraph/src/base/rr_graph_builder.h
- libs/librrgraph/src/base/rr_graph_storage.cpp
- libs/librrgraph/src/base/rr_graph_storage.h
- libs/librrgraph/src/base/rr_graph_view.h
- libs/librrgraph/src/io/gen/rr_graph_uxsdcxx.h
- libs/librrgraph/src/io/gen/rr_graph_uxsdcxx_capnp.h
- libs/librrgraph/src/io/gen/rr_graph_uxsdcxx_interface.h
- libs/librrgraph/src/io/rr_graph.xsd
- libs/librrgraph/src/io/rr_graph_uxsdcxx_serializer.h
- libs/libvtrcapnproto/gen/rr_graph_uxsdcxx.capnp
- vpr/src/route/rr_graph_generation/rr_graph.cpp
While ago, we added a new attribute called "twist" to handle tileable rr-graph ptc numbers in [this PR](https://github.com/verilog-to-routing/vtr-verilog-to-routing/pull/2378). As OpenFPGA branch has fixed the issue in another way, this attribute is no longer needed, thus I cleaned up the code and remove all unnecessary functions that uses this values.
> Removed twist attribute from RR graph 

- vpr/src/base/netlist_writer.cpp
The Netlist Writer is used to write the post-implementation netlist and SDF files for use in post-implementation timing analysis. While working with this tool on blocks with multi-port, registered output pins, I found that the SDF file generated was not correct.
The issue was that the Netlist Writer always assumed that any registered output ports had only 1 bit, so the SDF file did not contain delays per output port causing it to be invalid.
This was easy to fix by making clock to q paths timing arcs instead so that the pin IDs in each port can be passed to the SDF writer and the SDF writer can annotate the correct delays.
> [NetlistWriter] Fixed Tcq SDF Writing for BlackBoxs

- doc/src/vpr/command_line_usage.rst
- vpr/src/analytical_place/detailed_placer.cpp
- vpr/src/base/CheckSetup.cpp
- vpr/src/base/SetupVPR.cpp
- vpr/src/base/read_options.cpp
- vpr/src/base/read_options.h
- vpr/src/base/vpr_types.h
- vpr/src/place/annealer.cpp
- vpr/src/place/annealer.h
- vpr/src/place/place.cpp
- vpr/src/place/placer.cpp
- vpr/src/place/placer.h
Since the AP flow produces an initial placement that has 4x improved estimated wirelength and 2x improved CPD, the initial temperature of the annealer is too high. From experimentation, I have found that reducing the initial temperature in half improves quality slightly and reduces runtime.
Added an option to the Placer to scale up or down the initial temperature. The default flow just sets this scale to 1.0, but the AP flow sets this scale to 0.5 currently.
I have also exposed this option to the command-line so this option can be swept more easily.
Results on VTR with AP (timing driven, no fixed IOs):
Init T Scale | Post-DP HPWL | Post-DP CPD | Final Wirelength | Final CPD | DP Run Time | Routing Run Time | Total Run Time
-- | -- | -- | -- | -- | -- | -- | --
1.0000 | 1.00 | 1.00 | 1.00 …
> [AP][DP] Added Option to Scale Init T in Annealer

- vpr/src/analytical_place/analytical_solver.cpp
- vpr/src/analytical_place/analytical_solver.h
- vpr/src/analytical_place/global_placer.cpp
The B2B solver originally used a simple net weighting model to incorperate timing into the objective. This works well, but a more direct approach to timing should provide a better solution.
Added extra edges to the B2B formulation which encode per-connection delays into the objective.
Simply, these edges incentivice the solver to shrink the distance between driver and sinks where shrinking that distance would improve the delay the most (focusing more on currently critical edges).
To encode this objective, I compute the instantaneuous derivative of the delay of an connection with respect to the distance (normalized such that the units are not in seconds) and use that as a weight for a pin to pin connection between each driver and its sinks.
More tuning is likely need to find good factors …
> [AP][Solver] Per-Connection Timing Optimization

- vpr/src/pack/pack.cpp
The packer iteratively restarts itself with different options if the packer fails to find a dense enough clustering. The way this was written was very hard to follow and was error prone.
Rewrote the iterative packer code to be more like a state-machine. This makes it easier to add new states in the future and maintain the current states.
My goal here is to be accurate to what the packer was doing before (i.e. no results will change, the packer will behave exactly as it did before). So some of the state transitions may make you say "why do that, why not this?"; those changes will come in a future PR. This is just cleanup.
> [Packer] Reorganized Iterative Packer Algorithm

- vpr/src/route/router_lookahead/router_lookahead_report.cpp
The router lookahead report may be confusing to people who are not familiar with what the profiling code is doing to make that report.
Added a preamble section to the report which explains what is being performed and how to interpret the data.
The lookahead report now looks like this:
> [RouterLookahead] Added Preamble Section to Profile Report

- vpr/src/base/netlist_writer.cpp
The nightly test for the netlist writer was failing due to changes in the clock to Q delays. After some digging, I found that there was an oversight in the netlist writer code when it generates ram black boxes.
Someone hard-coded the name of the clock port to "clock", when in reality the port's name is "clk". This was a very simple fix.
This resolves the failures in NightlyTest2:
> [NetlistWriter] Fixed Failing Nightly Test

- vpr/src/route/route_utils.cpp
The rhel9 build of VTR is unable to resolve the "onetbb" prefix in the include path for tbb. This is easily resolved by just removing this prefix.
Other tbb includes do not use this prefix. This is only found in this one place.
> [Build] Fixed Issue in Rhel9 Build

- .github/workflows/test.yml
I expect the sanitized test to be the tall pole for the speed of the CI due to its long run time on the testcases. After investigating with Vaughn, we realized that this test was using the debug build of VTR. This was likely making it much slower than it needed to be.
To improve the speed of this test, moved it to use the release build. We still want symbols to give good error messages.
> [CI] Moved Sanitized Test from Debug to RelWithDebInfo

- .github/workflows/test.yml
The compatibility CI builds are taking longer than expected, especially
for the GCC builds. They appear to be having issues with CCache.
Trying to clean up the tests to speed them up.
Removed the GCC-11 compatibility test since it was already being tested
in the Jammy compatibility test.
Removed Odin from the compatibility test since it is not the default
flow.
Cleaned up some enviornment variables.
I found that using a release build caches much better than a debug
build. This ends up saving way more time than we gain from using a debug
build.
> [CI] Speeding Up Compatibility Builds

- vpr/src/analytical_place/analytical_solver.h
- vpr/src/analytical_place/global_placer.h
Tuned some of the parameters for the global placement stage. The goal of this tuning was to speed up the global placer as much as reasonable, while retaining similar quality.
Reduced the B2B convergence gap slightly to allow the B2B solver to converge on a more accurate solution.
Reduced the number of B2B convergences required before stopping from 2 to 1. I found that this did not provide as much quality, and reducing this greatly improved the solver's speed.
Reduced the max number of CG iterations. This should further improve the speed of the solver.
Reduced the relative gap between the upper and lower bound solutions in the global placer from 5% to 1%.
> [AP][GP] Tuning Parameters

- .github/workflows/test.yml
Explicitly installed the apt packages required for the tests and the
python requirements.
In the future, we should update the version of pylint and black used by
the CI to allow us to use a more up to date version of Python for
linting. It looks like linting has to be done on CI which is not ideal.
> [CI] Updated Install Dependencies for Format Tests

- vpr/src/pack/greedy_seed_selector.cpp
When echo file generation is enabled, a crash occurs during molecule printing. This is caused by not checking the validity of an atom's block while iterating over the atoms in a molecule. This PR adds a check to ensure the block is valid before accessing it, preventing the crash.
> Skip Invalid Atom Blocks

- vpr/src/place/move_generators/simpleRL_move_generator.cpp
Found that it may be possible for a random move to not be selected due to numerical precision issues. Added a check to handle this.
See issue #3242
> [Place][MoveGenerator] Fixed Rare Issue

- vpr/src/base/read_blif.cpp
Moves BLIF model existence check in arch.xml from end of BLIF parse to point where corresponding blackbox model is read. 
Throw an error if the blackbox BLIF model was not found in the architecture at the end of parsing.  This gives the name of the mismatching blackbox model but was pointing the user to the end of BLIF file.
Throw an error when we read that current model is a blackbox model and not found in architecture. This gives the name of the mismatching blackbox model and also points the user to line where current model is defined to be a blackbox model.
Some BLIF errors point to the wrong line number (end of file) - https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/3215 
The throws checking the existence of a main model (we should have a non-blackbox) and checking …
> Move BLIF model existence check in architecture from end of BLIF parse to corresponding blackbox definition line

- vtr_flow/misc/yosys/slang_filelist.tcl
- vtr_flow/misc/yosys/synthesis.tcl
Removed all top module mapping code in synthesis.tcl and slang_filelist.tcl for Slang.
Since top module mapping isn't required for slang, any unused code for this that made it to master needs to be removed to reduce clutter.
Passes the system verilog regression test that uses slang as a parser.
> Removing Top Module Mapping With Slang

- libs/libarchfpga/src/physical_types.h
- libs/librrgraph/src/base/rr_edge.h
- libs/librrgraph/src/base/rr_switch.h
- vpr/src/route/rr_graph_generation/rr_graph_switch_utils.h
- vpr/src/route/rr_graph_generation/rr_graph_tile_nodes.cpp
- vpr/src/route/rr_graph_generation/rr_graph_tile_nodes.h
Addresses Vaughn's comments from #3281
> Address remaining comments from #3281

- vpr/src/draw/draw.cpp
#3249 moved function calls that update the graphics to a function that is only called when the stage changes. This PR brings them back to where they were before #3249 was merged.
> Bugfix: Update graphics after each SA outer loop iteration
