vpr/SRC/base/read_place.c

Implementation of solution I propose in "problem when using --fix_pins option #123"

Assign 'z' index for fixed IO placement

---

vpr/SRC/route/rr_graph.c

3-rd index of array added to print value, instead of pointer

fix incorrect value printing

---

doc/src/vpr/file_formats.rst

Two mistakes were found. First mistake still needs a fix. ( Thanx for the hard work! )
1) Incomplete sentence. It seems like the sentence is incomplete.
2) Simple typo fix. not -> note

refactoring file_formats.rst

---

ODIN_II/README.txt

Updating Readme file with pre-requisites and cmake build instructions

ODIN Readme file update

---

ODIN_II/README.txt

Adding a per-requisite package
Updating ODIN make command

Updating README file

---

ODIN_II/SRC/odin_ii.c

same as previous commit, forgot to merge changes to odin_ii.c

remove deleted files from include

---

ODIN_II/SRC/lib_ast/ast_util.c
ODIN_II/SRC/odin_util.c

fix for warning from last commit

fixed warnkng

---

ODIN_II/SRC/PARSE_TOOL/verilog_preprocessor.cpp
ODIN_II/SRC/odin_util.cpp
ODIN_II/SRC/odin_util.h

Fixing Bug 173

---

ODIN_II/SRC/lib_ast/ast_elaborate.cpp
ODIN_II/SRC/lib_ast/ast_util.cpp
ODIN_II/SRC/lib_ast/parse_making_ast.cpp
ODIN_II/SRC/lib_blocks/adders.cpp

Fixing few ODIN warning messages

Fixing few ODIN warning messages

---

ODIN_II/SRC/lib_netlist/netlist_create_from_ast.cpp

Resolving few more warning messages

Resolving few more warning messages

---

ODIN_II/SRC/odin_util.cpp
README.md

- Convert C style string in `make_string_based_on_id` to a C++ string
- Update Contributors Section in `README.md`, add myself as a Contributor
- Correct function name, `convert_int_to_bit_string`, in comment for function `convert_long_long_to_bit_string`
Continuing Odin C++ Conversion
Modernizing and Cleaning up Odin
Ran `ODIN_II/verify_full.sh`, `run_quick_test.pl`, `vtr_reg_basic`and `vtr_reg_strong` regression tests with no related qor test or run failures.

[Odin] C++ Conversion changes and Cleanup

---

libs/libarchfpga/src/echo_arch.cpp

Before this pull request every segment would contain the sb/cb values of the first segment. After this change it correctly outputs the sb/cb values for each segment.

libarchfpga: Fix segment list output in echo file.

---

doc/src/vpr/file_formats.rst

Fixed some small white space issues inside [file_formats.rst](docs/src/vpr/file_formats.rst).

Small white space fixes to documents.

---

.travis.yml
.travis/after_failure.sh
.travis/after_success.sh
.travis/common.sh
.travis/install.sh
.travis/script.sh

* Builds vtr.
* Runs the vtr_reg_basic tests.
* Has pretty colors.
As travis runs on pull requests **before** you merge them into the repo, this is the **first step** towards adding style checks to the repository which make sure that the code style continues to improve. It also makes sure that at least basic tests will pass when you merge the change.
Travis CI is a free CI system for open source projects. It enables building and testing of open source projects as part of the pull request and gives you a signal about if the build completed successfully - you can see this on another one of my projects in the screenshot below;
The actual travis run output is shown below and can also be found [here](https://travis-ci.org/mithro/vtr-verilog-to-routing)
Step 1 - [Log into Travis …

infra: Adding Travis CI build to vtr.

---

doc/src/tutorials/timing_simulation/index.rst

Signed-off-by: John McMaster <johndmcmaster@gmail.com>
http://docs.verilogtorouting.org/en/latest/tutorials/timing_simulation/#generating-the-post-implementation-netlist
Clearly says to use the "--gen_post_synthesis_netlist" option but the example has "-gen_post_synthesis_netlist". Also verified the former is only accepted by the actual tool
Make tutorial easier to follow
Ran make html
Opened ./_build/html/tutorials/timing_simulation/index.html
Looks fixed
Pretty isolated
I didn't run any other tests, but I can if you really think I should

Timing sim tutorial: add missing dash

---

README.developers.md

Signed-off-by: John McMaster <johndmcmaster@gmail.com>
Some of the examples use "./run_reg_test" instead of the correct file name "./run_reg_test.pl"
Change two entries
N/A
Makes it easier to read
Viewed in markdown editor
N/A
N/A

README.developers: add missing .pl

---

libs/libarchfpga/src/read_xml_arch_file.cpp

* Improves error message for CB/SB lists by including the actual numbers.
* Strip all trailing whitespace in the file.

Improve CB/SB list errors

---

CMakeLists.txt
ODIN_II/SRC/lib_ast/parse_making_ast.cpp
libs/libarchfpga/src/physical_types.h
libs/libvtrutil/src/vtr_flat_map.h
libs/libvtrutil/src/vtr_strong_id.h
vpr/src/base/netlist_writer.cpp
vpr/src/base/vpr_types.h
vpr/src/power/power_lowlevel.cpp
vpr/src/power/power_sizing.cpp
vpr/src/util/vpr_utils.cpp

Fixing a bunch of small typos in the vtr code base.

A bunch of small typo fixes

---

ace2/CMakeLists.txt

ace2: Define __STDC_XXX_MACROS.

---

doc/src/tutorials/arch/timing_modeling/index.rst

Some minor fixes to issues I found in the timing modeling tutorial.

Small fixes to timing modeling tutorial

---

ODIN_II/SRC/include/odin_util.h
ODIN_II/SRC/odin_util.cpp
ODIN_II/SRC/read_xml_config_file.cpp
ODIN_II/SRC/verilog_preprocessor.cpp

Remove the allocation and move the temporary line on the stack
Memory leaks in odin
Reduce memory leaks in odin
Used odin regression pre-commit test suite

Fixed memory leak in verilog_preprocessor.cpp

---

ODIN_II/SRC/verilog_preprocessor.cpp

ODIN_MEMLEAK: fix mem leak with free

---

ODIN_II/SRC/netlist_create_from_ast.cpp

ODIN_MEMLEAK: Leak ast to netlist str free

---

ODIN_II/SRC/partial_map.cpp

ODIN_MEMLEAK: freed nnode in instantiate_bitwise_logic

---

ODIN_II/SRC/parse_making_ast.cpp

ODIN_MEMLEAK: freed replaced symbol nodes

---

ODIN_II/SRC/netlist_create_from_ast.cpp

ODIN_MEMLEAK: freed nnodes associated with BLOCKING_STATEMENTS

---

ODIN_II/SRC/netlist_create_from_ast.cpp

ODIN_MEMLEAK: freed temp_string in ast_to_netlist

---

ODIN_II/SRC/partial_map.cpp

ODIN_MEMLEAK: freed mux nodes in partial_map

---

ODIN_II/SRC/netlist_create_from_ast.cpp

ODIN_MEMLEAK: freed potential_clocks in terminate_registered_assignment

---

ODIN_II/SRC/multipliers.cpp
ODIN_II/SRC/netlist_utils.cpp
ODIN_II/SRC/partial_map.cpp

ODIN_MEMLEAK: freed input pin names

---

ODIN_II/SRC/partial_map.cpp

ODIN_MEMLEAK: freed node in instantiate_EQUAL

---

ODIN_II/SRC/netlist_create_from_ast.cpp

ODIN_MEMLEAK: freed nnodes associated with non-blocking statements

---

ODIN_II/SRC/netlist_create_from_ast.cpp

ODIN_MEMLEAK: freed unused pin names

---

ODIN_II/SRC/netlist_create_from_ast.cpp

ODIN_MEMLEAK: freed unused BLOCKING_STATEMENT nodes

---

README.developers.md

Small fixes to README.developers.md file, no functional changes.

Minor fixes to README.developers.md file.

---

ODIN_II/SRC/netlist_utils.cpp

ODIN_MEMLEAK: fixed pin name mixup when freeing

---

ODIN_II/SRC/include/netlist_utils.h
ODIN_II/SRC/netlist_create_from_ast.cpp
ODIN_II/SRC/netlist_utils.cpp

ODIN_MEMLEAK: added free_nnet function

---

ODIN_II/SRC/netlist_create_from_ast.cpp
ODIN_II/SRC/netlist_utils.cpp
ODIN_II/SRC/partial_map.cpp

ODIN_MEMLEAK: added free_npin function

---

ODIN_II/SRC/netlist_create_from_ast.cpp

ODIN_MEMLEAK: freed overwritten pin names

---

ODIN_II/SRC/netlist_create_from_ast.cpp

ODIN_MEMLEAK: freed if logic expressions

---

ODIN_II/SRC/memories.cpp

ODIN_MEMLEAK: freed pin names before null assignment

---

ODIN_II/SRC/implicit_memory.cpp

ODIN_MEMLEAK: freed memory name

---

ODIN_II/SRC/parse_making_ast.cpp

ODIN_MEMLEAK: freed children array of freed module instance node

---

ODIN_II/SRC/parse_making_ast.cpp

ODIN_MEMLEAK: freed ref name for new module instance

---

ODIN_II/SRC/parse_making_ast.cpp

ODIN_MEMLEAK: freed unused nodes in newModule

---

ODIN_II/SRC/parse_making_ast.cpp

ODIN_MEMLEAK: freed module connection nodes

---

ODIN_II/SRC/partial_map.cpp

ODIN_MEMLEAK: freed unused nodes during operation instantiations

---

ODIN_II/SRC/netlist_create_from_ast.cpp

ODIN_MEMLEAK: freed nnodes related to NON_BLOCKING_STATEMENT nodes

---

ODIN_II/SRC/partial_map.cpp

ODIN_MEMLEAK: freed unused nnets

---

README.developers.md

Small fix to the documentation.

docs: Fix the external_subtree documentation.

---

vpr/src/place/timing_place_lookup.cpp

Just look at it :)
Just look at it :)

Fix source/sink mix-up

---

ODIN_II/SRC/parse_making_ast.cpp

ODIN_MEMLEAK: removed unnecessary calloc

---

ODIN_II/SRC/netlist_create_from_ast.cpp

ODIN_MEMLEAK: freed untouched signal lists

---

ODIN_II/SRC/verilog_bison.y
ODIN_II/regression_test/benchmark/syntax/flip_flop_enable_w_begin_label.v

added support for labeling begin blocks

support for begin labels

---

ODIN_II/SRC/ast_elaborate.cpp
ODIN_II/SRC/ast_loop_unroll.cpp
ODIN_II/SRC/include/ast_elaborate.h
ODIN_II/SRC/include/ast_loop_unroll.h
ODIN_II/SRC/netlist_create_from_ast.cpp

altered loop unrolling to be done recursively (per module)

ODIN II: moved unroll_loops() into simplify_ast_modules()

---

vpr/src/pack/cluster.cpp

Previous implementation would get an assertion after showing that the blackbox could fit in the pb_type (see: https://github.com/verilog-to-routing/vtr-verilog-to-routing/blob/master/vpr/src/pack/cluster.cpp#L3145).  Rather than asserting after packing the primitive, instead reject the packing earlier in the flow.

Fix check to ensure that molecule belongs in the target pb_type.

---

ODIN_II/SRC/verilog_preprocessor.cpp

ODIN_II: Fixing verilog_preprocessor.cpp warnings
Small changes in verilog_preprocessor.cpp that eliminate compilation warnings.
#572 - ODIN_II: verilog_preprocessor warnings
These changes eliminate warnings that come up during compilation. They are all related to `format_verilog_file()`, `format_module_declaration()` and `format_port_declaration()` in verilog_preprocessor.cpp.
verify_odin.sh has been run with no failures.

ODIN_II: Fixing verilog_preprocessor.cpp warnings

---

vpr/src/base/atom_netlist_utils.cpp
vpr/src/base/netlist_writer.cpp
vpr/src/pack/output_blif.cpp
vtr_flow/arch/common/arch.xml
vtr_flow/benchmarks/tests/eblif_write.eblif
vtr_flow/tasks/regression_tests/vtr_reg_strong/strong_eblif_vpr_write/config/config.txt
vtr_flow/tasks/regression_tests/vtr_reg_strong/task_list.txt

This PR adds the feature to output `.param` and `.attr` to the `blif` file produced when the `--gen_post_synthesis_netlist` option is enabled.
This change is necessary to add additional information in the analysis of the post-synthesis netlist output.
To test the correct functionality I have created a small regression test which in which the `--gen_post_synthesis_netlist` is enabled and the top.blif file is produced.

Eblif write support

---

vpr/src/pack/cluster_router.cpp
vpr/src/pack/pb_type_graph.cpp

Fixes some small spelling mistakes.

Minor spelling fixes

---

ODIN_II/SRC/include/odin_types.h
ODIN_II/SRC/netlist_create_from_ast.cpp
ODIN_II/SRC/netlist_utils.cpp

Merge resolve node with some constant folding functions
fix edge sensitivity not being properly read from a blif

fix edge sensitivity

---

doc/src/utils/fasm.rst
utils/fasm/src/fasm.cpp
utils/fasm/src/fasm.h
utils/fasm/src/parameters.cpp
utils/fasm/src/parameters.h
utils/fasm/test/test_fasm.cpp
utils/fasm/test/test_fasm_arch.xml
utils/fasm/test/test_parameters.cpp
vpr/src/route/route_tree_timing.cpp
vpr/src/route/route_tree_timing.h

This contains a handful of fixes to the genfasm tool.
The initial genfasm tool had some bugs around route walking, some FASM prefix construction, and clock pins.  This resolves those issues.
Unit test and integration testing with symbiflow

Fixes to genfasm tool

---

libs/libarchfpga/src/read_xml_arch_file.cpp

This PR is a fix related to the fasm util. It changes the way the metadata is read in the `read_xml_arch_file.cpp` file. This fix does not affect any VPR functionalities.
The fix is needed as some of the fasm features are incorrectly parsed, leading some of the SymbiFlow tests to failure.

fasm fix: metadata read fix in read_xml_arch

---

ODIN_II/verify_odin.sh

Fix ln failing in verify script
pre_commit odin
vtr_reg_small
'' basic
'' valgring_small
- [ x ] Bug fix (change which fixes an issue)
- [ x ] All new and existing tests passed

Odin:  fix ln error in verify script

---

vpr/src/base/vpr_api.cpp
vpr/src/pack/cluster.cpp
vpr/src/pack/cluster.h
vpr/src/pack/pack.cpp
vpr/src/pack/pack.h
vpr/src/timing/PreClusterTimingGraphResolver.cpp
vpr/src/timing/PreClusterTimingGraphResolver.h

This timing report provides insight into how the packer criticality
values were computed.
https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/653
Provides insight into pre-pack timing analysis.  Timing report has already reveal at least one potential issue https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/653#issuecomment-502840460
Generated new timing report on several designs.

Add a pre-pack timing report.

---

ODIN_II/SRC/multipliers.cpp

remove memory leak from instantiate_hard_multiplier, where it would lose the initial malloc'd new_name.
odin memory leaks

odin_leak: fix memory leak in instantiate_hard_multiplier function

---

ODIN_II/SRC/ast_elaborate.cpp

fix compile error for odin
compile error

Odin: fix compile warning, fallthrough statement

---

ODIN_II/SRC/ast_util.cpp
ODIN_II/SRC/include/ast_util.h
ODIN_II/SRC/include/config_t.h
ODIN_II/SRC/include/odin_memory.hpp
ODIN_II/SRC/include/odin_types.h
ODIN_II/SRC/include/output_blif.h
ODIN_II/SRC/include/read_xml_config_file.h
ODIN_II/SRC/include/simulate_blif.h
ODIN_II/SRC/netlist_create_from_ast.cpp
ODIN_II/SRC/odin_ii.cpp
ODIN_II/SRC/odin_memory.cpp
ODIN_II/SRC/output_blif.cpp
ODIN_II/SRC/read_xml_config_file.cpp
ODIN_II/SRC/simulate_blif.cpp
ODIN_II/SRC/soft_logic_def_parser.cpp

fix leak on arg_parse
double free guard to be used later
odin pre_merge

Odin constant invalid read

---

ODIN_II/SRC/ast_util.cpp
ODIN_II/SRC/include/ast_util.h
libs/librtlnumber/src/include/rtl_int.hpp
libs/librtlnumber/src/rtl_int.cpp

This change allows resolve_node to be aware of the ternary operation and fold these if they can be reduced.
N/a
Allows resolve node to have a broader coverage for constant folding

Odin: initial constant conditional evaluation

---

libs/librtlnumber/src/include/internal_bits.hpp

Stop current compile warnings from being thrown
issue on buildbot
keep the buildbot compilation clean

fix compile warnings

---

ODIN_II/SRC/ast_util.cpp

Updated number resizing from expression resolution to accurately reflect the Verilog sizing standards.
Odin pre-commit regression suite

ODIN II: update number sizing

---

libs/librtlnumber/src/include/internal_bits.hpp

Removed new operator from VNumber constructor

Remove alloc call for VeriBits

---

ODIN_II/SRC/ast_util.cpp
ODIN_II/SRC/netlist_create_from_ast.cpp

Resolved node in netlist_expand_ast_of_module before creating pins to make it possible to free the previous node before reassigning in the resolve_node function

Odin leak fix resolve node

---

ODIN_II/SRC/netlist_create_from_ast.cpp
ODIN_II/SRC/parse_making_ast.cpp

Fixed two leaks from function instantiations.

ODIN II: fix leaks from functions

---

ODIN_II/SRC/netlist_create_from_ast.cpp
ODIN_II/SRC/output_blif.cpp

Fixed memory leak in netlist_create_from_ast.cpp from not freeing in_list

ODIN_II Fix memory leaks arch/both_ram.v

---

ODIN_II/SRC/adders.cpp

Fixed leak in match_ports function in adders.cpp

Odin_ii leak fix from match_ports

---

ODIN_II/SRC/parse_making_ast.cpp

Added a NULL check on module_instance_name. Should resolve Coverity issue #200639

ODIN_II: Fix coverity CID 200639

---

ODIN_II/SRC/read_blif.cpp

Removed !token condition from if statement, as this code would never be explored with it. Should resolve coverity issue CID 200631

ODIN_II: Fixed Coverity issue #200631

---

ODIN_II/SRC/netlist_create_from_ast.cpp

Fixes leak from array_name being allocated and going out of scope before being freed

ODIN_II leak fix array_name

---

ODIN_II/SRC/adders.cpp

Should resolve coverity issues CID 201176, CID 200703, CID 200661, CID 200897. 

ODIN_II: Fixes type mis-match coverity issues

---

ODIN_II/SRC/subtractions.cpp

Should resolve coverity issues CID 200670, CID 201092, CID 201088, CID 201792.

ODIN_II: Fix type mis-match coverity issues

---

ODIN_II/SRC/memories.cpp

Should resolve coverity issue CID 200757, type mis-match.

ODIN_II: Fix coverity issue CID 200757

---

ODIN_II/SRC/implicit_memory.cpp

Fix coverity issue CID 200829; type mis-match.

ODIN_II: fix coverity issue CID 200829

---

ODIN_II/SRC/odin_util.cpp

Should resolve coverity issue CID 200886; type mis-match

ODIN_II: Fix coverity issue CID 200886

---

ODIN_II/SRC/adders.cpp

Should resolve coverity issues CID 200978, CID 201345, & CID 201445. Type mis-match

ODIN_II Fix coverity issues type mis-match in adders.cpp

---

ODIN_II/SRC/hard_blocks.cpp

Should resolve coverity issue CID 200985. Type mis-match

ODIN_II: Fix coverity issue CID 200985

---

ODIN_II/SRC/netlist_create_from_ast.cpp

Should resolve coverity issues CID 201404 & CID 201050. Type mis-match

ODIN_II: Fix coverity issue CID 201404 & CID 201050

---

ODIN_II/SRC/adders.cpp

Should resolve coverity issue CID 201067. Type mis-match

ODIN_II: Fix coverity issue CID 201067

---

ODIN_II/SRC/netlist_utils.cpp

Should resolve coverity issues CID 201087 & CID 201120. Type mis-match

ODIN_II: Fix coverity issues CID 201087 & CID 201120

---

ODIN_II/SRC/memories.cpp

Should resolve coverity issue CID 201089. Type mis-match

ODIN_II: Fix coverity issue CID 201089

---

ODIN_II/SRC/read_blif.cpp

Should resolve coverity issue CID 201101. Type mis-match

ODIN_II: Fix coverity issue CID 201101

---

ODIN_II/SRC/multipliers.cpp

Should resolve coverity issue CID 201111

ODIN_II: Fix coverity issue CID 201111

---

ODIN_II/SRC/simulate_blif.cpp

Should resolve coverity issues CID 201158 & CID 201246

ODIN_II: Fix coverity issues CID 201158 & CID 201246

---

ODIN_II/SRC/odin_util.cpp

Should resolve coverity issue CID 201217. Type mis-match

ODIN_II: Fix coverity issue CID 201217

---

ODIN_II/SRC/parse_making_ast.cpp

Should resolve coverity issue CID 201231. Type mis-match

ODIN_II: Fix coverity issue CID 201231

---

ODIN_II/SRC/simulate_blif.cpp

Should resolve coverity issue CID 201244. Type mis-match

ODIN_II: Fix coverity issue CID 201244

---

ODIN_II/SRC/adders.cpp

Should resolve coverity issue CID 201260

ODIN_II: Fix coverity issue CID 201260

---

ODIN_II/SRC/simulate_blif.cpp

Should resolve coverity issues CID 201836 & CID 201280. Type mis-match

ODIN_II: Fix coverity issues CID 201836 & 201280

---

ODIN_II/SRC/ast_util.cpp
ODIN_II/SRC/include/odin_util.h
ODIN_II/SRC/odin_util.cpp

Tweak previous changes from PR #763 to reuse some existing code rather than adding too much new.

ODIN_II: Reuse old code rather than write new

---

ODIN_II/SRC/memories.cpp

Should resolve coverity issue CID 201291. Type mis-match

ODIN_II: Fix coverity issue CID 201291

---

ODIN_II/SRC/adders.cpp

Should resolve coverity issues CID 201313, CID 201395, & CID 201715

ODIN_II: Fix coverity issues CID 201313, 201395, 201715

---

ODIN_II/SRC/simulate_blif.cpp

Should resolve coverity issue CID 201323. Type mis-match

ODIN_II: Fix coverity issue CID 201323

---

ODIN_II/SRC/simulate_blif.cpp

Should resolve coverity issue CID 201333. Type mis-match

ODIN_II: Fix coverity issue CID 201333

---

ODIN_II/SRC/memories.cpp

Should resolve coverity issue CID 201391. Type mis-match

ODIN_II: Fix coverity issue CID 201391

---

ODIN_II/SRC/netlist_check.cpp

Should resolve coverity issue CID 201406. Type mis-match

ODIN_II: Fix coverity issue CID 201406

---

ODIN_II/SRC/netlist_create_from_ast.cpp

Should resolve coverity issue CID 201409. Type mis-match

ODIN_II: Fix coverity issue CID 201409

---

ODIN_II/SRC/simulate_blif.cpp

Should resolve coverity issue CID 201528. Type mis-match

ODIN_II: Fix coverity issue CID 201528

---

ODIN_II/SRC/netlist_check.cpp

Should resolve coverity issue CID 201637. Type mis-match

ODIN_II: Fix coverity issue CID 201637

---

ODIN_II/SRC/simulate_blif.cpp

Should resolve coverity issue CID 201636. Type mis-match

ODIN_II: Fix coverity issue CID 201636

---

ODIN_II/SRC/subtractions.cpp

Should resolve coverity issue CID 201588. Type mis-match

ODIN_II: Fix coverity issue CID 201588

---

ODIN_II/SRC/simulate_blif.cpp

Should resolve coverity issue CID 201418. NULL check before de-reference

ODIN_II: Fix coverity issue CID 201418

---

ODIN_II/SRC/netlist_create_from_ast.cpp

Should resolve coverity issue CID 201571. NULL de-reference

ODIN_II: Fix coverity issue CID 201571

---

ODIN_II/SRC/odin_util.cpp

Should resolve coverity issue CID 200673; type mis-match.

ODIN_II: Fix coverity issue CID 200673: type mis-match

---

ODIN_II/regression_test/benchmark/valgrind_vtr/config.txt
ODIN_II/wrapper_odin.sh

add benchmark to test vtr_flow verilog files with valgrind on
benchmark the vtr_flow verilog file to assure functionnality and help debug leaks

ODIN_II: add vtr_flow verilog file benchmark suite for odin

---

libs/libarchfpga/src/physical_types.h
vpr/src/base/clustered_netlist.h

correct typos

---

ODIN_II/SRC/adders.cpp

Should resolve coverity issue CID 201136. Identical code inside if-else statements

ODIN_II: Fix coverity issue CID 201136

---

ODIN_II/SRC/simulate_blif.cpp

Should resolve coverity issue CID 200848. sim_data  should be freed before going out of scope.

ODIN_II: Fix coverity issue CID 200848

---

ODIN_II/Makefile
ODIN_II/verify_odin.sh
ODIN_II/wrapper_odin.sh
run_reg_test.pl

Display error code in message for odin test suite
```
operators/binary_nor/sample_arch
Ok . . . . . . . . . . . . . . . operators/binary_logical_less_than/k6_N10_mem32K_40nm
Ok . . . . . . . . . . . . . . . operators/binary_nor/no_arch
Ok . . . . . . . . . . . . . . . operators/binary_nor/sample_arch
Failed  exit:139 "SIGSEGV" . . . operators/string_test_concat_replicate/no_arch
...  <odin stdout if verbose is set> ...
```

Odin_II: improved error message for odin wrapper

---

ODIN_II/wrapper_odin.sh

move the exit signal assignement in regression script such that it properly grabs the exit code with time and timeout
wrapper_odin.sh not catching abort signal
odin operators with forcefully introduced errors

Odin catch abort reg

---

ODIN_II/SRC/subtractions.cpp

Should resolve coverity issue CID 200698. Resource leak due to new_name being overwritten

ODIN_II: Fix coverity issue CID 200698

---

ODIN_II/SRC/hard_blocks.cpp

Should resolve coverity issue CID 201837. Type mis-match

ODIN_II: Fix coverity issue CID 201837

---

ODIN_II/SRC/simulate_blif.cpp

Should resolve coverity issue CID 201873. Resource leak due to *handle and *error not being freed.

ODIN_II: Fix coverity issue CID 201873

---

ODIN_II/SRC/soft_logic_def_parser.cpp

Should resolve coverity issue CID 201870. Extra argument to print statement and type mis-match.

ODIN_II: Fix coverity issue CID 201870

---

ODIN_II/SRC/netlist_create_from_ast.cpp

Should resolve coverity issue CID 201331. Dead code

ODIN_II: Fix coverity issue CID 201331

---

ODIN_II/SRC/Hashtable.cpp

Should resolve coverity issue CID 201668. Identical code inside if-else statement

ODIN_II: Fix coverity issues CID 201668

---

ODIN_II/SRC/ast_elaborate.cpp

```
________________________________________________________________________________________________________
*** CID 202136:  Incorrect expression  (COPY_PASTE_ERROR)
/workspace/vtr-verilog-to-routing/ODIN_II/SRC/ast_elaborate.cpp: 492 in reduce_expressions(ast_node_t *, STRING_CACHE_LIST *, long *, long)()
486                                                             remove_child_from_node(node, last_index);
487                                                             continue;
488                                                     }
489                                                     if (node->children[index] == NULL)
490                                                     {
491                                                             /* resulting from replication of zero …
```

Odin_II: coverity CID 202136 fix copy paste error

---

ODIN_II/SRC/ast_elaborate.cpp

Should resolve coverity issue CID 202109. new_node going out of scope before being freed

ODIN_II: Fix coverity issue CID 202109

---

ODIN_II/SRC/netlist_create_from_ast.cpp

Should resolve coverity issue CID 201059. Explicit NULL de-reference

ODIN_II: Fix coverity issue CID 201059

---

ODIN_II/SRC/simulate_blif.cpp

Should resolve coverity issue CID 202087. Incorrect deallocator

ODIN_II: Fix coverity issue CID 202087

---

ODIN_II/SRC/verilog_bison.y

Fixes memory leak caused by setting a node to NULL in the verilog_bison.y file rather than freeing it.

ODIN_II: fix specparam block leak

---

ODIN_II/SRC/implicit_memory.cpp

Odin_II: fix implicit SP ram leak

---

vpr/src/base/netlist.h
vpr/src/draw/draw.cpp
vpr/src/draw/search_bar.cpp
vpr/src/draw/search_bar.h

- made all of the id check functions public under Netlist
- pop up a warning dialog box if entered block/net/rr node id/name does not exist

vpr: add bound check to the search bar

---

vpr/src/place/place.cpp

Run 'make format'

---

.github/travis/cron_build.sh
.travis.yml

This PR include build step to make and push Coverity builds 
Currently, use my email (should be regenerated by one of the long-term maintainers?)
closes #733
Increase frequency of Coverity scan to improve code quality and lessen errors
used the travis linter to verify no bug were introduced (any other to test before pushing?)
```travis lint .travis.yml```
tested cron_build.sh localy with token from coverity

Travis: include Coverity build step

---

vpr/src/place/place.cpp

- If place method is bounding box and timing analysis is disabled, then
the place_delay_model will not be constructed.
- Later code defers the unique_ptr that holds no object
- Passing an invalid reference is undefined behavior, and may cause a
SEGFAULT.
N/A
Avoids SEGFAULT place algorithm when: ``--place --timing_analysis off --place_algorithm bounding_box``
SEGFAULT no longer happens!

Fix bug in placer when running with no timing analysis.

---

ODIN_II/regression_test/.library/conf_generate.sh
ODIN_II/regression_test/.library/output_on_error.conf
ODIN_II/verify_odin.sh

update the global conf file for the odin regression suite to match new style
remove warning messages from CI)
run_reg_test.pl odin_reg_micro

Odin: update odin global reg conf

---

vpr/src/draw/draw.cpp

- set to left-click only to highlight nodes
#917

vpr: left-click only to highlight nodes

---

ODIN_II/CMakeLists.txt
ODIN_II/Makefile
ODIN_II/SRC/include/odin_types.h
ODIN_II/SRC/include/parse_making_ast.h
ODIN_II/SRC/include/scope_util.h
ODIN_II/SRC/include/string_cache.h
ODIN_II/SRC/netlist_create_from_ast.cpp
ODIN_II/SRC/parse_making_ast.cpp
ODIN_II/SRC/scope_util.cpp
ODIN_II/SRC/simulate_blif.cpp
ODIN_II/SRC/string_cache.cpp
ODIN_II/SRC/verilog_bison.y
ODIN_II/SRC/verilog_flex.l

implement stack-based scopes tables during parse for Verilog files to allow easy creation of temporary tables and better hierarchical maps
inability to create a hierarchy for labels.
odin_pre_commit

Odin_II: initial scope table

---

ODIN_II/SRC/ast_elaborate.cpp
ODIN_II/SRC/ast_loop_unroll.cpp

odin coverity sizeOf problem

---

ODIN_II/SRC/ast_elaborate.cpp

Odin coverity cid203551

---

ODIN_II/SRC/read_blif.cpp

odin_coverity_CID:203690

---

ODIN_II/SRC/verilog_flex.l

coverity bug fix CID: 203549

---

ODIN_II/SRC/verilog_flex.l

odin_coverity_203550

---

ODIN_II/SRC/parse_making_ast.cpp

odin coverity CID 20368[3,5]

---

ODIN_II/SRC/verilog_flex.l
ODIN_II/regression_test/.library/valgrind_simulation.conf
ODIN_II/regression_test/.library/valgrind_synthesis.conf

Odin coverity cid203550

---

ODIN_II/SRC/parse_making_ast.cpp

odin_coverity_CID203685

---

ODIN_II/SRC/ast_elaborate.cpp

odin_coverity_CID203686

---

doc/requirements.txt

Solves an issue with ReadTheDocs. This PR adds the specific commit of the python package used to solve the cross-reference links.

docs: added commit for markdown-code-symlinks python package

---

ODIN_II/SRC/netlist_create_from_ast.cpp

Odin coverity cid203689

---

ODIN_II/SRC/verilog_flex.l

tested by Valgrind for specific tasks which had the mem leak issue

basic_vtr mem leaks

---

ODIN_II/SRC/ast_elaborate.cpp
ODIN_II/SRC/verilog_flex.l

Odin coverity cid203686

---

ODIN_II/regression_test/.library/no_tool.conf
ODIN_II/verify_odin.sh

odin:fix parameter override for test suite

---

doc/src/vpr/basic_flow.rst
doc/src/vpr/index.rst

Add basic VPR flow description to the docs.
Added a new ``basic_flow.rst`` file with the additional description of the P&R process including examples. Added a reference to it to the ``index.rst`` file .
N/A
Better understanding of what VPR does.
Ran with sphinx-build to make sure the ``rst`` file has correct syntax.
- [N/A] I have added tests to cover my changes

docs: vpr: Add basic flow description

---

ODIN_II/SRC/read_blif.cpp

Simulation mem leak - model->name 

---

ODIN_II/SRC/simulate_blif.cpp

Simulation mem leak - pin_numbers in lines structure

---

ODIN_II/SRC/simulate_blif.cpp

Simulation mem leak - num_children in stage struct

---

vpr/src/route/route_tree_timing.cpp

Previous code potentially added a rt_node to two linked_rt_edge's,
resulting in a double free when freeing the tree.
Previous code would segfault in some circumstances.
1. Segfaulting case no longer segfaults
2. CI is green

Fix bug in add_subtree_to_route_tree that can result in double free.

---

ODIN_II/SRC/read_blif.cpp

Simulation mem leak - last element of names array

---

ODIN_II/SRC/read_blif.cpp

Simulation mem leak - create hard block mappings

---

ODIN_II/SRC/read_blif.cpp

Free remained portname's memory

---

vpr/src/base/vpr_context.h

Spelling fix

---

doc/src/utils/index.rst
doc/src/utils/route_diag.rst

This PR adds documentation to the `route_diag` tool.

docs: added `route_diag` documentation

---

ODIN_II/exec_wrapper.sh
ODIN_II/regression_test/.library/output_on_error.conf
ODIN_II/verify_odin.sh

this commit also:
- add helpfull errors on missing packages
- add facility to only run subset of task
- fix the overrides of config files, must specify that we want to override
- add method to forcefully disable coloring in case we can't pick up that its a CI
fails test that should be included during weekly due to change done on 41c111fb347142ac873d3e35f52ff04f9e3fdc53 
fix nightly regression
ran whole flow

Fix regression flow wrongly included test

---

vpr/src/route/route_timing.cpp
vpr/src/util/histogram.cpp

Improve VPR log histogram formatting

Fix histogram formatting

---

vtr_flow/benchmarks/ispd_blif/README.rst

Fix URLs in ISPD benchmark READMEs

Fix ISPD benchmark URLs

---

vpr/src/place/move_utils.cpp

Remove local variable that is not  used.

Remove unused local variable.

---

README.developers.md
README.md
run_reg_test.pl
vpr/src/base/setup_clocks.cpp
vpr/src/route/clock_connection_builders.cpp
vpr/src/route/route_timing.cpp
vpr/src/route/rr_graph2.cpp
vpr/src/route/rr_graph_clock.cpp
vtr_flow/arch/titan/README.rst

Just a bunch of random spelling fixes, and formatting in `run_reg_test.pl`.

Spelling and formatting fixes

---

vpr/src/route/rr_graph2.cpp

vpr: Fix incorrect indexing in get_rr_node_indices for CHANX

---

libs/libarchfpga/src/physical_types.h
vpr/src/route/gen/rr_graph_uxsdcxx.h
vpr/src/route/rr_graph_writer.cpp

Fixes for new rr graph reader / writer

---

.github/travis/build.sh
.travis.yml
CMakeLists.txt
ODIN_II/CMakeLists.txt
vpr/CMakeLists.txt

We should automatically check for compilation warnings during CI. This PR adds such a check to the regular TravisCI build.
As noted in #1114 our current build testing misses this since we default to doing IPO builds, but disable warnings during the link phase (see #634 for why).
Warnings often indicate code issues, as a result VTR builds with fairly aggressive warnings turned on. This helps ensure such issues are caught early.
However having the main build produce many errors is problematic as it means developers may miss new warnings which are introduced.
It is therefore important to have automated tests which fail if code is checked-in with warnings to ensure they get fixed.
Tested manually, and via CI build

Add Travis compile warnings check

---

libs/EXTERNAL/libezgl/examples/basic-application/basic_application.cpp
libs/EXTERNAL/libezgl/include/ezgl/application.hpp
libs/EXTERNAL/libezgl/src/application.cpp
libs/libvtrutil/src/vtr_util.cpp
libs/libvtrutil/src/vtr_util.h
vpr/src/draw/draw.cpp

Fix multiple instances of VPR interfering with each other when they try to open graphics.

Fix multinstance gfx

---

CMakeLists.txt
ODIN_II/CMakeLists.txt
ODIN_II/Makefile
ODIN_II/SRC/netlist_create_from_ast.cpp

Fix invalid string cache access closing #1138 for #1131 
and add quick sanitize compile flags for Odin
closes #1138 
for #1131 
fix invalid memory access
odin regression full

Fix invalid string cache access

---

ODIN_II/Makefile
ODIN_II/regression_test/benchmark/suite/light_suite/task_list.conf
ODIN_II/verify_odin.sh
libs/librtlnumber/rtl_number

add symlink to executable rtl_number
update verify script to call rtl_lib test
add the rtl lib regression suite to odin and fix relapath not being respected in test
improve test coverage
run the suite newly included

Add rtl lib regression suite to Odin

---

README.developers.md

Typos in README.developers.md

---

ODIN_II/SRC/parse_making_ast.cpp
ODIN_II/regression_test/benchmark/verilog/syntax/no_input.v
ODIN_II/regression_test/benchmark/verilog/syntax/no_output.v
ODIN_II/regression_test/benchmark/verilog/syntax/no_port.v

fix segfault for modules without ports
closes #940
help Odin pass more symbiflow tests
odin complete regression

Odin: fix segfault on empty module

---

blifexplorer/CMakeLists.txt

skip building Blifexplorer if Qt is not found

---

blifexplorer/CMakeLists.txt

Fix missing bracket in Cmake Blifexplorer

---

ODIN_II/SRC/ast_elaborate.cpp
ODIN_II/SRC/ast_util.cpp
ODIN_II/SRC/include/ast_elaborate.h
ODIN_II/SRC/include/ast_util.h
ODIN_II/SRC/include/netlist_create_from_ast.h
ODIN_II/SRC/include/odin_globals.h
ODIN_II/SRC/include/odin_types.h
ODIN_II/SRC/include/parse_making_ast.h
ODIN_II/SRC/netlist_create_from_ast.cpp
ODIN_II/SRC/odin_ii.cpp
ODIN_II/SRC/output_blif.cpp
ODIN_II/SRC/parse_making_ast.cpp

see Symbiflow error
ODIN/Makfile pre_merge

Odin: fix empty module and empty files error

---

ODIN_II/SRC/parse_making_ast.cpp
ODIN_II/SRC/verilog_flex.l

see symbiflow test
ODIN_II/make pre_merge

Odin: fix sv call __LINE__ and __FILE__'

---

.travis.yml

Enable address sanitizer in travis for Odin Microbenchmarks to prevent regression failures.
related to #1131

Enable address sanitizer in travis for Odin Microbenchmarks

---

ODIN_II/verify_odin.sh

running verify script from outside directory breaks the bm suite
reenable bm
run_reg_test odin_micro

Odin: use glob over ls to itterate over directory content

---

vpr/src/route/router_lookahead_map.cpp

vpr: Remove extra semicolon

---

.github/kokoro/continuous/strong.cfg
.github/kokoro/presubmit/strong.cfg

Lower the number of cores used for vtr_reg_strong on kokoro.
#1136

Half NUM_CORES for strong.

---

.github/kokoro/steps/vtr-test.sh

Limit kokoro VPR_NUM_WORKERS to 1.
#1136

Limit kokoro VPR_NUM_WORKERS to 1.

---

vpr/src/device/check_rr_graph_obj.cpp

hotfix to avoid double look-up in edge_counter

---

ODIN_II/regression_test/parse_result/parse_result.sh

colors are printed as is rather than colored. use printf
local dry-run

Odin: fix colored output on error

---

libs/libvtrutil/src/vtr_array_view.h
libs/libvtrutil/test/test_array_view.cpp

This enables creating views into allocated data, without direct
ownership.

Add vtr::array_view object.

---

vpr/src/route/binary_heap.cpp
vpr/src/route/binary_heap.h
vpr/src/route/heap_type.cpp
vpr/src/route/heap_type.h
vpr/src/route/route_common.cpp
vpr/src/route/route_common.h
vpr/src/route/static_heap.cpp
vpr/src/route/static_heap.h

This work is in preparation for integrating the heap approximation.
#952

Encapsulate binary heap.

---

.travis.yml
libs/libarchfpga/src/arch_util.cpp
vpr/src/base/read_netlist.cpp
vpr/src/route/binary_heap.cpp
vpr/src/route/connection_router.cpp
vpr/src/route/connection_router.h
vpr/src/route/rr_graph.cpp
vpr/src/route/rr_graph2.cpp
vpr/src/route/rr_graph_uxsdcxx_serializer.h

This addresses a random assortment of issues from coverity.
6 of the 8 changes are just warning suppression.   The change to rr_graph2 fixes a real bug.  The change to connection_router.cpp was a long standing bug around the routing budgets.

Assorted fixed from coverity.

---

libs/libvtrutil/src/vtr_array_view.h
libs/libvtrutil/test/test_array_view.cpp

Adds a version of array_view that is key'd by vtr::StrongId.

Add array_view key'd by StrongId.

---

vpr/src/util/vpr_utils.cpp

Instead of printing each pin's names when describing
an RR source with pin equivalence, print the range of pins (much more
compact and less overwhelming).
Previously VPR would print:
```
CLB.I[0], CLB.I[1], CLB.I[2], CLB.I[3], CLB.I[4]
```
where if the port has a large equivalence class (e.g. 50 pins) the message is very long and overwhelming.
With this PR, we now determine the contiguous ranges of pins and print them directly:
```
CLB.I[0:4]
```
which for large pin counts is much more read-able.

vpr: Print pin ranges when describing contiguous ranges of pins

---

Dockerfile
ODIN_II/regression_test/parse_result/parse_result.py

this commit changes the dockerfile to use Ubuntu
also updates the key in the parse script for odin
commit fixes Dockerfile not usable anymore
odin make test

Update Dockerfile and use vars for dict key python

---

README.md
vtr_flow/scripts/blif_splicer.py
vtr_flow/scripts/download_ispd.py
vtr_flow/scripts/download_titan.py
vtr_flow/scripts/qor_compare.py
vtr_flow/scripts/upgrade_arch.py

I used the 2to3 tool to convert 5 Python 2 scripts to Python 3, and made a few additional minor changes to complete the upgrade for these scripts.
Issue #1181 
Python 2 is end-of-life; these changes remove dependency on Python 2.
All changes were tested with Python 3.7.7 on Debian Testing. Each script was tested for syntax errors detected by the interpreter, followed by attempts to execute each script in its normal usage scenario to confirm that script behavior is unchanged. Finally, the basic and strong regression tests were run with no errors.

Issue #1181 Python 2 to 3 Progress (5 Scripts)

---

ace2/scripts/extract_clk_from_blif.py
dev/external_subtrees.py
dev/submit_slurm.py
sweep_build_configs.py
vtr_flow/scripts/arch_gen/arch_gen.py

I used the 2to3 tool to convert 5 additional Python 2 scripts to Python 3, and made a few additional minor changes to complete the upgrade for these scripts.
Issue #1181
Python 2 is end-of-life; these changes remove dependency on Python 2.
All changes were tested with Python 3.7.7 on Debian Testing. Each script was tested for syntax errors detected by the interpreter, followed by attempts to execute each script in its normal usage scenario to confirm that script behavior is unchanged. Finally, the basic and strong regression tests were run with no errors.

Issue #1181 Python 2 to 3 Additional Progress 1 (5 Scripts)

---

ODIN_II/regression_test/.library/conf_generate.sh
ODIN_II/regression_test/benchmark/task/FIR/task.conf
ODIN_II/regression_test/benchmark/task/arch_sweep/task.conf
ODIN_II/regression_test/benchmark/task/cmd_line_args/batch_simulation/task.conf
ODIN_II/regression_test/benchmark/task/cmd_line_args/best_coverage/task.conf
ODIN_II/regression_test/benchmark/task/cmd_line_args/coverage/task.conf
ODIN_II/regression_test/benchmark/task/cmd_line_args/graphviz_ast/task.conf
ODIN_II/regression_test/benchmark/task/cmd_line_args/graphviz_netlist/task.conf
ODIN_II/regression_test/benchmark/task/cmd_line_args/parallel_simulation/task.conf
ODIN_II/regression_test/benchmark/task/full/task.conf
ODIN_II/regression_test/benchmark/task/large/task.conf
ODIN_II/regression_test/benchmark/task/micro/task.conf
ODIN_II/regression_test/benchmark/task/operators/task.conf
ODIN_II/regression_test/benchmark/task/syntax/task.conf
ODIN_II/regression_test/benchmark/task/vtr/task.conf
ODIN_II/regression_test/benchmark/third_party/SymbiFlow/build.sh
ODIN_II/verify_odin.sh

match vtr flow spelling and fixes a typo in the odin benchmarks infra

ODIN: pluralise circuit_dir and arch_dir bm infra

---

ODIN_II/SRC/verilog_flex.l

Removed buf keyword from unsupported tokens

---

CHANGELOG.md
CMakeLists.txt
doc/src/CHANGELOG.md
doc/src/index.rst
doc/src/vtr/get_vtr.rst
libs/libvtrutil/test/test_strong_id.cpp
vpr/src/base/read_options.cpp

Porting minor changes from the 8.x branch into master (since v8.0.0 has been released).

8.x updates for master

---

Dockerfile
ODIN_II/Makefile
ODIN_II/regression_test/benchmark/task/large/task.conf
ODIN_II/regression_test/parse_result/conf/basic.toml
ODIN_II/regression_test/parse_result/conf/sim.toml
ODIN_II/regression_test/parse_result/conf/synth.toml
ODIN_II/regression_test/parse_result/parse_result.py

This PR fixes issue were really small benchmark accross different machines produced times that are way off.
```
Ok . . . . . . . . . . . . . . . . . operators/binary_logical_and/k6_N10_40nm
Ok . . . . . . . . . . . . . . . . . operators/asr_8_6/no_arch
Ok . . . . . . . . . . . . . . . . . operators/unary_bitwise_bufnode/k6_N10_mem32K_40nm
Ok . . . . . . . . . . . . . . . . . operators/signed_to_unsigned/k6_frac_N10_frac_chain_mem32K_40nm
Ok . . . . . . . . . . . . . . . . . operators/twobits_arithmetic_mod/k6_frac_N10_frac_chain_mem32K_40nm
Ok . . . . . . . . . . . . . . . . . operators/twobits_arithmetic_minus/k6_N10_mem32K_40nm
Failed . . . . . . . . . . . . . . . operators/unary_bitwise_bufnode/k6_frac_N10_frac_chain_mem32K_40nm
- synthesis_time(ms)                  [-0.2-]{+26.3+}
Ok …
```

Odin: add lower and upper bound to range during result parsing

---

.travis.yml
README.developers.md
README.md

Update README and release procedures documentation

Update readme release procedures

---

ODIN_II/regression_test/parse_result/parse_result.py

Create new entries in the regression diff if the tests weren't there before and display the new changes.
fix #1229 regression result generated
allow new regression expected results to be generated

Odin: [bugfix] create new lines in regression results with new tests

---

vpr/src/place/timing_place_lookup.cpp

The previously code could choose such pins if no ports had pin
equivalence, and an fc=0 pin appeared first in the tile/pb_type
port list. This would cause high run-times during placement delay
calculation, since the router would need to search the entire RR graph
before giving up (since no such path exists).
This commit ensures that we only consider pin classes which are a
accessible to/from the general inter-block routing network (i.e.
skipping those with fc=0).
Closes #1240

vpr: Skip fc=0 pins during placement delay lookup calculation

---

doc/src/index.rst
doc/src/vpr/command_line_usage.rst
doc/src/vpr/graphics.rst
doc/src/vpr/index.rst
doc/src/vtr/index.rst

Also expands VPR graphics description section to include illustrative
animations, including of the RR graph.
Closes #1256

doc: Add animations to documentation (main, VTR, VPR pages)

---

README.developers.md
dev/vtr_gdb_pretty_printers.py
dev/vtr_pretty_printers.py
doc/src/vpr/command_line_usage.rst

Various updates to documentation on development best with respect to debugging.
Also adds a pretty printer for some VTR data types under `dev/`

Update Developer Guide for Debugging and Add GDB Pretty Printer

---

vpr/src/base/atom_lookup.cpp
vpr/src/base/atom_lookup.h
vpr/src/timing/timing_graph_builder.cpp
vpr/src/timing/timing_graph_builder.h

Add high-level overview and more comments to timing graph construction code. To address comments from #1040
Closes #1040

Improve Timing Graph Build Comments

---

libs/EXTERNAL/libargparse/.travis.yml
libs/EXTERNAL/libargparse/src/argparse.cpp
libs/EXTERNAL/libargparse/src/argparse_formatter.cpp
libs/EXTERNAL/libargparse/src/argparse_value.hpp
utils/fasm/src/fasm.h
vpr/src/base/vpr_api.cpp
vpr/src/place/move_transactions.cpp
vpr/src/route/check_route.cpp
vpr/src/route/check_rr_graph.cpp
vpr/src/route/clock_fwd.h
vpr/src/route/clock_network_builders.h
vpr/src/route/rr_graph.cpp
vpr/src/timing/PostClusterDelayCalculator.tpp
vpr/src/util/vpr_utils.cpp
vpr/test/test_vpr.cpp

Various bug fixes for issues found by Coverity

Coverity bug fixes

---

vtr_flow/parse/parse_config/common/vpr.common.txt

To aid in debugging and understanding performance/QoR differences across different infrastructure/platforms, parse out additional metrics about how VPR was built.

flow: Record additional build info in parse results

---

libs/libarchfpga/src/main.cpp
vpr/src/place/timing_place_lookup.cpp
vpr/src/route/clock_connection_builders.h
vpr/src/route/rr_graph.cpp
vpr/src/util/vpr_utils.cpp
vpr/src/util/vpr_utils.h

Additional fixes for issues identified by Coverity

Coverity fixes

---

libs/librtlnumber/CMakeLists.txt
libs/librtlnumber/regression_tests/basic_regression_tests.csv
libs/librtlnumber/src/include/internal_bits.hpp
libs/librtlnumber/src/rtl_int.cpp
libs/librtlnumber/verify_librtlnumber.sh

Added test coverage for Z into the RTL library
TODO

Updated RTL tests to cover X and Z

---

libs/libvtrcapnproto/gen/rr_graph_uxsdcxx.capnp
vpr/src/route/gen/rr_graph_uxsdcxx.h
vpr/src/route/gen/rr_graph_uxsdcxx_capnp.h
vpr/src/route/gen/rr_graph_uxsdcxx_interface.h

Should fix Coverity 208510
See also https://github.com/SymbiFlow/uxsdcxx/pull/49#event-3253121681 for upstream fix.

vpr: Update generated rr graph serialization to fix potential FILE* leak

---

dev/annealing_curve_plotter.py

This is a simple script that parses VPR log and extracts data printed out during placement (simulated annealing progress). Then it allows to generate various plots of the data.
See the script's docstring or run it with the `-h` switch.
While playing with placement parameters or even with the code it is good to know how various metrics change with the annealing temperature. This gives valuable insights in how the algorithm works and if it progresses correctly.

A script for generating plots of simulated annealing curves

---

vpr/src/place/place.cpp

Removes unused variable in placer.

vpr: Remove unused net_pin_indicies variable in placer

---

libs/libarchfpga/src/physical_types.h
libs/libarchfpga/src/read_xml_arch_file.cpp
vpr/src/base/read_route.cpp
vpr/src/place/initial_placement.cpp
vpr/src/route/rr_graph.cpp
vpr/src/util/vpr_utils.cpp
vpr/src/util/vpr_utils.h
vtr_flow/arch/sub_tiles/sub_tiles.xml
vtr_flow/benchmarks/microbenchmarks/sub_tiles.blif

This PR fixes some bugs related to the recent sub tiles addition.
For SymbiFlow purposes, the sub tiles were tested on regular tiles, such as the BUFG tile which has the same kind of sub tiles, which differ only for the pinlocations.
When it comes to more heterogeneous tiles, such as the CLBM, the sub tiles differ also in the pin definition.
What went undiscovered in the sub tile addition were two things:
- correct pin mappings checks between logical and physical tiles that (fixed with https://github.com/verilog-to-routing/vtr-verilog-to-routing/commit/2d5cb9979cbd49eeb2797699927d19b1741a7f77)
- fix initial placement that cannot have incompatible `logical_blocks <-> sub_tiles` locations. Also fixed the check for the sub tile compatibility (fixed with …

Fix bug in sub tiles

---

BUILDING.md
ODIN_II/SRC/include/Hashtable.hpp
ODIN_II/SRC/odin_ii.cpp
ODIN_II/SRC/parse_making_ast.cpp
dev/nix/shell.nix
libs/libvtrutil/src/vtr_logic.h
libs/libvtrutil/src/vtr_small_vector.h
libs/libvtrutil/src/vtr_string_interning.h
vpr/src/route/gen/rr_graph_uxsdcxx.h

Fixes bugs and adds a working `shell.nix` for developers using MacOS.
#1244
I have a Mac. I like Nix.
I ran `vtr_reg_strong` on my Mac. There was 1 test failure and 13 QoR failures, which is interesting because I didn't change anything significant.

Fix minor bugs to get VtR building on MacOS with Nix

---

README.developers.md

Update commit procedures to match current workflow.
Provide guidance on suggested commit message style and commit structure.

doc: Update commit proceedures

---

README.md

Update ODIN II Contributors in README

Update ODIN II Contributors in README

---

README.developers.md

In particular document different ways of speeding up compilation.
Document ways of speeding up VTR compilation for faster edit-compile-debug cycles (particularly compilation time).
Thanks for @dpbaines for asking questions about this which prompted writing this down.

doc: Add notes on how to speed-up VTR edit-compile-debug cycle

---

vpr/src/place/timing_place.h

vpr: Fix uninitialized class data member

---

vpr/src/pack/prepack.cpp

Fix the bug of memory leaking when disable packing is enabled
Free allocated memory when the packer fails at pre-packing stage. 
This aims to address the issue [https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/1334](url)
My take on this memory leak is that the linked list of molecules is not freed automatically when VPR packer throws a fatal error.
Therefore, codes were added to  free the linked list before throwing a fatal error.
Currently CI looks fine. But I would like to see the problem is solved in kokoro.
- [] All new and existing tests passed

bug fix for memory leakage in prepacking stage for disable packing 

---

vpr/src/base/read_route.cpp

I added a simple checker that checks for continuity between traces in read_route.cpp, if a weird discontinuity is detected it throws an exception, and tells the user which net and line threw the error. This is an improvement over the segmentation fault that happened before hand.
https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/1307
Following the issue described by Andrew; where the program would crash if VPR is given an externally produced route file, it was determined that the bug was caused by the introduction of a 'dangling branch', which is when the route trace has a discontinuity between traces.
I ran the regression tests and as expected there is no impact on the normal flow. I also ran several flows, and played around with the generated route files, checking to …

Adding improved error checking for the route file parser

---

doc/src/conf.py

Fixes the problem with missing links to markdown files in the documentation. The problem was introduced by https://github.com/verilog-to-routing/vtr-verilog-to-routing/pull/1354. 
Resolves https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/1357
This change is necessary to correctly show full content of the documentation.
Markdown Code Symlinks extension seems to work correctly since the relative path given in 
https://github.com/verilog-to-routing/vtr-verilog-to-routing/blob/master/README.developers.md#external-subtrees:
```
To simplify the process of working with subtrees we use the [`dev/external_subtrees.py`](./dev/external_subtrees.py) script.
```
is changed to the correct link to the file on GitHub:
https://vtr--1358.org.readthedocs.build/en/1358/dev/developing/#exter …

Fix links to markdown files in the documentation

---

README.developers.md

Add VPR profiling procedures to the VTR documentation

---

.gitignore
libs/libarchfpga/src/parse_switchblocks.cpp
libs/libarchfpga/src/parse_switchblocks.h
libs/libvtrutil/src/vtr_expr_eval.cpp
libs/libvtrutil/src/vtr_expr_eval.h
libs/libvtrutil/test/test_expr_eval.cpp
vpr/src/base/SetupGrid.cpp
vpr/src/base/setup_clocks.cpp
vpr/src/route/build_switchblocks.cpp

Move expression evaluator into vtrutil, and add tests.

Re-organize Expression Evaluator

---

ODIN_II/regression_test/parse_result/conf/basic.toml

@jeanlego 
Changed the regix in basic.toml of error and warning to be able to pick up messages inputed by the $display function in a verilog file when creating the simulation and synthesis jsons. The syntax for it to be picked up is: $display("Warning::CAPATALIZED_THING ");
Usually the capatalized thing is the function the benchmark is testing. This should be used for benchmarks to indicate if a test should pass or fail. Also, if it fails what is going wrong/not functioning properly. A future PR with make a new title called "Expecatation" instead of warning.
New feature
Ran make test passed

ODIN_II: basic.toml adjusted regex to read $display

---

ODIN_II/SRC/odin_ii.cpp
ODIN_II/main.cpp

update odins banner
we were behind a few version
allow better debugging of user errors
n/a

Odin: update the banner

---

ODIN_II/regression_test/benchmark/task/keywords/macromodule/synthesis_result.json
ODIN_II/regression_test/benchmark/task/keywords/module_endmodule/synthesis_result.json
ODIN_II/regression_test/parse_result/conf/basic.toml
ODIN_II/regression_test/parse_result/conf/hooks.py
ODIN_II/regression_test/parse_result/parse_result.py

this adds preprocessing hooks to the log parser.
the user can now specify runtime hooks for the log parser and call out line by line the 
PR #1416 was unable to merge because of string mismatch

Odin: add preprocessing hooks to the parse script to allow user made replacement

---

ODIN_II/regression_test/parse_result/parse_result.py

Currently odin only prints out null if the value is the default value, 
```
Failed . . . . . . . . . . . . . . . preprocessor/undef/k6_frac_N10_frac_chain_mem32K_40nm
- exit                                [-1-]{+null+}
- leaks                               [-1-]{+null+}
Failed . . . . . . . . . . . . . . . preprocessor/undef/k6_N10_40nm
- exit                                [-1-]{+null+}
- leaks                               [-1-]{+null+}
Failed . . . . . . . . . . . . . . . preprocessor/undef/k6_N10_mem32K_40nm
- exit                                [-1-]{+null+}
- leaks                               [-1-]{+null+}
Failed . . . . . . . . . . . . . . . preprocessor/undef/no_arch
- exit                                [-1-]{+null+}
- leaks                               [-1-]{+null+}
Ok . . . …
```

Odin: Json print more usefull value mismatch

---

ODIN_II/SRC/netlist_create_from_ast.cpp
ODIN_II/regression_test/benchmark/task/keywords/always/simulation_result.json
ODIN_II/regression_test/benchmark/task/keywords/always/synthesis_result.json

Fix leak in assignment operations

Odin assignement leak

---

vpr/src/place/timing_place.cpp

Fix timing cost consistency check bug

---

vpr/src/base/read_route.cpp
vpr/src/base/vpr_types.h
vpr/src/draw/draw.cpp
vpr/src/draw/draw_global.cpp
vpr/src/draw/draw_global.h
vpr/src/draw/draw_types.h
vpr/src/route/connection_router.cpp
vpr/src/route/connection_router_interface.h
vpr/src/route/route_breadth_first.cpp
vpr/src/route/route_common.cpp
vpr/src/route/route_common.h
vpr/src/route/route_timing.cpp
vpr/src/route/route_tree_timing.cpp
vpr/src/route/route_tree_timing.h
vpr/src/route/router_stats.h

Final optimization decision on PR #1396.

Remove pres cost

---

ODIN_II/SRC/simulate_blif.cpp

Odin: fix coverity 211470,211469

---

ODIN_II/Makefile
ODIN_II/regression_test/benchmark/suite/vtr_light_suite/task_list.conf
ODIN_II/regression_test/parse_result/conf/hard_blocks.toml
ODIN_II/regression_test/parse_result/conf/node.toml
ODIN_II/verify_odin.sh

This PR ad a vtr regression test filter that:
- only runs verilog based test
- combine a set of vtr tests together into one
Also add:
- ability to continue a test such that the directory are combined into one
- display previous test results
simplify test infrastructure and speed up tests.
odin test suite

Odin: add a vtr test filter

---

doc/src/vpr/debug_aids.rst

added documentation on using the new debugger
this documentation clearly outlines how the user can utilize the placer and router debugger. It explains features, available variables and operators.
This change results in a more complete documentation and avoids confusion for future users who want to use this debugger.

Added Debugger Documentation

---

libs/EXTERNAL/libargparse/argparse_test.cpp
vpr/src/base/CheckSetup.cpp
vpr/src/base/SetupVPR.cpp
vpr/src/base/ShowSetup.cpp
vpr/src/base/read_options.cpp
vpr/src/base/read_options.h
vpr/src/base/read_place.cpp
vpr/src/base/vpr_types.h
vpr/src/place/initial_placement.cpp
vpr/src/place/initial_placement.h
vpr/src/place/place.cpp

Removed pad_loc_file string as it was no longer needed.

Cleaning up code related to fix_pins and fix_clusters vpr options

---

doc/README

documentation was incorrectly spelt.

Fixed a typo

---

ODIN_II/SRC/include/parse_making_ast.h
ODIN_II/SRC/parse_making_ast.cpp

Changed format to be more insightful and useful.

Odin: Improve the AST dot graph

---

vpr/src/route/check_route.cpp

Refactored check_sink to use the traceback's net_pin_index so that code can be simplified. Also fixed the weak sink check.
- Allow net_pin_index of the traceback to be passed into the check_sink function.
- use the net_pin_index so we can get rid of the loop through all sinks for a match.
- implemented strong check by making sure that we hit a netlist pin exactly once.
The old check was a weaker check as it wasn't actually checking that we find a sink matching each pin in the net; it just checks that we find N sinks for a fanout N net, and each sink appears to connect to a block that is reasonable (matches some pin on this net).  it was really just counting them and making sure we hit N sinks that were reasonable, but not that each was different. So a strong check replacement is needed.
- …

Simplify and strengthen check_sink

---

CMakeLists.txt

This is a short commit that helps fixing the build breakage, with suggesting proper library.
Simplifies ease of use
Signed-off-by: Georgiy Krylov <georgiy.krylov@unb.ca>
Since the changes mid-August, the build on the main branch would fail if libgtk-3.0-dev was failing.
The suggested to the CMake error message fix resolved it for me, while the original message was 
insufficient
Building using the suggested library succeeded. Ubuntu 19.10
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~19.10) 
N/A
Since it is a "documentation" change, nothing should be affected.

Documentation Changes to CMakeLists.txt

---

.github/kokoro/run-vtr.sh
.github/kokoro/steps/hostsetup.sh
.travis.yml
dev/upgrade_vtr_archs.sh
requirements.txt

Added a requirements file  
This is needed because there are new packages required by the new python code in this [pull request](https://github.com/verilog-to-routing/vtr-verilog-to-routing/pull/1509)
No related issue.
We should document required packages.
Run the new python scripts without the required packages, see it fail, run `pip install -r requirements.txt` and rerun the new python scripts

Python requirements added

---

libs/libarchfpga/src/physical_types.h
vpr/src/util/vpr_utils.h

Additional in-code comments around physical tiles, logical blocks and sub tiles.
https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/1527

arch: additional comments on physical tiles, logical blocks, sub tiles

---

vpr/src/draw/draw.cpp

remove unused variable assignment  in draw.cpp that was caught by Coverity scan

remove unused variable assignment 

---

vpr/src/pack/prepack.cpp

This PR relaxes the assertion about the pin number when the model port is a clock input during prepacking.
https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/1546
If an input PAD needs to be treated as a clock generator to add the possibility to have SDC constraints, VPR would throw an error on the PAD primitive as the clock pin would not be valid (according to the assertion), given that the input clock pin would be at position 0 instead of 1.
With this PR, the assertion is relaxed, in a way that now, if the driver block is of an `.input` type, the assertion does not get triggered.

prepack: relax assertion on model port clock input pin_number

---

doc/src/conf.py
doc/src/odin/dev_guide/contributing.md
doc/src/odin/dev_guide/regression_test.md

This PR adds graphics to visualize the odin flow as well as graphviz support in sphinx to build them

Update the documentation with Odin flow

---

.github/autolabeler.yml
README.developers.md
dev/tutorial/NewDeveloperTutorial.txt
run_quick_test.py

Remove lingering references to old .pl files (now that we have switches to .py scripts for flow)
Existing CI tests.

Fix lingering .pl references in documentation

---

doc/src/dev/code_documentation.rst
doc/src/dev/index.rst
requirements.txt

This PR adds the note about documenting VTR code with Doxygen.
https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/1471
The created document will give a brief introduction on how to use Doxygen for documenting the code. 
It will be useful for new developers
I tested it locally. Additional tests and preview are available in the RTD CI.
[[CI PREVIEW]](https://vtr--1548.org.readthedocs.build/en/1548/dev/code_documentation/)

Add note about documenting code with Doxygen

---

ODIN_II/regression_test/benchmark/task/arch_sweep/task.conf
ODIN_II/regression_test/benchmark/task/large/task.conf
ODIN_II/regression_test/benchmark/task/micro/task.conf
ODIN_II/regression_test/benchmark/task/operators/task.conf
ODIN_II/regression_test/benchmark/task/syntax/task.conf
ODIN_II/regression_test/benchmark/task/vtr/task.conf

Timeout was too low and causing long CI to fails, this commit increases
the timeout to prevent failures
@vaughnbetz thanks for binging my attention to this!
related to CI problem on #1548

Odin: increase timeout of regression test

---

ODIN_II/README.md

This commit changes the OdinII maintainer

Odin: Switch Odin maintainer

---

ODIN_II/README.md

This Pr updates the code owner

Odin: Update Code Owner

---

vpr/src/base/partition.h
vpr/src/route/rr_graph_indexed_data.cpp

Add missing includes.

---

vpr/src/place/place.cpp

This PR is created to fix a compilation error that happens in place.cpp when we enable VPR_ANALYTIC_PLACE
When VPR_ANALYTIC_PLACE is enabled, a goto statement skip the anneal and jumps directly to the quench. This was also skipping some variables used by the RL agent in the quench. The code refactored to solve this issue and use better coding style than goto.

Refactor the interaction between analytical placer and RL

---

ODIN_II/SRC/netlist_create_from_ast.cpp
ODIN_II/SRC/odin_ii.cpp
README.md
doc/src/odin/dev_guide/contributing.md
doc/src/odin/dev_guide/regression_test.md
doc/src/odin/dev_guide/verify_script.md

Grammatical/spelling corrections and name addition to contributors
None
Fix typos
Not required as no changes to the code base

Documentation changes and grammatical/spelling corrections

---

.github/kokoro/steps/vtr-full-setup.sh
requirements.txt

This PR fixes https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/1716

requirements: pin pylint

---

ODIN_II/SRC/netlist_create_from_ast.cpp

Previously, the simple swap of two items at a time has been used as the sort approach for instance port connection, to reorder them according to the main module (function or task) that they are instantiated from. That would cause an error since we alter the array of ports each time, which results in an unexpected change in the array for future swapping. The new approach uses a helper array to order the ports and then reorder the instantiated instance ports.
#1699
bug fix
1. make test (ODIN-II)
2. Basic Regression Tests
3. Strong Regression Test
4. Basic Valgrind Memory Tests (also, Valgrind memory tests for all other regression suits)
5. Sanitized Basic Regression Tests
6. Odin-II Micro Tests

[Odin]: Sorting the instance ports based on the related module, function or task

---

doc/src/vpr/debug_aids.rst

Fixing images on debug_aids.rst

---

vtr_flow/benchmarks/titan_blif/README.rst
vtr_flow/benchmarks/titan_other_blif/README.rst

Updated the Titan README files to mention the location of the repo in the U of T EECG network. 
To document the location of this repo.

Updating Titan README 

---

README.developers.md

Fixing up spelling mistakes within the VTR documentation
The words 'Navigate' and 'messages' were spelled incorrectly and they
were found within the 'Commit Procedures' and 'Commit Messages and
Structure' sections of the documentation. The words were replaced with
the correct spelling.
This change was required to resolve minor issues with the documentation. 
The vtr_reg_basic and vtr_reg_strong tests were run and both tests successfully passed.

Header line: Fixing up spelling mistakes within the VTR documentation

---

utils/fasm/test/test_fasm.cpp

A followup PR of https://github.com/verilog-to-routing/vtr-verilog-to-routing/pull/1731 which adds the requested code comments.

Comments to genfasm tests

---

.github/kokoro/continuous/odin_strong.cfg
.github/kokoro/presubmit/odin_strong.cfg
.github/kokoro/run-vtr.sh
.github/workflows/test.yml
README.developers.md
run_reg_test.py

Running Odin full regression tests by CI and Kokoro
splitting Odin's complete regression test into two stages:
1. Odin reg basic: performing Odin's [light_suite](https://github.com/verilog-to-routing/vtr-verilog-to-routing/blob/master/ODIN_II/regression_test/benchmark/suite/light_suite/task_list.conf) [CI]
3. Odin reg strong: performing Odin's [heavy_suite](https://github.com/verilog-to-routing/vtr-verilog-to-routing/blob/master/ODIN_II/regression_test/benchmark/suite/heavy_suite/task_list.conf) [Kokoro]
Regression test coverage by CI

Ading odin_reg_full to CI

---

README.developers.md
vtr_flow/scripts/slurm/README.md
vtr_flow/scripts/slurm/submission_template.sh

This PR adds a template SLURM submission script that can be used to submit a large VTR task run on a SLURM-managed cluster. I have also added some documentation on how to use this script to run easily using slurm.
The PR is tested on computecanada cluster (Niagara system)

Add a template submission script for SLURM-managed clusters

---

ODIN_II/SRC/subtractions.cpp

Undriven nets would cause segfault in resolving subtraction nodes. Solution is provided by connecting the to the pad node
#1748 #1738
bug fix
`make test`

Connecting untouched nets to the pad node in resolving subtraction node

---

.github/kokoro/continuous/nightly_test1.cfg
.github/kokoro/continuous/nightly_test2.cfg
.github/kokoro/continuous/nightly_test3.cfg
.github/kokoro/continuous/nightly_test4.cfg
doc/requirements.txt
doc/src/conf.py

This should fix https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/1727

docs: fix wrong markdown links

---

doc/src/api/vtrutil/logging.rst
libs/libvtrutil/src/vtr_error.h
libs/libvtrutil/src/vtr_list.h
libs/libvtrutil/src/vtr_log.h

Added new information to the VTRUTIL API documentation. The updates improved the documentation clarity.
- First update was making it clear that VTR_LOG_ERROR does not terminate the program
- Second update was adding an example on how vtr::VtrError is used, and also indicated that it can be used to terminate the program.
- These changes were made to help improve the VTR documentation.
- After the changes were made, the documentation was built and the changes were verified visually.

Updating vtrutil api doc

---

.github/kokoro/steps/hostsetup.sh

Adding "--no-check-certificate" to wget command to the Kokoro host setup script to see if it solves recent Kokoro runners failure.
Discussed in #1863

Kokoro proxy issue

---

BUILDING.md

Updating the building doc to point to correct task path and output. 
#1966 Doc update.

Doc update building

---

doc/src/conf.py

The configuration file (conf.py) for the VTR document generation is using a depreciated function in the sphinx API, so this was changed to the newer equivalent function. 
The app.add_stylesheet() function has been changed to app.add_css_file().
When trying to build the documentation on a fresh machine, the latest version of sphinx is installed and this causes a build failure due to the depreciated function. And the latest sphinx API functions should be used. This change was made in version 1.8 as per the documentation (**https://www.sphinx-doc.org/en/master/extdev/appapi.html**).
This has been tested by building the documentation locally and ensuring that the build was error free.

changed a depreciated function in sphinx to its newer equivalent function

---

vpr/src/pack/pack.cpp
vpr/src/pack/prepack.cpp
vpr/src/pack/prepack.h
vpr/src/pack/re_cluster_util.h
vpr/src/place/place.cpp

This PR is a follow-up PR to address reviewers' comments on PR #2034
Mainly removing debugging and commented code and adding more comments.

Re-clustering API (follow-up PR)

---

Dockerfile

Adding multi-thread compiling option to the docker file to speed up the compiling process

Speeding up the compile process in a docker build

---

libs/EXTERNAL/libezgl/src/callback.cpp

…ger erases selection on drag)
Added fix in ezgl callback.cpp to prevent pans/screen drags from being read as clicks.
Dragging on the screen to move around the view of the chip mapping was being read as a click on the screen, which resulted in that callback fn being called, removing the selected block.

Fixed Bug Causing Selected Nets and Blocks to be unselected on pans

---

.readthedocs.yaml

Fixing the documentation build issue by updating the python version used to build the docs to python3.8. 
The documentation build was failing in the master branch and all PRs

Fixing the doc build issue

---

ODIN_II/main.cpp

Setting Odin-II stack size to >= 128 MB to avoid stack overflows in recursive routine for big benchmarks like tpu_32x32.v
#2098

Increase Odin-II stack size 

---

doc/src/vtr/run_vtr_flow.rst

Follow up on PR #2139 to clarify the expected file extensions for SystemVerilog/UHDM input HDLs

Update Yosys Plugins Documentation

---

ODIN_II/README.md

Updating the Odin-II maintainers

---

.github/workflows/test.yml

strong_analytic_placer benchmark was design to test analytical placement. However, It was running through Simulated Annealing instead of analytical placement due to missing package in CI test. I changed the test.yml file to address this issue. I changed the file in a way that we only install this package for the required test, and other designs do not require to install any extra libraries. 
@vaughnbetz

Changed the GitHub automated test to install external libraries for analytical placement

---

libs/librrgraph/src/io/gen/rr_graph_uxsdcxx.h
vpr/src/base/gen/vpr_constraints_uxsdcxx.h

Add comments for setting errno = 0;

add comments for setting errno=0

---

vpr/src/place/initial_placement.cpp

This PR is made to address [this](https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/2251) bug report.
@vaughnbetz

debug init_blk_types_empty_locations

---

install_apt_packages.sh

missing packages added from Yosys build page to `install_apt_packages.sh`
[2271](https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/2271)

missing packages added from Yosys build page

---

doc/src/quickstart/index.rst

Updated quick start to recommend Ubuntu 22.04

---

doc/src/vtr/optional_build_info.md

Updating compiler support list in documentation.

Updated build info for Ubuntu 22.04

---

doc/src/parmys/quickstart.rst
install_apt_packages.sh

https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/2271

Parmys doc update

---

vpr/src/util/vpr_utils.cpp

Add missing include; remove unused variable.

---

vtr_flow/parse/parse_config/vpr_noc.txt

Parse file for the design with Network-on-Chips (NoCs) didn't support all NoC metrics, modified it to report these three metrics:
1. NoC Aggregate Bandwidth
2. NoC Latency
3. Number of traffic flow that their constraints are met.

Modified NoC parse file

---

CONTRIBUTING.md
vpr/main.ui

Added a paragraph to the contributing.md documentation, indicating how to build the documentation, and referring to the README on the GitHub. Changed the "done" button on the UI to "proceed" 
Adds more information to the documentation, and makes the "done" button more accurate to what it does. 
Previewed the updated document and updated UI
- [ X ] My change requires a change to the documentation
- [ X ] I have updated the documentation accordingly

Changed contributing documentation, and done button to proceed

---

doc/requirements.txt

looks like this issue to me? https://github.com/readthedocs/readthedocs.org/issues/10279

fix rtd build

---

vtr_flow/scripts/qor_compare.py

This PR adds the `parmys_synth_time` metric to the `qor_compare.py` script.

parmys synthesis time added to the `qor_compare.py` script

---

vpr/src/base/vpr_api.cpp
vtr_flow/scripts/run_vtr_flow.py

Address issue [#2393](https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/2393) 
@vaughnbetz

Issue#2393 (add guards for tbb compilation)

---

.github/workflows/test.yml

To disable Parmys in Odin-specific tests.
https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/2402

disable Parmys in Odin tests

---

README.developers.md

Explained the various nightly tests etc. better.

Update README.developers.md with more current reg test info

---

libs/EXTERNAL/libcatch2/src/catch2/catch_test_case_info.hpp
libs/EXTERNAL/libcatch2/src/catch2/internal/catch_xmlwriter.cpp
libs/librtlnumber/src/include/rtl_utils.hpp

Attempt to fix the builds for now by patching catch2 (see #2436). I see @jgoeders is trying to set up catch2 as a submodule in #2437. This should go away once #2437 is merged.

quick fix for CI

---

README.md
vtr_flow/scripts/download_titan.py

Change http to https for titan link

Fix Titan Benchmark Link

---

vpr/src/route/router_lookahead_map.cpp

**Summary:**
Addresses issue #2458.
**Details:**
In this pull request, we resolve a key issue with the map router lookahead.
In Map router lookahead, only the cost from nodes of type channel x/y to IPINs is stored. To calculate the cost from OPIN to an IPIN, we relied on a map containing all segments accessible from that OPIN. We iterate over all those segments and get the lowest cost to the IPIN. Then, the cost to get to that segment is added to the cost from that segment to the IPIN.
The bug lay in the fact that the iteration was limited to segments on the same layer as the IPIN. This approach failed when there was no direct connection from the OPIN, resulting in no channel being directly accessible from that OPIN :)

Debug Router Lookahead For 3D Architecture

---

libs/EXTERNAL/libargparse/argparse_test.cpp
libs/librrgraph/src/base/rr_graph_storage.h
libs/libvtrutil/src/vtr_dynamic_bitset.h
vpr/src/base/ShowSetup.cpp
vpr/src/base/read_options.cpp
vpr/src/base/vpr_types.h
vpr/src/route/DecompNetlistRouter.h
vpr/src/route/DecompNetlistRouter.tpp
vpr/src/route/ParallelNetlistRouter.tpp
vpr/src/route/SerialNetlistRouter.tpp
vpr/src/route/connection_router.cpp
vpr/src/route/connection_router.h
vpr/src/route/connection_router_interface.h
vpr/src/route/netlist_routers.h
vpr/src/route/partition_tree.cpp
vpr/src/route/partition_tree.h
vpr/src/route/route.cpp
vpr/src/route/route_common.h
vpr/src/route/route_net.cpp
vpr/src/route/route_net.h
vpr/src/route/route_net.tpp
vpr/src/route/route_tree.cpp
vpr/src/route/route_tree.h
vpr/src/route/sink_sampling.h
vtr_flow/tasks/regression_tests/vtr_reg_nightly_test4/koios_medium/config/config.txt
vtr_flow/tasks/regression_tests/vtr_reg_weekly/koios_large/config/config.txt

Add net-decomposing case for `ParallelNetlistRouter`.
TODO: better description here

Improved parallel router: add DecompNetlistRouter

---

.github/workflows/test.yml

There has been some regressions with regard to CAPNPROTO being disabled since all of the CI tests have CAPNPROTO enabled.
Added a basic regression test to the CI which will run the vtr_reg_basic tests with CAPNPROTO disabled. This will test both that everything builds and basic VPR tests will run.
In the future we should test direct features that disabling CAPNPROTO would affect (such as writing and reading routing files); however, for now this will prevent the regressions previous seen.
issue #2510 
In a previous PR (PR #2511 ) fixed regressions to when CAPNPROTO is disabled. In the PR I mentioned that there should be regression tests in the CI to prevent this in the future. Added basic regression tests to the CI.

[CI][Capnproto] Added Basic Regression Test with CAPNPROTO Disabled

---

doc/src/vpr/command_line_usage.rst

Fix the visual issue in the documentation

Fix a minor issue in document

---

README.developers.md

The documentation on subtrees was a bit out of date. The command to update a subtree now requires a message.
Added a section on how to push changes from VTR back into the upstream subtree repo.
Added a tutorial on how to synchronize libtatum with the Tatum repo.

[Docs] Updated Subtree Docs

---

vpr/src/base/read_options.cpp

Added code to construct a default flat placement input file name.

added default filename generation for input flat placement file

---

vpr/src/route/connection_router.cpp

This PR addresses the issue #2612

CHAN Node Count - High Fanout RT

---

vpr/src/route/connection_router.cpp

This PR addresses the Issue #2611

Remove `has_path_to_sink`

---

.github/workflows/nightly_test.yml

Added a workflow dispatch trigger so the NightlyTests can be run manually for testing purposes.

[CI] Added a Workflow Dispatch Trigger for NightlyTest

---

libs/librrgraph/src/base/rr_graph_storage.h
libs/librrgraph/src/base/rr_node_types.h
libs/libvtrutil/src/vtr_ragged_matrix.h
libs/libvtrutil/src/vtr_string_interning.h

Fixes for gcc-15 build

---

doc/src/arch/index.rst

langauge -> language
Just nitpick spelling

Update spelling in index.rst

---

doc/src/vpr/file_formats.rst

VPR Place File Format Doc Updated to latest changes.
closes #2439
Up to date information in project docs

VPR Place File Format Doc Updated to latest changes

---

vpr/src/pack/cluster_legalizer.cpp

A memory leak was able to occur if the external pin utilization string was set to an invalid number. This was caught by the CI, which inexplicably came back to life today.

[ClusterLegalizer] Fixed Memory Leak

---

doc/src/vpr/command_line_usage.rst

Described the simple place_delay_model and that it is now the default.

Update command_line_usage.rst --place_delay_model

---

doc/src/vpr/command_line_usage.rst

Add missing command line option (simple) to --place_delay_model in docs

---

vpr/src/pack/sync_netlists_to_routing_flat.cpp

Fix name conflicts in sync_netlists_to_routing_flat

---

ODIN_II/SRC/include/Hashtable.hpp
libs/EXTERNAL/libargparse/src/argparse.cpp
libs/EXTERNAL/libcatch/catch.hpp
libs/libeasygl/src/graphics_types.h
libs/librtlnumber/src/rtl_utils.cpp
libs/libvtrutil/src/vtr_geometry.h
libs/libvtrutil/src/vtr_small_vector.h

#2826   pull request with base vtr8-noble

fix: v8.0.0 release version on [Ubuntu 24.04]  noble version 

---

doc/src/vpr/command_line_usage.rst
libs/libvtrutil/src/vtr_vector_map.h
vpr/src/base/load_flat_place.cpp
vpr/src/base/load_flat_place.h
vpr/src/base/vpr_api.cpp

Updated the code for writing a post-placement flat placement file.
Added documentation to make this option easier to find.

[FlatPlacement] Updated Flat Placement Writing Code

---

vpr/src/base/vpr_api.cpp
vpr/src/pack/pack.cpp

Two PRs conflicted with each other and failed after merging. Hotfix to fix the build issue.

[HotFix] Fixed Build Issue in Master

---

vpr/src/analytical_place/analytical_placement_flow.cpp
vpr/src/analytical_place/full_legalizer.cpp
vpr/src/analytical_place/full_legalizer.h
vpr/src/base/vpr_api.cpp
vpr/src/base/vpr_types.h
vpr/src/pack/cluster_legalizer.cpp
vpr/src/pack/cluster_legalizer.h
vpr/src/pack/pack.cpp
vpr/src/pack/pack.h

Found some arguments to the Cluster Legalizer Constructor which ultimately led to no change. Removed them to make the Cluster Legalizer easier to work with.

[Pack] Cleaned Up Cluster Legalizer Constructor

---

README.md

Update README.md to point to VTR 9 paper

---

README.md

Add pointer to VTR9 paper in the readme

---

vpr/src/analysis/timing_reports.cpp
vpr/src/analysis/timing_reports.h
vpr/src/power/PowerSpicedComponent.h
vpr/src/power/power.h
vpr/src/power/power_callibrate.cpp
vpr/src/power/power_callibrate.h
vpr/src/power/power_cmos_tech.cpp
vpr/src/power/power_cmos_tech.h
vpr/src/power/power_components.cpp
vpr/src/power/power_components.h
vpr/src/power/power_lowlevel.h
vpr/src/power/power_sizing.cpp
vpr/src/power/power_sizing.h
vpr/src/power/power_util.cpp
vpr/src/power/power_util.h
vpr/src/util/hash.cpp
vpr/src/util/hash.h
vpr/src/util/vpr_net_pins_matrix.h

Continued the cleanup into the analysis, power, and util directories.
Nothing majorly changed.

[Infra] Cleaned Up Includes in Analysis, Power, and Util Dirs

---

README.developers.md

Added basic information on building with debug information and verbose output to developer guide

---

doc/src/conf.py

A failing python formatting check got into Master. Fixing it.

[HotFix] Fix Failing Python Formatting Check

---

vpr/src/place/initial_placement.cpp

In the AP flow, the initial placement stage will try to create a minimum displacement placement based on the flat placement and the clustering. It does this by iteratively trying to place clusters farther and farther from where they want to be placed (according to the flat placement).
I found that this flow was having issues with macros that contained multiple clusters. If these blocks are placed too late, they may not find a hole big enough for them to fit into. To resolve this issue, split the initial placer into stages such that all fixed blocks are placed first (this blocks must be placed first to ensure other blocks don't take their spots), then all large macros are placed, then all remaining clusters are placed.
I expected to make this a backup flow, which only turned on if the …

[AP][IP] Split Initial Placement Into Stages

---

libs/libarchfpga/src/physical_types.h

Add an array storing interconnect type name

Interconnect Type Name

---

libs/librrgraph/src/base/rr_graph_type.h
vpr/src/route/rr_graph_generation/rr_graph.cpp

Found a bunch of low hanging fruit when going through the RRGraph to code.

[RRGraph] Small code clean up according to coding style

---

doc/src/vpr/graphics.rst

Fixed typo from https://github.com/verilog-to-routing/vtr-verilog-to-routing/pull/3249

[Docs] Fixed Typo in Graphics Code

---

doc/src/vtr/run_vtr_flow.rst

Updated slang documentation. Removed section for Yosys-SystemVerilog parser plugin. Made a note describing yosys-slang as experimental.
Made documentation for yosys-slang more clear.
- [ x] I have updated the documentation accordingly

Updating Slang Documentation 
